import { FlatList, StyleSheet, Text, View } from "react-native";
import React from "react";
import { useRoute } from "@react-navigation/native";
import { COLORS, SIZES } from "../../constants/themes";
import { SafeAreaView } from "react-native-safe-area-context";
import Appbar from "../../components/Reuseable/Appbar";
import MedicineTile from "../../components/Reuseable/MedicineTile";

const Balaroga = ({ navigation }) => {
  const route = useRoute();
  const { item } = route.params;
  const Balaroga = [
    {
      id: "1",
      department: "Balaroga",
      disease: "Anaemia",
      therapy: "Rasayana Therapy",
      therapy_elaborate:
        "Rasayana essentially means nutrition at all levels from macro to micro-cellular level. Rasayana therapy replenishes the vital fluids of the body; boost the ojas (vital force of life) and the immune system, thus keeping away from diseases and prevents against ill effects of advanced age.Rasayanas are supposed to rejuvenate body and mind and restore them to an excellent condition. Therefore, many Rasayana cures include herbal plants, detoxification, relaxation techniques and massages. It is best to seek the advice of an Ayurveda therapist as they can personalise your care,further divided into 3 types – 1. Aushadha Rasayana – Based on drugs and herbs 2. Ahara Rasayana – Based on diet and nutrition 3. Achara Rasayana – Based on conduct, behavior and lifestyle. One of the most important therapeutic benefits in cancer patients is improvement in health related to quality of life. We have documented changes in quality of life of several cancer patients using validated quality of life questionnaire. It has been clearly demonstrated that Rasayana significantly increases functional, emotional and physical domains of quality of life. This outcome is considered very useful in advanced stage cancer patients to whom curative goal is not feasible. For such patients Rasayana helps to lead a near normal quality of life without any side effects or toxicity. Moreover, Rasayana can be taken at home which reduces requirement of hospitalisation.",
      medicine: "Amla,Punarnava,Haritaki,Draksha,Shatavari,Mustak",
      description:
        "1.Amla is generally known as an Indian Gooseberry. The berries of the trees are potently used for medicinal formulations due to their healing properties. Amla tree contains small berries that are round and yellowish-green in colour. Due to its several health benefits, it should be referred to as a superfood. In ancient Ayurveda, the Amla is known by a different name such as sour, nurse, immortality, and mother.One unique taste characteristic of Amla is full of five different tastes like pungent, astringent, sweet, bitter, sour, and other than this; it helps in keeping better health of mind and body,2.Punarnava is a well known medicinal plant packed with essential nutrients, vitamins such as vitamin C and other constituents.Taking Punarnava juice before meals might help manage stomach disorders such as constipation by promoting bowel movements due to its laxative property. It also provides relief from gas and abdominal pain,3.Prized as the “King Of Medicines”, Haritaki is a miraculous ayurvedic fruit that is extensively used for a wide range of traditional remedies. Cultivated from the seeds of Terminalia chebula tree, it is popularly known as Indian walnut for its innumerable benefits or Indian hog plum in English,4.Drakshais well known for its sweet fruits. It is commonly knownas Grapes and is cultivated through out India. Draksha have sweet taste like that of nectar and is also known as Madhurasa. Vinifera indicates that it is used for making wine. Draksha have many therapeutic properties,5.Shatavari is an Ayurvedic rasayana herb which is also known as the female-friendly herb. It is helpful in menstrual disorders and acts as a uterine tonic. It enhances breast development and increases breast milk production by regulating hormonal balance.Shatavari is also beneficial for men as it improves testosterone levels. It might be good for diabetics as it helps manage blood sugar levels. Shatavari might also promote memory functions due to its antioxidant activity,6.Musta is a well-known atisaraghna (antidiarrheal) and grahi (absorbing/preventing water loss from the body) drug of Ayurveda. It is mentioned in Nighantus (lexicons) of Ayurveda that, it is increasing agni and thereby cure the problems of gastro intestinal tract. ",
      use: "1.amla is good for iron-deficiency anemia, it is rich in Vitamin C that helps in better absorption of iron in our body. Once iron is absorbed by the body, it is used to make hemoglobin, which is a protein found in red blood cells and hemoglobin transports oxygen throughout the body.The fruit is used either alone or in combination with other plants to treat many ailments such as common cold and fever; as a diuretic, laxative, liver tonic, refrigerant, stomachic, restorative, alterative, antipyretic, anti-inflammatory, hair tonic; to prevent peptic ulcer and dyspepsia, and as a digestive,2.Punarnava might help in anaemia as it helps to increase the total haemoglobin count which may be due to iron present in it. Anemia is a condition of low hemoglobin, which generally occurs due to an imbalance of Pitta dosha and weak or poor digestion.he root extracts of Punarnava can stimulate the white blood cells and increase the tolerance to stress. The plant has an anti-fibrinolytic activity that helps to decrease the deposition of fibrin and platelets in vessels,3.Pernicious anemia treatment using Haritaki is recommended for the patients who suffer from peptic ulcers that cause continuous bleeding from the lesions.Haritaki helps in improving appetite and helps in the digestion. In anemia of any origin, Haritaki herb is highly beneficial. It helps anemia due to haemoglobin deficiency, anemia due to red blood cell deficiency, and anemias of abnormal form origin,4.Raisins or Draksha- enriched with iron and vitamins, it helps to boost Hb level and combats iron deficiency anemia. Cinnamon or Tvak- with haematinic properties, it helps improve blood health. Indian rose chestnut or Nagakesara- helps to enhance the absorption of iron,5.Shatavari's benefits for anemia are attributed to its rich iron content. Iron is crucial for haemoglobin production and is responsible for oxygen transport in the body. Shatavari enhances iron levels, aiding in the formation of healthy red blood cells and preventing anemia,6.Mustak is also one of the best herbs for anaemia, as it helps in natural healing. Therefore, If there is difficulty in consuming the supplements, then you can drink mustak juice or tea to fight anaemia. Other sources of iron are soy sprouts, quinoa and amaranth.",
      imageUrl:
        "https://brookefieldhospital.com/wp-content/uploads/2023/06/Understanding-GallBladder-Stone-Surgery-Everything-You-Need-to-Know-21-1024x536.png",
    },
    {
      id: "2",
      department: "Balaroga",
      disease: "Asthama",
      therapy: "Panchakarma Therapy",
      therapy_elaborate:
        "Panchakarma, that involves 5 (panch) actions of therapeutic treatment (karma), is very useful for asthmatic patients. It is a detoxification process that takes a person through 5 stages that involves the uses of herbs, herbal oils, medicated milk, and other Ayurvedic medicines.",
      medicine: "Pippali,Madhu,Rasonam,Shunthi,Vasa",
      description:
        "1.Pippali is an essential herb used in various Ayurvedic medicines. The roots and fruits of Pippali are used for its medicinal purposes. Fruits of this plant are slight yellow to orange in color and pungent in taste.The traditional herb goes by the botanical name Piper longum and comes from the Piperaceae family. The holistic science of ayurveda classifies this herb as a potent rejuvenative herb that has strong anti-ageing and aphrodisiac effects on the body and is widely used for treating diabetes, asthma, indigestion, cough and cold,2.Honey known as madhu in ayurvedic scriptures is one of the most important medicines used in ayurveda. In ayurveda, honey is used for both internal and external applications. It is mainly used for the treatment of eye diseases, cough, thirst, phlegm, hiccups, blood in vomit, leprosy, diabetes, obesity, worm infestation, vomiting, asthma, diarrhoea and healing wounds. It is also used as a natural preservative and sweetener in many  ayurvedic preparations,3.This is the ayurvedic or Sanskrit name for Garlic. Rasonam responds to TB effectively and helps in treating nervous, respiratory, digestive, circulatory and reproductive system. Tuberculosis infects the person in almost every area; rasonam helps to stimulate energy in the body with its medicinal properties. It is antiseptic, antibacterial, antispasmodic, carminative and anthelmintic in nature,4.Shunthi (Sonth in Hindi), known in Botany with the name of Zingiber officinale, is quite a recognized Ayurvedic herb. It always grows erect to about one meter height and has rhizomes that are tuberous, horizontal and a little aromatic. Drying of ginger after its processing with the help of lime water, Shunthi or Sonth is prepared. It is a commonly used ingredient in Trikatu powder. It is hot in effect but adds taste to the food. It is useful in promoting digestive fire and helps in rheumatoid arthritis and aamvata,5.Vasa commonly known as Malabar nut is one most significant herb used in Ayurveda. The name ‘Vasa’ itself means that plant alleviates many diseases and restores the health. The word ‘Adhatoda’ is derived from its Malabar name ‘Adalodaka’ and ‘vasica’ indicates its fragrance. Vasa is found abundantly through out India and is one of the most useful herb ever found.",
      use: "1.Pippali is an effective home remedy in managing cough and cold. Swallowing Pippali powder along with honey after lunch and dinner helps release mucus from the air passages due to its expectorant property, thus allowing the patient to breathe easily. It’s consumption might also help promote weight loss by improving the body’s metabolism. Consuming Pippali powder might be useful in managing constipation by promoting bowel movements due to its laxative property,2.Respiratory tract disorders: It is useful in common cold, sore throat and cough with sputum. Healing property: Due to Shodhana (purification), Ropana (healing), and Sandhana (union) properties it is useful for topical application on wounds and mouth ulcers. Navin Madhu acts as laxative,2.In Ayurveda, honey is used for both internal and external applications.  It shows mild laxative, bactericidal, sedative, and antiseptic properties and is found to be useful in the treatment of bronchial asthma, tuberculosis, cough and cold, eye diseases, wounds, constipation, hiccups, skin disorders, worm infestation and urinary tract disorders etc. Old honey reduces fat and obesity and is highly scarificant,3.Garlic also expels phlegm and opens your obstructed veins for removal of impure blood. This herb can be had with many beverages or used as a paste for more effectiveness. It targets the nerve tissues, lungs, bronchi and treats fever that is caused by bacteria in the body,4.The oil secretion in body is boosted as it contains aromatic oil. Despite being pungent, Shunthi is very helpful in increasing the quality of semen. It also helps in constipation because of its quality of digestion effect after consumption. It helps check vomiting, promotes voice effect and is useful in many gastric ailments. It is useful in elephantiasis, abdominal digestion, edema and relieves pain in piles,5.Vasa is useful in many diseases like Hemorrhage, Fever, Cough, Asthma, Skin allergies, Jaundice, Anorexia etc. Malabar nut have properties like bronchodilation, expectorant, abortificient, hypoglycemic etc.",
      imageUrl:
        "https://irp.cdn-website.com/2e75da1a/dms3rep/multi/normal-vs-asthma-lung.png",
    },
    {
      id: "3",
      department: "Balaroga",
      disease: "Diphtheria",
      therapy: " Raktamokshana",
      therapy_elaborate:
        "Your eyes will be covered using a cotton pad and bandage. The doctor will make several small cuts/ pricks over an area on the skin using a lancet or sterile blade. After the pricks are made, the oozed blood will be wiped off. The area will be cleaned using antiseptic.Raktamokshana is an effective blood purification therapy, in which carefully controlled removal of small quantities of blood is conducted to neutralise accumulated Pitta toxins of many blood-borne diseases.",
      medicine: "Garlic,Lemon,Mullein,Raspberry leaves,Bayberry",
      description:
        "1.Garlic (Allium sativum) is an herb related to onion, leeks, and chives. It is commonly used for conditions related to the heart and blood system.Garlic produces a chemical called allicin. This is what seems to make garlic work for certain conditions. Allicin also makes garlic smell. Some products are made 'odorless' by aging the garlic, but this process can also change the effects of garlic,2.Lemons are a nutritious fruit that can provide several health benefits. They are a rich source of vitamin C and consuming them may reduce the risk of heart disease and cancer.Lemons are a popular fruit that people use in small quantities to add flavor to baked goods, sauces, salad dressings, marinades, drinks, and desserts. However, they rarely consume them alone due to their intense, sour taste,3.Mullein is a plant. The flower is used to make medicine.Mullein is used for cough, whooping cough, tuberculosis, bronchitis, hoarseness, pneumonia, earaches, colds, chills, flu, swine flu, fever, allergies, tonsillitis, and sore throat. Other uses include asthma, diarrhea, colic, gastrointestinal bleeding, migraines, joint pain, and gout. It is also used as a sedative and as a diuretic to increase urine output.Mullein is applied to the skin for wounds, burns, hemorrhoids, bruises, frostbite, and skin infections (cellulitis). The leaves are used topically to soften and protect the skin,4.Raspberries (Rubus idaeus) are popular red berries that are native to Europe and parts of Asia. It’s the leaf of the plant that is used to make the herbal tea of the same name. Raspberry leaf tea has been used over many years to treat certain ailments and to facilitate labour and childbirth. However, evidence for its benefits is weak and more research is needed to assess its efficacy,5.Myrica esculenta is a tree or large shrub native to northern India, Its common names include box myrtle, bayberry and kafal. Its berries are edible and are consumed locally. The tree is harvested from the wild for local use as a food, medicine. Fruits are eaten raw and also made into syrup, jam, and squash. The ripe fruit is eaten raw it has a pleasantly sweet and sour taste with a strawberry note. ",
      use: "1.People commonly use garlic for high blood pressure, high levels of cholesterol or other fats in the blood, and hardening of the arteries. It is also used for the common cold, osteoarthritis, and many other conditions, but there is no good scientific evidence to support these uses. There is also no good evidence to support using garlic for COVID-19.Garlic (or lahsoon in Hindi) is an effective home remedy for curing various ailments, including diphtheria. It is said that taking a spoonful of 2-3 crushed garlic cloves can help lower the fever and cure this disease,2.Vitamin C is essential for health, and a deficiency can lead to health problems. The early explorers knew this and took lemons on their long voyages to help prevent or treat scurvy, a life threatening condition that was common among sailors.Lemon juice is not part of cancer treatment.But scientists have found tiny nanoparticles in lemon juice that – in lab tests on cells – inhibited cell reproduction and activated cancer cell death. This is extremely early research that’s more about searching for new cancer treatments and isn’t based on the lemon juice you’d get in your diet,3.is classified in the herbal literature as both an expectorant, to promote the discharge of mucus, and a demulcent, to soothe and protect mucous membranes. Historically, mullein has been used as a remedy for the respiratory tract, particularly in cases of irritating coughs with bronchial congestion. Its leaves and flowers have been used for several conditions, including cough and other respiratory conditions. It's available as tinctures, teas, capsules, and elixirs. It's generally considered safe with few reports of side effects,4.The tea can be purchased loose as leaves, in tea bags (check the product is made from 100% leaves) or in tablet form. Alternatively, you can make your own infusion using dried raspberry leaves. The astringency of the leaves produces a tea similar in taste to black tea, although commercial blends often combine the leaf with a sweeter tasting herb, such as peppermint,5.It is widely used in folk medicine to treat several ailments such as asthma, cough, chronic bronchitis, ulcers, inflammation, anemia, fever, diarrhea, and ear, nose, and throat disorders.Despite safety concerns, bayberry is used for colds, diphtheria, nausea, skin wounds, and many other conditions, but there is no good scientific evidence to support these uses.",
      imageUrl:
        "https://i0.wp.com/dubawa.org/wp-content/uploads/2023/02/Diphtheria.png?fit=1000%2C620&ssl=1",
    },
    {
      id: "4",
      department: "Balaroga",
      disease: "Leukamia",
      therapy: "Raktamoshana & Basti (Enema Therapy):",
      therapy_elaborate:
        "Your eyes will be covered using a cotton pad and bandage. The doctor will make several small cuts/ pricks over an area on the skin using a lancet or sterile blade. After the pricks are made, the oozed blood will be wiped off. The area will be cleaned using antiseptic.Raktamokshana is an effective blood purification therapy, in which carefully controlled removal of small quantities of blood is conducted to neutralise accumulated Pitta toxins of many blood-borne diseases &  Basti involves the use of herbal enemas to cleanse and rejuvenate the colon. It is considered one of the most important Panchakarma procedures and is used to address various health issues, including chronic constipation and imbalances in Vata dosha.",
      medicine: "Ashwagandha,Guduchi,Cucurmin,Neem,Vibhitaki",
      description:
        "1.Ashwagandha (Withania somnifera), also known as Indian ginseng, is an herb used in Ayurveda, the traditional medicine of India. Its root has a horsey smell and is said to confer the strength and virility of a horse. In Sanskrit, ashva means “horse” and gandha means “smell.” Various parts of the plant are used, but the most common supplemental form is an extract of its roots. Its use as part of the Ayurvedic system usually involves more than just the herb alone.Ashwagandha is best known for its anxiolytic (anti-anxiety) and stress-relieving effects.It also seems to reduce cortisol levels,2.Guduchi which goes by the scientific name Tinospora cordifolia is an extremely essential immunomodulator herb and a base ingredient of numerous Ayurvedic formulations. Deemed as ‘Queen Of Herbs’, Guduchi plays a significant role in the promotion and restoration of health and curing several diseases and infections,3.Curcuma longa, a flowering plant of the ginger family best known as a spice used in curry. It is a polyphenol with anti-inflammatory properties and the ability to increase the amount of antioxidants that the body produces.Curcumin and the curcuminoids found in turmeric can be extracted to produce supplements that have a much higher potency than turmeric. However, orally ingested curcumin is poorly absorbed during digestion,so a variety of different formulations have been created to improve its bioavailability,4.Neem is a natural herb from the neem tree, other names for which include Azadirachta indica and Indian lilac. There are some potential health benefits of neem, but it is also possible for someone to have a neem allergy or sensitivity.The extract comes from the seeds of the tree and has many different traditional uses. Neem is known for its pesticidal and insecticidal properties, but people also use it in hair and dental products.Neem is a revered tree in Ayurveda, and its leaves, bark, and oil are known for their potent antimicrobial and antibacterial properties,5.Vibhitaki, named in Botany as Terminalia Bellirica, is very useful in all the gastric problems, keeps the digestive track clear and allows it to work at its optimum. It is one of the three major components of Triphala and it has been certified by the Ayurvedic Pharmacopoeia of India that the powder of Vibhitaki can be used to deal worm infestation and nausea.Gallic acid, ß-sitosterol, chebulagic acid, ethyl gallate, ellagic acid, and galloyl glucose are components of herb",
      use: "1.In some studies it was found that Ashwagandha might reduce the growth breast, colon, lung, and central nervous system cancer cells without damaging the normal cells. However, it was ineffective against the drug-resistant stem-like cancer cells.Other reported benefits of ashwagandha include better memory and attention span, reduced food cravings, lower blood sugar, increased muscle mass and strength and better heart health,Ashwagandha is renowned in Ayurveda for its powerful adaptogenic properties. It is known to help the body adapt to stress, balance the nervous system, and strengthen the immune system.During leukemia treatment, the immune system can be compromised. Ashwagandha's immune-boosting properties may enhance the body's ability to fight infections and cope with the stress of treatment, improving overall resilience,2.Strengthening the immune response is crucial during leukemia treatment. Guduchi's immunomodulatory properties may aid in fortifying the body's defenses, making it better equipped to handle the challenges of the disease and its treatment.,3.Turmeric contains a bioactive compound called curcumin, which is known for its potent anti-inflammatory and antioxidant properties. It has been extensively studied for its health benefits.Curcumin's anti-inflammatory properties may assist in reducing inflammation often associated with leukemia. Additionally, its antioxidant properties help protect cells from oxidative stress. This can be particularly beneficial during leukemia treatment to support the immune system,4.Neem is a natural herb from the neem tree, other names for which include Azadirachta indica and Indian lilac. There are some potential health benefits of neem, but it is also possible for someone to have a neem allergy or sensitivity,4.Leukemia patients are vulnerable to infections due to a weakened immune system. Neem's antimicrobial properties make it a valuable herb for managing infections that may arise during leukemia treatment. It can contribute to overall well-being by helping to control these infections,5.It has numerous health benefits on the human body. Its action on the heart makes it an excellent heart tonic. It helps in purifying blood, thinning of blood, and removing toxins. It is used in cases of low RBC count and low haemoglobin. Vibhitaki helps cases of anemia of any origin and help regain healthy haemoglobin count and form. Our product Sanjeevani vati has Vibhitaki.",
      imageUrl:
        "https://upload.wikimedia.org/wikipedia/commons/3/3a/Symptoms_of_leukemia.png",
    },
    {
      id: "5",
      department: "Balaroga",
      disease: "Measeles",
      therapy: "Panchakarma Therapy",
      therapy_elaborate:
        "Panchakarma, that involves 5 (panch) actions of therapeutic treatment (karma), is very useful for asthmatic patients. It is a detoxification process that takes a person through 5 stages that involves the uses of herbs, herbal oils, medicated milk, and other Ayurvedic medicines.",
      medicine: "Liquorice,Garlic,Lemon,Karela & Haldi Jad,Barley,Amla",
      description:
        "1.Licorice is an herb that grows in parts of Europe and Asia. Licorice root contains glycyrrhizin, which can cause side effects when eaten in large amounts.The chemicals in licorice are thought to decrease swelling, decrease cough, and increase the chemicals in our body that heal ulcers. Many 'licorice' products made in the U.S. actually don't contain licorice. They contain anise oil, which has the smell and taste of 'black licorice',2.Garlic consists of fresh or dried bulbs of the botanical plant Allium sativum. It’s cultivated worldwide. The bulb, or clove, is the part of the plant that’s used most often. Garlic is best stored hung in a dry place. Garlic can be consumed fresh, as a powder sprinkled over food, or as garlic oil to flavor foods,3.Lemons are a nutritious fruit that can provide several health benefits. They are a rich source of vitamin C and consuming them may reduce the risk of heart disease and cancer.Lemons are a good source of vitamin C. One 58 gram (g) lemon can provide over 30 milligramsTrusted Source (mg) of vitamin C.Vitamin C is essential for health, and a deficiency can lead to health problems. The early explorers knew this and took lemons on their long voyages to help prevent or treat scurvy, a life threatening condition that was common among sailors,4. Bitter melon is a perennial plant that grows in the tropical and subtropical regions of Asia, South America, East Africa, and the Caribbean. The edible fruit is used both as food and in medicine to treat diabetes, cancer, viral infections, and immune disorders,whereas In India, it was traditionally used for disorders of the skin, upper respiratory tract, joints, and digestive system. Today, turmeric is promoted as a dietary supplement for a variety of conditions, including arthritis, digestive disorders, respiratory infections, allergies, liver disease, depression, and many others,5.Barley (Hordeum vulgare) is a common grain that is high in fiber. It's consumed in foods and used to brew alcoholic beverages worldwide.The fiber in barley might lower cholesterol, blood sugar, and insulin levels. It also seems to slow stomach emptying,6.Amla, also known as Indian gooseberries, grows on a flowering tree of the same name. The small berries are round and bright or yellow-green. Though they are quite sour on their own, their flavor can enhance recipes they’re added to.It's no surprise — a 100-gram serving of fresh amla berries contains as much vitamin C as 20 oranges.",
      use: "1. Half a teaspoon of liquorice root ground into powder along with a little drop of honey can cure you effectively from measles. You got to consume this daily while you are infected,2.Not just in your kitchen space, garlic rules when it comes to treating measles the natural way as well. All you need to do is take some cloves of garlic, powder them and consume with some honey and of course get well sooner from measles,3. If you are fond of lemon juice, this is good news. You may just consume more of it in case you are struck with measles. 15 to 25ml of lemon juice squeezed in the water is a perfect natural therapy to cure it,4.This may not taste too good but it's a saviour in case you contract measles. Juice the bitter gourd leaves, add it to a mix of turmeric root and honey and fight measles the best way,5.For managing coughs, barley water is best. Drinking barley water flavoured with some sweetened almond oil quite often gives you immense relief if you are suffering from measles,6.Amla mixed with water is the best way to get rid of burning and itching sensation during measles. If possible, take a shower in amla rinsed water for better result.",
      imageUrl:
        "https://www.medicoverhospitals.in/images/diseases/measles.webp",
    },
    {
      id: "6",
      department: "Balaroga",
      disease: "Mumps(Karnamulaka Jwara)",
      therapy: "Nasyam",
      therapy_elaborate:
        "It is one of the mainstream Panchakarma procedure. Medicated powder, oil, ghee or the herbal decoctions are poured inside the nostrils according to the dosha involved. It cleanses the organs above the neck and strengthens the nervous system.",
      medicine: "Cucurmin,Guduchi,Boswellia,Guggul",
      description:
        "1.Curcuma longa, a flowering plant of the ginger family best known as a spice used in curry. It is a polyphenol with anti-inflammatory properties and the ability to increase the amount of antioxidants that the body produces.Curcumin and the curcuminoids found in turmeric can be extracted to produce supplements that have a much higher potency than turmeric. However, orally ingested curcumin is poorly absorbed during digestion,so a variety of different formulations have been created to improve its bioavailability,2.Guduchi which goes by the scientific name Tinospora cordifolia is an extremely essential immunomodulator herb and a base ingredient of numerous Ayurvedic formulations. Deemed as ‘Queen Of Herbs’, Guduchi plays a significant role in the promotion and restoration of health and curing several diseases and infections,3.Boswellia is an herbal extract made from the bark of the boswellia tree. It is also known as frankincense. The resin (sticky substance found in trees and plants) is used to make an extract.Boswellia resin is used in Ayurvedic (traditional Indian) medicine. You can take boswellia in different ways, including taking it orally (by mouth) in a capsule, pill, or tablet, or using it as an oil that you can put on your body,4.Guggul is also known as “Pura” which means “wards off disease”. It is used as a source of commercial “Gum guggul”. The major bioactive component of Guggul is oleo-gum-resin (a mixture of an oil and yellowish or brownish fluid secreted from the plant stem or bark). It is this oleo-gum resin that is said to have therapeutic benefits. Guggul is useful in weight management as it helps to improve metabolism and reduce Ama (toxic remains in the body due to improper digestion) by increasing the digestive fire. It also helps to reduce swelling, pain and stiffness in joints in case of osteoarthritis as well as rheumatoid arthritis due to its anti-inflammatory and anti-arthritic properties. Guggul might also be helpful in managing blood cholesterol levels by lowering total cholesterol, low-density lipoprotein (LDL or bad cholesterol) and triglyceride levels.",
      use: "1.Aloe vera has soothing properties that can bring relief from swelling and pain. Neem leaves have been used since ancient times to treat mumps. Neem leaves reduce itching and swelling and can be mixed with turmeric powder to form a paste that can be applied to the swelling,2.Drink plenty of fluids, but avoid acidic drinks such as fruit juice. Apply a warm or cool compress to your swollen glands to help reduce any pain. Eat foods that don't need a lot of chewing guduchi leaves and drinking Giloy kadha for relieving pains of mumps,3.Boswellic acids have been recognized as anti-inflammatory and immunomodulatory agents with potentials to control autoimmune and inflammatory diseases. taking approximately 300–400 milligrams (mg) of boswellia three times per day to deliver boswellic acids to the body. They recommend looking for capsules that contain 60% boswellic acid, as it is the active ingredient,4.Guggul can be taken in the form of powder, tablet or capsule to help reduce the production of sebum which inhibits the growth of acne-causing bacteria due to its antibacterial property.Applying a paste of Guggul mixed in warm water on the joints helps to reduce mumps pain.It should be kept in mind that Guggul should always be chewed well before swallowing in order to get the maximum benefits",
      imageUrl: "https://ssl.adam.com/graphics/images/en/24397.jpg",
    },
    {
      id: "7",
      department: "Balaroga",
      disease: "Pneumonia",
      therapy: "Nasyam Therapy",
      therapy_elaborate:
        "Putting two drops of sesame oil in each nostril cleans the nasal passage and acts as a detoxifying agent for the lungs in a highly polluted environment. This practice is called 'Nasya' in Ayurvedic literature. Nasya is great for overall wellness too as it helps in many health issues by strengthening the immune system.",
      medicine: "Amlaki,Bhringraj,Tila,Pippali,Yastimadhu",
      description:
        "1.Amla is generally known as an Indian Gooseberry. The berries of the trees are potently used for medicinal formulations due to their healing properties. Amla tree contains small berries that are round and yellowish-green in colour. Due to its several health benefits, it should be referred to as a superfood. In ancient Ayurveda, the Amla is known by a different name such as sour, nurse, immortality, and mother,2.Bhringraj is also known as Kesharaj which means “Ruler of the hair”. It is rich in proteins, vitamins and antioxidants which help protect the body against certain infections.Bhringraj oil is is effective in promoting hair growth as well as reducing the greying of hair. This is due to the presence of various nutrients in Bhringraj that provide nourishment to the hair scalp. According to Ayurveda, Bhringraj juice rejuvenates the skin and thereby helps reduce the signs of aging such as fine lines, wrinkles and patchy skin due to its anti-aging property. Bhringraj powder along with a carrier oil (like coconut oil) can also be used to manage skin infections and allergies due to its antimicrobial property,3.Sesame seeds also known as Til, is mainly grown for its seed and oil. It is packed with various nutrients and fibre and can be beneficial to add in your daily diet. Sesame seeds can be consumed roasted, crushed or sprinkled over salads.Sesame seeds and Sesame seed oil can be used for cooking and might be useful in managing cholesterol as it helps maintain the level of good cholesterol (HDL) and lowers bad cholesterol (LDL) in the blood,4.Pippali is an essential herb used in various Ayurvedic medicines. The roots and fruits of Pippali are used for its medicinal purposes. Fruits of this plant are slight yellow to orange in color and pungent in taste,5.A hardy leguminous undershrub attaining the height of about 3 meter with compressed pods. It is found growing wild in many Asian countries and is also cultivated at small scales in India, Iran, Afghanistan etc. The root tastes sweet and is used in Ayurveda.",
      use: "1.Amlaki is well known for its immunity-enhancing and anti aging properties.It is effective in relieving symptoms of lung inflammation associated with pneumonia.It hosts several antibacterial compounds,which aids in clearing out the infectious microbes responsible for pneumonia infection.Flavanoids and Vitamin C in amalaki are potent antioxidants that prevent lung tissue damage associated with pneumonia, best suitable for pneumonia if eating raw,2.Leaves and roots of bhringraj have been used in Ayurvedic medicines for its antipyretic,rejuvinating and tonic properties.Together these properties of bhringraj are useful in reducing the microbial activity associated with pneumonia and improving the overall health.It is administered in the form of infusion,powder,decoction,medicated oil or ghee(clarified butter),3.Seeds,oil and leaves of tila are used in ayurvedic medicine for various therapeutic purposes.It acts as a tonic rejuvenator and aids in the treatment of diseases associated with the reproductive,excretery,urinary and respiratory systems.It helps treat pneumonia by inhibiting the action of microorganisms associated with this infection,4.This is because Pippali has decongestant, bronchodilator and expectorant effects due to its Kapha balancing properties. Pippali shows good result in cough and cold when it is taken with honey. Pippali also gives rejuvenating effect on the lungs due to its Rasayana (rejuvenating) nature. Take 2-3 pinch of Pippali powder. Swallow it with honey after lunch and dinner to manage the symptoms of pneumonia,5.Mulethi, due to its emollient and demulcent properties has a soothing effect on throat. So, it helps to relieve scratchy throat, throat irritation and hoarseness of voice. Due its expectorant property, it promotes drainage of thick mucus from the lungs, bronchi and trachea by thinning the mucus, and also lubricates the irritated respiratory tract. With its antibacterial, antiviral, anti-allergic and anti-inflammatory properties, Mulethi helps to fight respiratory infections. It also helps to boost our immunity against these infections due to its immuno-modulatory property.",
      imageUrl: "https://medlineplus.gov/ency/images/ency/fullsize/19680.jpg",
    },
    {
      id: "8",
      department: "Balaroga",
      disease: "Polio",
      therapy: "Njavarakizhi",
      therapy_elaborate:
        "A generous amount of medicated oil is applied to the whole body and then the body is massaged with small cotton cloth boluses filled with cooked Njavara rice. We do Ayurvedic treatment for paralysis. The boluses are dipped in this regenerating mixture of cow’s milk and a brewed herbal decoction, and then applied all over the body to induce sudation (sweat). This procedure is highly rejuvenating, nourishing and prepares the individual to bear the stresses and strains of a busy lifestyle. It enhances physical consistency, strengthens the nervous system and improves the overall appearance of the skin.This treatment is done with specific Kizhis (Pouches) made up of special Navara Rice which has amazing medicinal value. These warm kizhis are applied to the body of the patient who lays in the Dhroni. We do polio treatment for the person who suffers from many years ago. This is applied by two masseurs for about 60 to 90 minutes per day for a period prescribed by the Doctor. Najavarakzhi treatment is for all types of rheumatism pain in the joints, emaciation of limbs, high blood pressure, and high cholesterol. This is found to be very effective for Polio and paralysis. There is great relief from joints pain.Njnavarakizhi which is known as shashtikashali pinda swedam is a therapy in which Kizhi (bolus) filled with Njavara rice ( a variety of rice grown in Kerala) is used to massage all over the body. Njavarakizhi is the best treatment for rejuvenating your body and found to be very effective for arthritis, blood born diseases, hemiplegia, scoliosis, spasticity, kyphosis, cervical myelopathy and Perthes disease.",
      medicine: "Daruharidra,Ashwagandha,Nimba,Jatiphala",
      description:
        "1.Daruharidra is also called as Indian barberry or Tree Turmeric. It has been used in Ayurvedic medicine system since a long time. The fruit and stem of Daruharidra are widely used for its medicinal benefits. The fruit is edible and is a rich source of vitamin C.Daruharidra is mainly beneficial for skin problems like inflammation and psoriasis as it has anti-inflammatory and anti-psoriatic activity. It helps in managing acne by preventing the growth of acne causing bacteria and reducing inflammation due to its antibacterial and anti-inflammatory properties,2.Ashwagandha is an evergreen shrub that grows in Asia and Africa. It is commonly used for stress. There is little evidence for its use as an 'adaptogen'.Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system.Adaptogens are believed to help the body resist physical and mental stress. Some of the conditions it is used for include insomnia, aging, anxiety and many others, but there is no good scientific evidence to support most of these uses. There is also no good evidence to support using ashwagandha for COVID-19,3.Nimba means neem, which is the main ingredient. It is used in the Ayurvedic treatment for skin diseases, gout etc. Benefits of Nimba Churna: It is used in the Ayurvedic treatment of skin diseases, gout, leukoderma, skin eruptions, psoriasis,4.Jatiphala is a classical Ayurvedic herb known to be digestive tonic, aphrodisiac, beneficial in Kasa, Swasa, Shiroshoola, etc.Jatiphala consists of the endosperm of dried seeds (kernels of fruits) of Myristica fragrans Houtt. (Fam. Myristicaceae), dioecious or occasionally monoecious aromatic tree, about 10-20 m high.",
      use: "1.According to Ayurveda, applying a paste of Daruharidra powder along with honey or rose water on burns helps in faster healing due to its Ropan (healing) property. Daruharidra might help to protect the liver and prevent liver disorders as it maintains the level of liver enzymes. It also protects the liver cells against damage caused by free radicals as it has antioxidant, anti-inflammatory and hepatoprotective activities,2.1 capsule twice a day or as prescribed by the doctor. Ashwagandha Churna - 1/4-1/2 teaspoon twice a day or as prescribed by the doctor.Generally, ashwagandha dose recommendations vary from 250 to 600 mg daily. For overall support and general well-being, this dose range is frequently employed. However, under the direction of a healthcare practitioner, some circumstances or objectives may call for greater dosages, up to 1,000 mg per day or more,3.A good tip is to mix neem leaves with honey or drinking neem leaves boiled in water on an empty stomach to counter the bitter taste,which will be very helpful in countering polio,4.You can make Jaiphal powder and mix it with honey, milk, tea, etc. It can also be added to soups, stews, puddings, kheers, and several bakery items and savories. Honey for weight loss can also be used to maintain a healthy Body Mass Index among women.",
      imageUrl:
        "https://www.dinf.ne.jp/doc/english/global/david/dwe002/dwe002g/dwe00209g01.gif",
    },
    {
      id: "9",
      department: "Balaroga",
      disease: "Whooping cough(Pertussis)",
      therapy: "Panchakarma Therapy",
      therapy_elaborate:
        "The name Panchakarma literally means 'Five Actions' which is well-suited given the fact that this technique relies upon five distinctive basic activities that control the body namely Vomiting, Purgation, Niruham, Anuvaasan, and Nasyam.Panchakarma is a treatment program for the body, mind, and consciousness that cleanses and rejuvenates. It is based on Ayurvedic principles, every human is a unique phenomenon manifested through the five basic elements of Ether, Air, Fire, Water, and Earth.The combination of these elements are three doshas (tridosha): Vata, Pitta, and Kapha, and their balance is unique to each individual. When this doshic balance is disturbed it creates disorder resulting in disease.Panchakarma is done individually for each person with their specific constitution and specific disorder in mind, thus it requires close observation and supervision. Treatment starts with pre-purification Measures of Snehan and Svedana, and then cleansing methods – Shodanas are applied.",
      medicine: "Eucalyptus Oil,Honey,Lemon,Garlic,Haldi,Mulethi",
      description:
        "1.Eucalyptus is a tree. Its leaves and oil have been consumed, chewed, and applied to the skin for many conditions.Eucalyptus contains many different chemicals. These chemicals might have various effects in the body. Also, some research suggests that eucalyptus may have activity against bacteria and fungi,2.Honey is a sweet liquid that bees produce using nectar from flowers. People throughout the world have hailed the health benefits of honey for thousands of years.Honey is available raw or pasteurized and in a variety of color grades. On average, it contains about 80%Trusted Source sugar. People remove honey from the hive and bottle it directly, so it may also contain trace amounts of yeast, wax, and pollen,3.The lemon is a bright yellow citrus fruit. It has its distinctive sour taste because it’s rich in citric acid. It comes from the flowering plant family rutaceae, and its scientific name is Citrus limon.The lemon’s unique flavor makes it a popular ingredient in drinks, desserts, and meals. Almost all parts of a lemon can be used in cooking and cleaning,4.Garlic (Allium sativum) is an herb related to onion, leeks, and chives. It is commonly used for conditions related to the heart and blood system.Garlic produces a chemical called allicin. This is what seems to make garlic work for certain conditions. Allicin also makes garlic smell. Some products are made 'odorless' by aging the garlic, but this process can also change the effects of garlic,5.Turmeric is a common spice that comes from the root of Curcuma longa. It contains a chemical called curcumin, which might reduce swelling.Turmeric has a warm, bitter taste and is frequently used to flavor or color curry powders, mustards, butters, and cheeses,6.Mulethi, also known as mulethi churna is one such classical ayurvedic remedy that has a centuries-long repute of being the ultimate grandma’s remedy for cough and sore throat.",
      use: "1.It is one of the best remedies to treat respiratory tract disorders, including sinusitis, bronchitis, and pharyngitis. If you have whooping cough symptoms and wondering how to prevent whooping cough naturally, then you should give it a try. Mix a few drops of eucalyptus oil with olive or coconut oil and apply it to your back and chest. Alternatively, add 3 to 4 drops of the oil blend in steaming hot water. Now you need to inhale the vapors at least three times a day,2.Intake of Honey is the next best thing you can go to get rid of whooping cough. To practice this pertussis treatment at home, all you need to do is eat two teaspoons of raw honey just half an hour before going to bed. It will help in reducing cough. It is an ideal treatment for both adults and children,3.Intake of Honey is the next best thing you can go to get rid of whooping cough. To practice this pertussis treatment at home, all you need to do is eat two teaspoons of raw honey just half an hour before going to bed. It will help in reducing cough. It is an ideal treatment for both adults and children,4.Garlic includes allicin – a compound exhibiting antibacterial properties. Hence, garlic can be ideally used for combating whooping cough-causing bacteria. Take 2-3 garlic cloves and mix them with raw Honey. Consume this mix 2 to 4 times daily for effective results,5.Turmeric includes curcumin compound, which has antimicrobial power for treating whooping cough issues and related problems. Mix half a teaspoon of turmeric powder in a cup of hot milk. Consume this mix daily before going to bed,6.Licorice includes glycyrrhizic acid, which is an immunity-boosting compound. If you have been wondering how to prevent whooping cough naturally, then you have licorice root working for you. It accelerates tissue healing damaged due to whooping cough. Take an adequate quantity of licorice root and steep in 50 ml of hot water. Strain it after 5 minutes and consume it warm. You may add Honey to it to enhance the taste. Consume this mix at least 3 to 4 times daily.",
      imageUrl:
        "https://www.netmeds.com/images/cms/wysiwyg/blog/2019/02/Whooping-coughr_898x898.jpg",
    },
    {
      id: "10",
      department: "Balaroga",
      disease: "Down's Syndrome",
      therapy: "Basti & Shirodhara",
      therapy_elaborate:
        "Basti treatments balance and nurture Vata dosha. When Vata usually functions, it helps bring toxins and waste matter out of the dhatus( body cells) and eliminates them. Basti has two actions, expelling the vitiated doshas ( morbid substances/toxins) and nourishing the body.The procedure is like a cleansing therapy, removing toxins and bringing back harmony in the body. The Basti procedure is primarily beneficial to people with Vata Dosha. This dosha affects the colon. The Panchakarma therapy involves accumulating all doshas in the abdomen and then removing them by using Basti,whereas Shirodhara is a classical and a well-established ayurvedic procedure of slowly and steadily dripping medicated oil on the center of the forehead of the patient, resting quietly on a comfortable bed. Other liquids like coconut water, buttermilk, milk, etc. are also used depending on the individual need of the patient.It is usually indicated to treat stress, anxiety, and insomnia and to relax the nervous system. Generally, sesame oil processed with various Indian herbs is used for Shirodhara.",
      medicine: "Guggul,Haritki,Draksha,Shankhapushpi,Brahmi",
      description:
        "1.Guggul is also known as “Pura” which means “wards off disease”. It is used as a source of commercial “Gum guggul”. The major bioactive component of Guggul is oleo-gum-resin (a mixture of an oil and yellowish or brownish fluid secreted from the plant stem or bark). It is this oleo-gum resin that is said to have therapeutic benefits. Guggul is useful in weight management as it helps to improve metabolism and reduce Ama (toxic remains in the body due to improper digestion) by increasing the digestive fire,2.Haritaki - a gift from Mother Earth, packed with the essence of holistic healing. It is one of Triphala's three magic ingredients, along with Amalaki and Bhibakti. Haritaki in Ayurveda is known for its healing and rejuvenating properties. It has antibacterial, anti-cancer, anti-diabetic, and antioxidant properties.Ayurveda believes that the body is comprised of three doshas namely Vata, Pitta, and Kapha. When haritaki is taken in appropriate quantities, it has the power to balance all three doshas. This quality makes it one of the most versatile herbs of Ayurveda,3.Common Grape Vine ( Vitis Vinifera ) is known as Draksha in ayurveda.  This is widely grown in western parts of India, Punjab, Kashmir, central Europe, Turkey, Morocco and Portugal. The grape vine has long, woody stems rooted to ground. Stems are covered with flaky bark. The grapevine usually grows up to 35 meters.It has alternative, broad, palmate leaves. The unripe fruit is usually green and ripe fruit is dark purple in color. Ripe fruits are covered with light grey wax coat,4.Shankhpushpi, which goes by the botanical name Convolvulus pluricaulis is a perennial plant native to India.Shankhpushpi characterizes Tikta Rasa (bitter taste). It shows Snigdha (oily, sticky) and Pichhil (slimy) gunas, Sheeto Virya (cold potency) and Madhura Vipaka (pungent metabolic property). It pacifies Tridoshas, i.e. the Pitta (fire and air), Vata (air) and Kapha (earth and water) doshas and works more on Vata and Pitta doshas,5.Brahmi (derived from the name of Lord Brahma and Goddess Saraswati) is a perennial herb most well known for its memory enhancing property.",
      use: "1.Guggul can be taken in the form of powder, tablet or capsule to help reduce the production of sebum which inhibits the growth of acne-causing bacteria due to its antibacterial property.Applying a paste of Guggul mixed in warm water on the joints helps to reduce joint pain.It should be kept in mind that Guggul should always be chewed well before swallowing in order to get the maximum benefits,2. Take ¼ - ½ teaspoon of Haritaki powder with one cup of warm water. Drink as a tea once or twice daily, or as directed by your healthcare practitioner. Please consult your physician before use if you are pregnant, or nursing, or on medication, or have a medical condition.Generally speaking, haritaki is considered safe for everyday use, especially when taken in small doses and blends such as triphala. Haritaki is available in various forms, including powder, leaf extract, and chyawanprash. For optimum absorption, it is advised to take Haritaki between meals on an empty stomach,3.10 - 20 ml, along with equal quantity of water, immediately after meals or as suggested by the health care provider.Draksha are good source of vitamin-C, vitamin-A, vitamin-K, carotenes, B-complex vitamins such as pyridoxine, riboflavin, and thiamine that are necessary for tissue health,4.You can take Shankhpushpi powder along with warm milk or water to help boost memory and concentration. Shankhpushpi tablets and capsules can also be used to improve brain functions. Shankhpushpi might help to manage wrinkles and prevent ageing due to its Rasayana (rejuvenating) property,5.Brahmi tea that is made by brewing Brahmi leaves helps to manage cold, chest congestion and bronchitis by clearing out the mucus from the air passages which helps ease breathing. It also reduces pain and inflammation in the throat and respiratory tracts due to its anti-inflammatory property. Taking Brahmi powder along with milk helps improve brain functions by preventing brain cell damage caused by free radicals due to its antioxidant property.It is used as a memory enhancer and brain tonic for kids due to its property to improve cognition.",
      imageUrl:
        "https://www.cdc.gov/ncbddd/birthdefects/surveillancemanual/quick-reference-handbook/Fig.-52.-Common-traits-in-trisomy-21-Down-syndrome.jpg",
    },
  ];
  return (
    <SafeAreaView style={{ marginHorizontal: 20, marginBottom: 50 }}>
      <View style={{ height: 50 }}>
        <Appbar
          title={item.department}
          color={COLORS.white}
          icon={"search1"}
          color1={COLORS.white}
          onPress={() => navigation.goBack()}
          onPressSearch={() => navigation.navigate("Search")}
        />
      </View>
      <FlatList
        data={Balaroga}
        showsVerticalScrollIndicator={false}
        keyExtractor={(item) => item.id}
        contentContainerStyle={{ columnGap: SIZES.small }}
        renderItem={({ item }) => (
          <View style={{ marginBottom: 10 }}>
            <MedicineTile
              item={item}
              onPress={() => navigation.navigate("Departmentdetails", { item })}
            />
          </View>
        )}
      />
    </SafeAreaView>
  );
};

export default Balaroga;

const styles = StyleSheet.create({});
