import { FlatList, StyleSheet, Text, View } from "react-native";
import React from "react";
import { SafeAreaView } from "react-native-safe-area-context";
import Appbar from "../../components/Reuseable/Appbar";
import { COLORS, SIZES } from "../../constants/themes";
import { useRoute } from "@react-navigation/native";
import Reusabletile from "../../components/Reuseable/Reusabletile";
import MedicineTile from "../../components/Reuseable/MedicineTile";
const brain = [
  {
    id: "1",
    department: "Vatavyadhi",
    disease: "Spinal Cord Injury",
    therapy: "Panchakarma Therapy",
    therapy_elaborate:
      "It is a purification process that removes skin toxins from the body and restores the balance of the body energies, involves five procedures, namely vamana, Virechana, Nasya, Basti and Taktamokshana.This therapy can help improve circulation reduce inflammation and promote the regeneration of damaged tissues.",
    medicine: "Ashwagandha,Shatavri,Guggulu,Bala",
    description:
      "1.Ashwagandha is an adaptogenic herb known for its ability to reduce stress, promote relaxation, and support the nervous system. It is often used in Ayurveda treatments for conditions like anxiety, depression, and cognitive disorders,2.Coined as the “Queen Of Herbs”, Shatavari has been used for centuries as a hormone balancer and a general tonic to uplift female health and libido. Being a powerful adaptogenic herb, it not only relieves one from physical and emotional stress but also manages diabetes mellitus, prevents high cholesterol and triglyceride levels, and helps in the treatment of bacterial and fungal infections, oedema, infertility, depression and cancer,3.Guggul is also known as “Pura” which means “wards off disease”. It is used as a source of commercial “Gum guggul”.Guggul can be taken in the form of powder, tablet or capsule to help reduce the production of sebum which inhibits the growth of acne-causing bacteria due to its antibacterial property.Applying a paste of Guggul mixed in warm water on the joints helps to reduce joint pain.It should be kept in mind that Guggul should always be chewed well before swallowing in order to get the maximum benefits,4.Bala is a popular herb in the Ayurvedic system of medicine, and it denotes “strength “in English. It is a robust herb used to uplift the strength of bones, muscles, joints and enhance overall stamina of the body. The plant is associated to the ancient Hindu Goddess of beauty, and grace Parvathi and famed as a beautifying herb. It goes by the scientific name Sida cordifolia, a perennial herb that grows to 30 metres height with oblong or heart-shaped leaves bearing small, solitary, axillary and white coloured florals. The roots and stems of Bala are very stout and strong. A native plant to India that grows along wastelands and roadsides.",
    use: "Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system,Shatavari has been used to attempt to treat conditions related to hormone imbalance such as polycystic ovarian syndrome ( PCOS) and infertility. Reduce symptoms of menopause. A small study showed taking an herbal mixture that included shatavari significantly reduced hot flashes,Guggul is useful in weight management as it helps to improve metabolism and reduce Ama (toxic remains in the body due to improper digestion) by increasing the digestive fire. It also helps to reduce swelling, pain and stiffness in joints in case of osteoarthritis as well as rheumatoid arthritis due to its anti-inflammatory and anti-arthritic properties. Guggul might also be helpful in managing blood cholesterol levels by lowering total cholesterol, low-density lipoprotein (LDL or bad cholesterol) and triglyceride levels,Bala is greatly valued for its shukrala traits, which enhances both the quality and quantity of sperm count. This classical herbal drug is mainly used as a Central Nervous system (CNS) depressant, analgesic, anti-inflammatory, hypotensive and hypoglycaemic agent. It works the best nerve tonic for treating numerous vata disorders, purifies blood, cures piles and boosts fetal growth and development. Furthermore, cooked leaves are valuable in curing bleeding piles. All parts of the plant are credited to possess distinct medicinal actions, mainly the root. It is valuable in losing weight as it helps in suppressing appetite and hypoglycaemic activity aids in controlling blood sugar spikes. As per the holistic system of Ayurveda, it is beneficial in pacifying all three doshas- vatta, pitta and kapha, but is most efficient is balancing vata dosha.",
    imageUrl:
      "https://d3b6u46udi9ohd.cloudfront.net/wp-content/uploads/2022/10/12074159/Spinal-Cord-Injury.jpg",
  },
  {
    id: "2",
    department: "Vatavyadhi",
    disease: "Alzheimer's Disease",
    therapy: "Panchakarma Therapy",
    therapy_elaborate:
      "It is a purification process that removes skin toxins from the body and restores the balance of the body energies, involves five procedures, namely vamana, Virechana, Nasya, Basti and Taktamokshana.This therapy can help improve circulation reduce inflammation and promote the regeneration of damaged tissues.",
    medicine:
      "Ashwagandha,Shankhapushpi,Gotu Kola,Jatamansi,Turmeric,Brahmi,Trailokya Vijaya Vati",
    description:
      "1.Ashwagandha is an adaptogenic herb known for its ability to reduce stress, promote relaxation, and support the nervous system. It is often used in Ayurveda treatments for conditions like anxiety, depression, and cognitive disorders,2.Shankhpushpi is an herb known for its calming properties and its ability to support brain function. It is commonly used in Ayurvedic treatments for conditions like insomnia, anxiety, and memory problems,shankhpushpi helps to calm down the brain and relieve stress as well as anxiety. It also improves memory by acting as a brain tonic due to its Medhya (improves intelligence) property. You can take Shankhpushpi powder along with warm milk or water to help boost memory and concentration,3.Gotu kola’s scientific name is Centella asiatica. The plant is native to tropical and subtropical parts of Asia.According to an older review of studiesTrusted Source, gotu kola contains compounds such as triterpenoid saponins. Researchers believe that these may be largely responsible for the plant’s purported health benefits,4.Jatamansi is a medicinal herb that has calming and neuroprotective properties. It is used in Ayurveda to promote relaxation, improve sleep quality, and support overall neurological well-being.5.Turmeric is a common spice that comes from the root of Curcuma longa. It contains a chemical called curcumin, which might reduce swelling.Turmeric has a warm, bitter taste and is frequently used to flavor or color curry powders, mustards, butters, and cheeses. Because curcumin and other chemicals in turmeric might decrease swelling, it is often used to treat conditions that involve pain and inflammation.6.Bacopa monnieri, also called brahmi, water hyssop, thyme-leaved gratiola, and herb of grace, is a staple plant in traditional Ayurvedic medicine.It grows in wet, tropical environments, and its ability to thrive underwater makes it popular for aquarium use.Bacopa monnieri has been used by Ayurvedic medical practitioners for centuries for a variety of purposes, including improving memory, reducing anxiety, and treating epilepsy.In fact, research shows that it may boost brain function and alleviate anxiety and stress, among other benefits.A class of powerful compounds called bacosides in Bacopa monnieri is believed to be responsible for these benefits,7.The medicine has a direct effect on motor neurons or 'VaatVaahini Naadi' and therefore is a drug providing quick relief.",
    use: "1.Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system,2.Shankhpushpi helps to calm down the brain and relieve stress as well as anxiety. It also improves memory by acting as a brain tonic due to its Medhya (improves intelligence) property. You can take Shankhpushpi powder along with warm milk or water to help boost memory and concentration,3.Gotu kola is commonly used as an herbal supplement for conditions ranging from varicose veins to Alzheimer’s disease. Some think it may lower the risk of blood clots after plane flights, but more research is needed. Experts have looked at gotu kola as a treatment for other conditions like liver disease, bladder disease, and hardening of the arteries.A few studies have found that gotu kola creams or ointments might prevent scarring and help with wound healing and psoriasis. These creams may help reduce stretch marks during pregnancy,4.The roots and the rhizomes of N. jatamansi, as mentioned in Ayurveda, have been used in various herbal formulations including dietary supplements. This important traditional drug is also used to treat epilepsy, hysteria, syncope, convulsions, and mental weakness. The decoction of the drug is also used in neurological disorders, insomnia, and disorders of cardiovascular system. It has been reported to exhibit antidepressant, anticonvulsant and antiarrhythmic activities as well as to possess antioxidant and lipid peroxidation activities.5.People commonly use turmeric for osteoarthritis. It is also used for hay fever, depression, high cholesterol, a type of liver disease, and itching, but there is no good scientific evidence to support most of these uses. There is also no good evidence to support using turmeric for COVID-19.6.It may help improve inflammation, reduce ADHD symptoms, and prevent anxiety and stress. Bacopa monnieri, also called brahmi, water hyssop, thyme-leaved gratiola, and herb of grace, is a staple plant in traditional Ayurvedic medicine.7.it has extensive pain-relieving characteristics. Trailokya Vijaya Vati is a classic Ayurvedic formula used for treating chronic pains and arthritis pains. It is even effective in relieving muscular spasms, sciatica pain, menstrual cramps and colic pain.",
    imageUrl: "https://medlineplus.gov/ency/images/ency/fullsize/23214.jpg",
  },
  {
    id: "3",
    department: "Vatavyadhi",
    disease: "Amyotrophic Lateral Sclerosis",
    therapy: "Rasayana Therapy",
    therapy_elaborate:
      "Rasayana is the medicine of nourishment. These nourish the body deeply. Internal medication  - Mamsagni Rasayana, Saha Bala along with Omni Power is effective and safe Ayurvedic supplement for treatment, other herbal supliments like Ajmodadi churna, Ashwagandharishtha, Ras rajeshwar rasa, Narsingh churna.Rasayana essentially means nutrition at all levels from macro to micro-cellular level. Rasayana therapy replenishes the vital fluids of the body; boost the ojas (vital force of life) and the immune system, thus keeping away from diseases and prevents against ill effects of advanced age.",
    medicine: "Ashwagandha,Shankhapushpi,Bala,Rasayana,Guduchi,Haritki",
    description:
      "1.Ashwagandha is an adaptogenic herb known for its ability to reduce stress, promote relaxation, and support the nervous system. It is often used in Ayurveda treatments for conditions like anxiety, depression, and cognitive disorders,2.Shankhpushpi is an herb known for its calming properties and its ability to support brain function. It is commonly used in Ayurvedic treatments for conditions like insomnia, anxiety, and memory problems,3.Bala is a popular herb in the Ayurvedic system of medicine, and it denotes “strength “in English. It is a robust herb used to uplift the strength of bones, muscles, joints and enhance overall stamina of the body. The plant is associated to the ancient Hindu Goddess of beauty, and grace Parvathi and famed as a beautifying herb. It goes by the scientific name Sida cordifolia, a perennial herb that grows to 30 metres height with oblong or heart-shaped leaves bearing small, solitary, axillary and white coloured florals. The roots and stems of Bala are very stout and strong. A native plant to India that grows along wastelands and roadsides,4.In early ayurvedic medicine, rasāyana (Pali and Sanskrit: रसायन) is the practice of techniques for lengthening lifespans and invigorating the body. It is one of the eight areas of medicine in Sanskrit literature. In Vedic alchemy, 'rasa' also means 'metal' or 'a mineral',5.Guduchi, scientifically known as Tinospora cordifolia, is a vital remedy in the Indian system of medicine. It belongs to the Menispermaceae family and has been used as a medicament since ancient times. It is also known as Giloy, Amrita or Indian bitter. It is found in dense and dry forests all over India, growing over small trees and bushes at high altitudes. The stem, roots and leaves of Guduchi all have medicinal properties,6.Haritaki is considered an important herb in Ayurveda and Siddha medicine,they’re then powdered and made into Ayurvedic remedies. The fruit’s potency is based on where the fruit was collected, its color, and its shape.Haritaki is also known as:harad,haradey,kaddukki (in South Asia),kayakalpa,In Tamil, it’s referred to as “kayakalpa,” a rejuvenator of the body that balances all dosha, or humors. It’s often referred to as a “life-giving” herb.Haritaki is prized in Ayurveda for its versatile health applications.",
    use: "1.Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system,2.Shankhpushpi helps to calm down the brain and relieve stress as well as anxiety. It also improves memory by acting as a brain tonic due to its Medhya (improves intelligence) property. You can take Shankhpushpi powder along with warm milk or water to help boost memory and concentration,3.Bala is greatly valued for its shukrala traits, which enhances both the quality and quantity of sperm count. This classical herbal drug is mainly used as a Central Nervous system (CNS) depressant, analgesic, anti-inflammatory, hypotensive and hypoglycaemic agent. It works the best nerve tonic for treating numerous vata disorders, purifies blood, cures piles and boosts fetal growth and development. Furthermore, cooked leaves are valuable in curing bleeding piles. All parts of the plant are credited to possess distinct medicinal actions, mainly the root. It is valuable in losing weight as it helps in suppressing appetite and hypoglycaemic activity aids in controlling blood sugar spikes. As per the holistic system of Ayurveda, it is beneficial in pacifying all three doshas- vatta, pitta and kapha, but is most efficient is balancing vata dosha,4.Helps improve body mass, muscle bulk and strength of bones.Promotes stamina and vitality.Supports fertility and proper functioning of reproductive system.Promotes digestive and respiratory health.Maintains Urogenital health in both male and female.Offers postpartum care,5.Guduchi has been shown to reduce blood sugar levels, especially during fasting levels. The anti-diabetic effect is attributed to the various phytochemicals present in it. It regulates the blood sugar level by reducing oxidative stress, enhancing insulin release, and reducing the production and breakdown of glucose in the body. Guduchi is especially useful for type 2 diabetes,6.Haritaki is a magical remedy that holds high significance in treating countless health problems including indigestion, gastritis, lung disease, obesity, impotence, cough, cold, asthma, vision defects, urinary tract infections and hair, and skin problems.",
    imageUrl:
      "https://natureswaymedicine.com/wp-content/uploads/2019/10/als.jpg",
  },
  {
    id: "4",
    department: "Vatavyadhi",
    disease: "Ataxia",
    therapy: "Panchkarma therapy",
    therapy_elaborate:
      "It is a purification process that removes skin toxins from the body and restores the balance of the body energies, involves five procedures, namely vamana, Virechana, Nasya, Basti and Taktamokshana.This therapy can help improve circulation reduce inflammation and promote the regeneration of damaged tissues.",
    medicine:
      "Brahadvatacintamanirasa,Vasantamalti rasa,Dasamula Kwath,Amrta Churna,Muktasukti pisti,Yograj guggulu",
    description:
      "1.Brihat Vatchintamani Ras is an Ayurvedic medicine in tablet form. It is used in the treatment of Vata Dosha imbalance diseases such as paralysis, hemiplegia, facial palsy, tremors etc.  This medicine should only be taken under strict medical supervision,2.Virgo Suvarna Vasant Malati Rasa Tablet is an ayurvedic formulation made with natural ingredients. It has antimicrobial properties that can prove beneficial in dealing with fever. It can support the body in anaemia, liver enlargement and various other conditions and can boost the immunity of the body,3.Dashmool is a combination of 10 effective herbs mentioned in Ayurveda for their Anti-inflammatory properties. Dashmool kwath is beneficial for reducing / balancing Vata dosha especially in the Bones, Joints, muscles and nerves,4.Amrita Churna Amla is a rich source of vitamin C that boosts immunity. It helps rejuvenate cells and maintain healthy skin, body and hair. Amla is also known to be beneficial in managing blood sugar levels,5.Muktas or pearls have been known for their curative properties since time immemorial. Imbued with amino acids, calcium, and trace minerals, pearls have many purported benefits for skin and health,6.It contains several aromatic, medicinal and dietary herbs as active ingredients. It is used to cure joint disorders.",
    use: "1.Brihat vatchintamani ras uses- it is used in the treatment of paralysis, facial palsy, psychosis, epilepsy, etc. It is an excellent rejuvenative and anti-aging ayurvedic medicine. It is also effective in pitta disorders such as migraine, vertigo, digestive disorders,2.Vasant Malati Rasa Tablet is an ayurvedic formulation made with natural ingredients. It has antimicrobial properties that can prove beneficial in dealing with fever,3.Beneficial for reducing / balancing Vata dosha especially in the Bones, Joints, muscles and Nerves. This makes it extremely useful in various painful, inflammatory and degenerative problems of joint like osteoarthritis, rheumatoid arthritis,4.Helps improve conditions resulting from stress, fatigue, lack of sleep, and energy loss. It helps reduce cortisol levels and is helpful for those suffering from chronic stress and anxiety.5.It can be used for overcoming symptoms of cough, cold, asthma, etc. It may neutralise the excess acid in the stomach and provides immediate relief from acidity and heartburn,6.It is used to cure joint disorders. Useful in muscles, bone and joint pains, fibromyalgia, joint stiffness, constipation, bloating, indigestion, irritable bowel syndrome, epilepsy, sciatic nerve pain, dysmenorrhea, premenstrual syndrome..",
    imageUrl:
      "https://www.hopkinsmedicine.org/health/conditions-and-diseases/-/media/ksw-images/amuscsk20140305v0002.ashx",
  },
  {
    id: "5",
    department: "Vatavyadhi",
    disease: "Bell's Palsy",
    therapy: "Sadyovamana Therapy",
    therapy_elaborate:
      "Initially, the patient is given Purvakarma, or preparatory therapy, for three to seven days. Both internal and external oleation are done with medicated ghee or oil and the patient is made to sweat intensely. This directs the excess Kapha to build up in the stomach.",
    medicine:
      "Ashwagandha,Brahmamusli,Ekangaveera rasa,Brihitvata Chintamani,Gulika,Balarishta",
    description:
      "1.Ashwagandha is an adaptogenic herb known for its ability to reduce stress, promote relaxation, and support the nervous system. It is often used in Ayurveda treatments for conditions like anxiety, depression, and cognitive disorders,2.Musli might help improve sexual performance by increasing libido. It also helps enhance testosterone levels. A study states that Safed musli can also be used to prevent premature ejaculation as well as to improve the sperm count. Another study states that it enhances strength and stamina,3. 125 – 375 mg once or twice a day, after or before meals as directed by Ayurvedic doctor. Generally in Ayurvedic medicine it's administered with fresh ginger juice extract and water. In practice, Ekangveer ras is also administered along with Rasnadi Kashayam,4.Baidyanath Vatchintamani Ras is the classical Ayurvedic medicine specially formulated for the management of chronic vat diseases. Highly efficacious formula prepared with combinations of six potent bhasma that provides relief from debility related to chronic vat diseases and relieves other problems related to it,5.Gulika  is time tested classical formulation made with safe herbs, which is authentic ayurvedic product from the house of AVP. Ingredients used in Gulika is Sariba- which is effective in the management of fever,6. Balarishta Syrup contains Bala, Satavari and Rasna to assist in the treatment of pains in the joints. Karshya is also included to treat cases of malnourishment while daurbalya is added to improve how well the body can respond to different treatments, thus allowing the body to become stronger when it is used properly.",
    use: "1.Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system,2.Musli is considered safe when taken in the proper prescribed dosage, an excessive amount without a doctor's consultation can cause weight gain, difficulty in digestion, depreciated digestive functions, loss of appetite and constipation,3.It is used in the treatment of paralysis, sciatica, facial palsy. This medicine contains heavy metal ingredient, hence should only be taken under strict medical supervision,4.it is used in the treatment of paralysis, facial palsy, psychosis, epilepsy, etc. It is an excellent rejuvenative and anti-aging ayurvedic medicine. It is also effective in pitta disorders such as migraine, vertigo, digestive disorders,5.Gulikas are tablets dispensed to patients for their ease of consumption. They are made by rolling medicinal pastes into balls and drying them under the sun,gulika recommended for the treatment of diabetics, spleen disorders, urinary issues and anaemia (iron deficiency),6.Balarishta is used as a pain-relieving tonic. It can treat problems like arthritis, muscle cramps, physical weakness and joint aches. The tonic also improves digestive health and helps the body stay stronger and balanced.",
    imageUrl:
      "https://images.ctfassets.net/u4vv676b8z52/537tC7znCwnRX3l3c9xnnz/5d9a26a2cf3b676af2ad45f66c67abfb/bells-palsy-678x446.gif?fm=jpg&q=80",
  },
  {
    id: "6",
    department: "Vatavyadhi",
    disease: "Brain Tumors",
    therapy: "Shirodhara",
    therapy_elaborate:
      "Shirodhara is one of the effective procedures for curing brain tumor conditions. The Shirodhara Treatment refers to the process of pouring warm oil on the head with a continuous motion that will help you eradicate the pain and symptoms to a great extent! The Shirodhara treatment helps to reduce symptoms of stress and anxiety, as well as promote relaxation.",
    medicine: "Ashwagandha,Curcumin,Guggul,Wheatgrass,Indian White Cedar",
    description:
      "1.Ashwagandha herb has fascinating healing properties. This Herb plays a major role in restoring strength and immunity in your body. It is endowed with anti-inflammatory properties and is a beneficial anti-oxidant,2.Curcumin has been known to disintegrate malignant cells from your body. It not only is a great anti-oxidant but also improves immunity,3.Guggul has highly potent rejuvenating properties. It revitalizes cells and therefore, rejuvenates them. It enhances oxidation potentials of the body and speeds up recovery from brain tumors,4.Wheatgrass has components that increase the oxygen capacity of the blood. The antioxidants present in the wheatgrass push up the absorption power of the cells in the body. Since the brain needs an abundant supply of oxygen and consumes 25% of the body’s oxygen, wheatgrass works wonders on brain tumors,5.Also called Bili Devdari, the tree is today better known in India as a source of timber. However, it has long been used in Ayurveda for its therapeutic value.",
    use: "1.It supplements the essential nutrients, which improve the functions of the brain and minimize the adverse effects caused by harmful radiation,2.The anti-oxidants present in the herb reduce the free radicals from the body, thereby improving health and immunity. It has gained popularity as a cure for brain tumors as well,3.Guggul is praised for its anti-inflammatory properties. Preliminary research suggests it may help treat certain anti-inflammatory conditions, such as acne, eczema, psoriasis, and arthritis. It has also been used to promote weight loss, treat hypothyroidism, and manage cholesterol and blood sugar levels,4.The organs like the liver and intestines which become sluggish also get strength from the juices of the plant. Just as wheat gives us tremendous strength and energy to fight against diseases, wheatgrass is extremely beneficial in fighting tumors and many other diseases,5.Ayurvedic physicians often use it as an ingredient in herbal remedies to treat rheumatism, with some varieties of the tree also being used to produce Ayurvedic medications for heart disease and tumors.",
    imageUrl:
      "https://my.clevelandclinic.org/-/scassets/images/org/health/articles/6149-brain-tumor",
  },
  {
    id: "7",
    department: "Vatavyadhi",
    disease: "Epilepsy & Seizure",
    therapy: "Panchakarma & Nasya Therapy",
    therapy_elaborate:
      "Nasya refers to nasal administration of therapeutic oil. Nasya is a part of the Panchakarma treatment where the central nervous system is cleansed through administering beneficial oils through the nostrils. The oil is customised by the practitioner based on the condition to be treated.",
    medicine:
      "emesis(vatika apasmara) & enema(pattika apasmara),ghritas(purified butter),mahapanchagavya ghrta,anjanas,ashvangandhayarishta,bail tail",
    description:
      "1.Apasmara (epilepsy) is defined by Acharya Charaka as Apagama (deterioration) of Smriti (retention) associated with Bibhatsa Chesta (seizers) due to derangement of Dhi and Sattva. The vitiate Dosha related to the condition are Vata and Rajo Dosha,2.It is the preeminent element of Indian food for hundreds of years. Indian cow Ghrita is used in the daily routine diet. Ghrita is not only used as an excellent base for preparing Ayurveda medicines, but it is also used as a traditional adjuvant/ vehicle in Ayurveda,3.Ayurveda is the only method of medicine where nasalmethod is used for treatments. ‘Nasika shiraso dvaram’ means nose (nostrils) are the door to the head. All brain related diseases and ailments can be treated with this maha Panchgavya ghritam. Charak Samhita details the method of preparing this nasya,4.It contains Ashwagandha as the main ingredient which shows positive results in managing stress or anxiety due to its anti-stress properties[1]. The presence of Ashwagandha may also help in managing epilepsy due to its antiepileptic property. Some evidence suggests that Ashwagandharishta may also help in improving the digestive system,5.The water soluble as well as fat soluble active principles can be transformed into Taila media and this addition of properties of material made the Taila potent and effective.",
    use: "1. The main features of Apasmara are impairment in memory or awareness,in internal medications following Ayurvedic preparations can be given: Pancha gavya ghrita. Maha pancha gavya ghrita. Brahmi ghrita,2.Rich in antioxidants, fatty acids and a natural emollient, ghee helps you with maintaining healthy skin by locking in moisture, improving skin repair, treating cracks and softening the skin. This is also one of the popular traditional benefits of ghee,3.Maha Panchagavya Ghrita is an ayurvedic formulation. This formulation is known to contain mixture of fruitful herbs. Ghee is used as a base in this formulation. This is very helpful to treat problems related with liver, inflammation and psychiatric etc,4.In Ayurvedic therapy, Ashwagandharishta is used in psychiatric disorders like epilepsy, depression, anxiety, schizophrenia, sluggishness, dullness, and other memory-related disorders. The roots of ashwagandha are very efficient in promoting memory, attention and concentration,5.Formulations prepared from the Taila enhance life, complexion, strength and anabolism of body.",
    imageUrl: "https://nurseslabs.com/wp-content/uploads/2018/08/Seizures.jpg",
  },
  {
    id: "8",
    department: "Vatavyadhi",
    disease: "Muscular Dystrophy",
    therapy: "Panchakarma Therapy",
    therapy_elaborate:
      "Panchakarma, the primary healing and purifying system of Ayurveda that uses five procedures, can also help to relieve constipation, backaches, and sciatica, is also very helpful for dystrophy patients as it can help reduce a lot of the muscular pain that comes with the illness.",
    medicine:
      "Yograj Guggulu,Dashmoola Kwath,Shatavri,Shankha Bhasma,Narsinha Churna,Ekangveera rasa,Ashwagandha Churna",
    description:
      "1.Yogaraj Guggulu contains several aromatic, medicinal and dietary herbs as active ingredients. It is used to cure joint disorders. Useful in muscles, bone and joint pains, fibromyalgia, joint stiffness, constipation, bloating, indigestion, irritable bowel syndrome, epilepsy, sciatic nerve pain, dysmenorrhea, premenstrual syndrome,2.Dashmool is a combination of 10 effective herbs mentioned in Ayurveda for their Anti-inflammatory properties. Dashmool kwath is beneficial for reducing / balancing Vata dosha especially in the Bones, Joints, muscles and Nerves,3.Shatavari is an Ayurvedic rasayana herb which is also known as the female-friendly herb. It is helpful in menstrual disorders and acts as a uterine tonic. It enhances breast development and increases breast milk production by regulating hormonal balance,4.Shankh Bhasma (Conch or Sea Shell) is an ayurvedic medicine used to manage conditions like acid reflux, also called gastroesophageal reflux disease (GERD)[1]. It possesses antacid properties which offer relief from symptoms like heartburn and chest pain. Shankha (Conch) is mentioned in Rasashastra as a mineral under Sudha Varga (Calcium group) category,5.Narasimha churna is a mixture of 11 dry herbal powder with sugar having wide application along with adjuvant in different health related problems like respiratory disorders, age related degenerative problems, skin diseases,6.The compostion of Basic Ayurveda Ekangveer Ras are Ras Sindoor, Sudha Gandhak, Kant Loh Bhasma, Nag Bhasma, Tamra Bhasma, Abhrak Bhasma, Loh Bhasma, Triphala Ras, Trikuta Ras, Chitrak Ras, Amla, Bhringraj Ras, Ginger, and other prominent herbs,7.Ashwagandha churna aids in alleviating stress and enhancing overall health and immunity. This herbal powder is derived from the beneficial properties of ashwagandha (Withania somnifera), also referred to as Indian ginseng. It facilitates the recovery from anxiety and depression while restoring strength.",
    use: "1.It is used to cure joint disorders. Useful in muscles, bone and joint pains, fibromyalgia, joint stiffness, constipation, bloating, indigestion, irritable bowel syndrome, epilepsy, sciatic nerve pain, dysmenorrhea, premenstrual syndrome,2.It is beneficial for reducing / balancing Vata dosha especially in the Bones, Joints, muscles and Nerves. This makes it extremely useful in various painful, inflammatory and degenerative problems of joint like osteoarthritis, rheumatoid arthritis etc,3.Shatavari increases the production of prolactin, a hormone that is important for breastfeeding. Hormone balancing. Shatavari has been used to attempt to treat conditions related to hormone imbalance such as polycystic ovarian syndrome (PCOS) and infertility. Reduce symptoms of menopause,4.It is widely used as a traditional medicine for treating various types of digestive disorders like gastritis, abdominal pain and malabsorption syndrome. It is derived from the powder of a conch shell through the process of calcination,5.This is an ayurvedic medicine that is used in the ayurvedic treatment of a wide variety of diseases including respiratory conditions, male infertility, and so on. Also, this powder helps cure liver problems, cure anemia, semen problem, cough, skin problems as well as many other clinical conditions,6.It is used in the treatment of paralysis, sciatica, facial palsy. This medicine contains heavy metal ingredient, hence should only be taken under strict medical supervision. It is used in the treatment of hemiplegic, cervical spondylosis, brachial neuralgia and such other neuro-muscular conditions,7.With its antioxidant properties, Divya Ashwagandha churna accelerates the healing process and rejuvenates the body. Divya pharmacy presents ashwagandha churna as a comprehensive remedy for both the body and mind.",
    imageUrl:
      "https://healthjade.net/wp-content/uploads/2020/05/Duchenne-muscular-dystrophy.jpg",
  },
  {
    id: "9",
    department: "Vatavyadhi",
    disease: "Parkinson's Disease",
    therapy:
      "Panchakarma Detox Cleansing, Abhyanga (massage),Shirodhara (pouring of oil over the forehead)",
    therapy_elaborate:
      "1.A panchakarma cleanse can effectively eliminate toxins. correct internal imbalances. and purify the body on a deep level: thereby restoring the natural balance in the body and mind. Panchakarma encompasses five procedures – Vamana,2.Abhyanga is a massage that’s done with warm oil. The oil is applied on the entire body, from the scalp to the soles of your feet.It’s the most popular massage in Ayurveda, a traditional system of medicine from India. Ayurveda focuses on maintaining health through natural practices like massage and what you eat,3.Shirodhara comes from the two Sanskrit words “shiro” (head) and “dhara” (flow). It's an Ayurvedic healing technique that involves having someone pour liquid — usually oil, milk, buttermilk, or water — onto your forehead. It's often combined with a body, scalp, or head massage,4.Vasti (Enema) treatments are extremely effective in removing Vata-based toxins from the system. There are two Vasti treatments - Niruha Vasti and Anuvasana Vasti - that are administered according to the patient's body condition and treatment requirements. Anuvasana Vasti is Enema Therapy using medicated oils.",
    medicine: "Ashwagandha,Bala,Atmagupta,Virechanam,Vasti Chikitsa",
    description:
      "1.Ashwagandha is an important herb in Ayurvedic medicine. This is one of the world’s oldest medical systems and one of India’s healthcare systems.In Ayurvedic medicine, ashwagandha is considered a Rasayana. This means that it helps maintain youth, both mentally and physically,2.Bala is a popular herb in the Ayurvedic system of medicine, and it denotes “strength “in English. It is a robust herb used to uplift the strength of bones, muscles, joints and enhance overall stamina of the body,3.This beautiful plant with its velvety seed pods is also a natural source of levodopa (L-dopa), which is an essential precursor to the neurotransmitter dopamine. Thanks to this attribute, it’s revered for its ability to uplift one’s mood and enhance a sense of emotional well-being,4.Virechana is one of the Panchakarma therapies wherein purgation is induced by drugs and it specifically aims at the elimination of excessive Pitta Dosha from the body. Normally, after Virechanakarma, patient does not complain of having any untoward like those present after diarrhea due to dehydration,5.Vasti karma is one of the main therapies used in Panchakarma treatments, that which mainly focuses on treating the disorders which are caused from the imbalance of Vata Dosha (One of the main basic element of our body). Because, Vayu is the motive force behind all physiological and pathological states of the body.",
    use: "1.Ashwagandha is traditionally used as an adaptogen, it is used for many conditions related to stress. Adaptogens are believed to help the body resist physical and mental stress. Some of the conditions it is used for include insomnia, aging, anxiety and many others, but there is no good scientific evidence to support most of these uses,2.Bala helps to control the symptoms of respiratory system problems like cough and cold. This is because it helps to balance Kapha and expel out the mucus from the lungs. It also helps to increase immunity due to its Rasayana (rejuvenating) property,3.It helps improve sperm count and its ability to swim (motility). It improves semen quality by preventing cellular oxidative stress, supporting sperm production, and maintaining healthy semen balance,4.Virechana is a cleansing procedure in Ayurveda, specifically a part of Panchakarma, which involves the removal of toxins from the body through induced bouts of diarrhea. This process is not a simple case of diarrhea but rather a carefully prepared and executed procedure that takes about 12 days to complete,5.Vasti is considered as a complete treatment because it incorporates all the treatment aspects of Ayurveda in to it.",
    imageUrl:
      "https://stanfordmedicine25.stanford.edu/the25/parkinsondisease/_jcr_content/main/panel_builder_0/panel_0/panel_builder_0/panel_0/panel_builder/panel_0/image.img.full.high.png/1.png",
  },
  {
    id: "10",
    department: "Vatavyadhi",
    disease: "Migraine",
    therapy: "Sirolepa & Shirodhara",
    therapy_elaborate:
      "Shirodhara is a classic Ayurvedic therapy or the practice of slowly and steadily dripping medicated oil or medicated decoctions on the forehead. The therapy induces a relaxed state of awareness that results in a psychosomatic balance.",
    medicine:
      "Jatamansi,Bala,Amalaki,Ginger,haritiki,Yastimadhu,Shirashooladi Vajra Rasa",
    description:
      "1.Jatamansi, also known as “tapaswani” in Ayurveda, is a perennial, dwarf, hairy, herbaceous and endangered plant species. It acts as a brain tonic and helps to improve memory and brain functions by preventing cell damage due to its antioxidant property. It also calms down the brain and manages anxiety as well as insomnia,2.Bala is a popular herb in the Ayurvedic system of medicine, and it denotes “strength “in English. It is a robust herb used to uplift the strength of bones, muscles, joints and enhance overall stamina of the body,3.Amalaki powder, or amla, is a supplement derived from the Indian gooseberry. It is a rich source of vitamins and bioactive compounds, and research suggests it may help support the immune system, improve digestion, and even protect against cancer,4.People have used ginger for in cooking and medicine since antiquity. It may help to relieve nausea and stomach pain. Ginger may also have other health benefits like antioxidant and antimicrobial properties,5.Yashtimadhu uses stems from its properties of being adaptogenic, antacid, cooling, nootropic, immunity boosting, anti-inflammatory, anti-oxidant, anti-obesogenic, analgesic, an antidepressant making it the ultimate multipurpose herb.6.Shir Shuladi Vajra Ras is an Ayurvedic medicine in tablet form, used in the treatment of headache. This medicine contains should only be taken under strict medical supervision. This medicine is most commonly used in north Indian Ayurvedic practice.",
    use: "1.Jatamansi, as mentioned in Ayurveda, have been used in various herbal formulations including dietary supplements. This important traditional drug is also used to treat epilepsy, hysteria, syncope, convulsions, and mental weakness2.Bala helps to control the symptoms of respiratory system problems like cough and cold. This is because it helps to balance Kapha and expel out the mucus from the lungs. It also helps to increase immunity due to its Rasayana (rejuvenating) property,3.Amlaki is loaded with powerful antioxidants and has detoxifying properties. Vitamin C in Amlaki is helpful in improving the body's immunity levels. The anti-aging and rejuvenating power of Amalaki contributes to healthy skin. Amalaki improves overall health by eliminating body stress and weakness,4.People typically use fresh or dried ginger in cooking or herbal tea, and some take ginger supplements for their possible health benefits.Ginger may help relieveTrusted Source nausea and vomiting and aid digestionTrusted Source. Antioxidants and other nutrients in ginger root may help prevent or treat arthritis, inflammation, and various types of infection. Ginger may also reduce the risk of diabetes, cancer, and other health problems.5.Yashtimadhu has been conventionally used by Ayurveda in the treatment of respiratory and digestive disorders. It is considered to be a 'Rasayana'. Mulethi uses specifically include treatment of chronic acidity, ulcers and chronic bronchial conditions,6.Indicated in Headache due to Tension, Vascular and Positional Headache. It is useful in treatment of Shiroroga (Disease of head). It gives relief in chronic headache, migraine, tension headache, and other type of headache.",
    imageUrl:
      "https://www.birlahospital.com/wp-content/uploads/2022/03/Why-are-migraines-caused.jpg",
  },
];
const Brain = ({ navigation }) => {
  const route = useRoute();
  const { item } = route.params;
  return (
    <SafeAreaView style={{ marginHorizontal: 20, marginBottom: 50 }}>
      <View style={{ height: 50 }}>
        <Appbar
          title={item.department}
          color={COLORS.white}
          icon={"search1"}
          color1={COLORS.white}
          onPress={() => navigation.goBack()}
          onPressSearch={() => navigation.navigate("Search")}
        />
      </View>
      <FlatList
        data={brain}
        showsVerticalScrollIndicator={false}
        keyExtractor={(item) => item.id}
        contentContainerStyle={{ columnGap: SIZES.small }}
        renderItem={({ item }) => (
          <View style={{ marginBottom: 10 }}>
            <MedicineTile
              item={item}
              onPress={() => navigation.navigate("Departmentdetails", { item })}
            />
          </View>
        )}
      />
    </SafeAreaView>
  );
};

export default Brain;

const styles = StyleSheet.create({});
