import { FlatList, StyleSheet, Text, View } from "react-native";
import React from "react";
import { SafeAreaView } from "react-native-safe-area-context";
import Appbar from "../../components/Reuseable/Appbar";
import { useRoute } from "@react-navigation/native";
import { COLORS, SIZES } from "../../constants/themes";
import MedicineTile from "../../components/Reuseable/MedicineTile";

const Ent = ({ navigation }) => {
  const route = useRoute();
  const { item } = route.params;
  const Ent = [
    {
      id: "1",
      department: "Shalankya Tantra(ENT)",
      disease: "karnasrava ",
      therapy: "Karna Prakshalana",
      therapy_elaborate:
        "Ear should be washed and drained so as to cause its thorough cleansing.This shall be done by using herbal decoctions which can heal the infection and also check discharges.",
      medicine:
        "Aushadha churna,Panchvalkala Kashaya,Tidukadi churna,Priyangvadi Taila,Dushta Varna & Nadi Vrana Chikitsa",
      description:
        "1.The afflicted ear should be filled/dusted with powder of medical herbs,2.Decoction of Panchavalkala should be added with juice of fruit pulp(Feronia limonia) and honey and filled in the afflicted ears,3.Powder of Diospyros malabarica(tinduka),Terminilia chebula,Symplocos racemosa, Rubia cordifolia and Emblica officinalis should be mixed in the juice of fruit pulp and filled in the affected areas of ears,4.Oil processed and prepared with decoction of Callicarpa macrophylla, liquorice, Cissampelos Pereira, Desmodium gangeticum,Rubia cordifolia,lac and fruit pulp should be as ear drops/ear filling,5.Master Vagbhata has emphasised on treating ear discharges on the lines of treatment of contaminated wounds and sinus ulcers.",
      use: "1.It possesses laxative qualities that stimulate peristaltic movements, ensuring a painless bowel movement. It aids in improving digestion,helpful in hearing aids,enhancing appetite, and alleviating gas formation and discomfort,2.Panchavalkal is the combination of five herbs having properties like Shodhana (cleaning) and Ropana (healing) of wounds. Individual drugs and in combination have Kashaya rasa (astringent) dominant and useful in the management of Vrana (wounds) as well as Shotha (inflammations).3.It is useful in diseases caused by bile.Migraine is extremely beneficial for migraine headaches.Fever caused due to heat stroke in summer is beneficial for cold.Helpful in removing heaviness of the head.4.Priyangvadi-Taila is indicated for Vidradhi Vrana in Vidradhi-Adhyaya (Chikitsasthana) of Sushruta Samhita. This Taila yoga contains the drugs possessing Shodhan and Ropana properties, thus considered as a good curative measure for local treatment of Dushta Vrana.5.Vrana (Wound/ Ulcer) and healing are the two sides of the surgical coin, on which an expert surgeon has to play his role very sincerely. Since the origin of medicine, there has been a concern about the healing of wounds in general. It is considered to be an essential to life, as it has always been known that infections acquired through wounds might lead to serious complications.",
      imageUrl:
        "https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2021/06/22/16/33/ear-infection-8col-153200-001-0.jpg",
    },
    {
      id: "2",
      department: "Shalankya Tantra(ENT)",
      disease: "Dysphagia-Difficulty Swallowing",
      therapy: "Gargle therapy",
      therapy_elaborate:
        "salt water – Dissolve half a tsp of rock salt in warm water and gargle. This will help reduce the swelling in your throat. It will also help loosen the mucus and flush it out. Henna leaves – These may also be used as a decoction that you can gargle. Methi seeds – Boil them in water, strain, and gargle.Turmeric water – Turmeric is an excellent antioxidant. Mix ½ tsp of turmeric powder in hot water along with ½ tsp of salt. Gargle every 2 hours. Basil water – You can boil water with tulsi leaves (basil). You can either drink this mixture after straining it or gargle with it.Tankana Bhasma – This is made from borax. You can dissolve some Tankana Bhasma powder in water, and gargle once or twice a day.",
      medicine:
        "Liquorice(Mulethi),Amla,Haritiki,Bahera,Pippali,Jeera,Ginger,Horse Gram",
      description:
        "1.Licorice is an Ayurvedic remedy for Dysphagia. It has soothing and anti-inflammatory properties. Throat discomfort, indigestion, gastric ulcers, and heartburn can all be relieved with this herb,2.Amla is an effective remedy to treat Dysphagia due to its healthy properties. Amla is an antioxidant with a high concentration of Vitamin C, making it a rejuvenator and a cooling agent with calming properties. Because it is sour, it aids in the stimulation of digestive juices,3.Haritaki is an effective herb with laxative, digestive tonic, expectorant, anti-dysentery, carminative, astringent properties,4.Bahera is an herb used to treat Tridoshas. It can excrete excessive mucus(Kapha) from the intestines and benefits in the right amount of excretion of juices,5.This herb helps to strengthen the complete digestive system. It stimulates the liver, pancreas, and intestines to secrete digestive juices,6.Jeera is the most common herbal plant used in reducing abdominal pain due to gas and flatulence. The decoction of jeera helps relieve abdominal gas problems and heartburn,7.Ginger helps reduce all the symptoms of Dysphagia. So, consume ¼ spoon honey with ¼ spoon of ginger juice every day to aid the swallowing process and eliminate other related symptoms,8.Horse Gram relieves burning sensations in the abdomen and chest and can help with sore throats. So, take some horse gram powder and keep it in your mouth. Slowly suck it for a couple of minutes and finally let it in.",
      use: "1.This herb has many uses like it can give relief from the throat soreness, indigestion, gastric ulcers and heartburn as well. Even good to use in dry cough, oral inflammation, asthma and bronchitis,2.The fruit is used either alone or in combination with other plants to treat many ailments such as common cold and fever; as a diuretic, laxative, liver tonic, refrigerant, stomachic, restorative, alterative, antipyretic, anti-inflammatory, hair tonic; to prevent peptic ulcer and dyspepsia, and as a digestive,3.Its warm potency helps to relieve flatulence and the formation of gastric problems. It can pacify all three doshas. It also provides relief in heartburn,4.It can excrete excessive ‘kapha' from intestines and benefits in the right excretion of juices. Supports the digestion process and maintain the pH of the stomach,It also supports the digestion process,5.It is capable to strengthen the complete digestive system. It stimulates liver, pancreas and intestines to secrete digestive juices,6.It is so common among people for its use in relieving abdominal pain due to gas and flatulence. The decoction of Cumin, Fennel, and Coriander is useful in relieving abdominal gas problem and heartburn,7.Eating ginger can cut down on fermentation, constipation and other causes of bloating and intestinal gas. Wear and tear on cells. Ginger contains antioxidants. These molecules help manage free radicals, which are compounds that can damage cells when their numbers grow too high,8.Horsegram or Kuleeth is an energy-filled superfood loaded with antioxidants, protein, iron, calcium and zinc. In Konkan, Horsegram Flour is used to make the Maharashtrian specialty, Pithla.",
      imageUrl:
        "https://www.triorehab.com/wp-content/uploads/2021/06/Dysphagia.jpg",
    },
    {
      id: "3",
      department: "Shalankya Tantra(ENT)",
      disease: "Ear Infection(Otisis Media)",
      therapy: "Shirovirechana and dhawana/ Prakshalana",
      therapy_elaborate:
        "Toileting of ear where the removal of ear wax, discharge, and debris is carried out.",
      medicine:
        "Laksmi vilasa-rasa,Turmeric,Jatamansi,Ashwagandha,Tea tree oil, Ginger,Tulsi(Holy basil)",
      description:
        "1.This ayurvedic formulation treats inflammation in the ear. Mix it with honey and consume it,Divya Laxmivilas Ras is a traditional Ayurvedic remedy that effectively treats cough, cold, and rhinitis. It provides relief to the throat and sinuses, while also helping to expel accumulated mucus from the chest. Additionally, it alleviates body aches and reduces fever. This formulation strengthens the immune system and prevents future infections,2.Turmeric is a deep, golden-orange spice known for adding color, flavor and nutrition to foods. A relative of ginger, turmeric comes from the rhizome (root) of a native Asian plant and has been used in cooking for hundreds of years,Brown explains that the active ingredient in turmeric is a natural compound (polyphenol) called curcumin, which has both antioxidant and anti-inflammatory properties.3.Jatamansi, also known as “tapaswani” in Ayurveda, is a perennial, dwarf, hairy, herbaceous and endangered plant species. It acts as a brain tonic and helps to improve memory and brain functions by preventing cell damage due to its antioxidant property. It also calms down the brain and manages anxiety as well as insomnia,4.ashwagandha is traditionally used as an adaptogen, it is used for many conditions related to stress. Adaptogens are believed to help the body resist physical and mental stress. Some of the conditions it is used for include insomnia, aging, anxiety and many others, but there is no good scientific evidence to support most of these uses. There is also no good evidence to support using ashwagandha for COVID-19,5.The tea tree oil effectively balances all the Tridoshas i.e. Vata, Pitta and Kapha Doshas and holds high significance in soothing the body and uplifting the overall health of an individual,6.Ginger has Bhedan (purgative), Deepan (appetizer), and Guru(heavy) properties which promote healthy digestion. Ginger also helps to reduce the symptoms of cough, cold, and body ache due to its Vata-Kapha balancing nature. Consuming ginger before taking meals can help stimulate the taste buds of the tongue and provide relief in sore throat. Ginger helps improve digestion by increasing the absorption of food which leads to better metabolism. A good digestive system can aid in weight management. Due to this, the regular intake of Ginger water might help reduce body weight,7.Tulsi is called the queen of all herbs, it is used widely in Ayurvedic and naturopathic medicines which helps in the healing.",
      use: "1.It is primarily indicated for the treatment of phlegm and respiratory-related disorders. It can help with cough, chest congestion, joint pain, detoxification and healthy skin. Key Benefits: Laxmivilas Ras Tablet is commonly used in Ayurveda to support respiratory health,2.Today, turmeric is promoted as a dietary supplement for a variety of conditions, including arthritis, digestive disorders, respiratory infections, allergies, liver disease, depression, and many others. Turmeric is a common spice and a major ingredient in curry powder,3.Applying Jatamansi oil on the skin helps manage skin infections and prevents aging due to its antifungal and antioxidant activities. Jatamansi is also good for hair growth as it helps to increase the follicular size and elongate the growth phase of hair. Applying Jatamansi oil helps to promote hair growth. Jatamansi root paste can also be applied on hair to improve hair strength and growth,4.By supporting immune function, ashwagandha may help teenagers stay healthy. Physical Performance : Some studies suggest that ashwagandha may improve physical performance and increase strength. This could be beneficial for teenagers who are involved in sports or other physical activities,5.Tea tree oil, also known as melaleuca oil, is an essential oil that comes from steaming the leaves of the Australian tea tree. When used topically, tea tree oil is believed to be antibacterial. Tea tree oil is commonly used to treat acne, athlete's foot, lice, nail fungus and insect bites,5.It thus reduces vata and kapha and increases pitta if taken in larger amount. Dried ginger naturally has a greater dryness, but also greater bitterness than fresh, ie it heats up the body more significantly, and is therefore more suitable for the constitution of kapha, when it alleviates its cold and moist nature,7.Tulsi is used to treat insect bites. Tulsi is also used to treat heart disease and fever. Tulsi is also used to treat respiratory problems. Tulsi is used to cure fever, common cold and sore throat, headaches and kidney stones.",
      imageUrl:
        "https://my.clevelandclinic.org/-/scassets/images/org/health/articles/8613-ear-infection",
    },
    {
      id: "4",
      department: "Shalankya Tantra(ENT)",
      disease: "Meniere's Disease",
      therapy: "Karnapoorna",
      therapy_elaborate:
        "It is the procedure of the instillation of the drug in the ear.",
      medicine: "Brahmi,Ashwagandha,Vacha,Shankhapushpi,Mulethi,Guggul",
      description:
        "1.Brahmi (derived from the name of Lord Brahma and Goddess Saraswati) is a perennial herb most well known for its memory enhancing property.Brahmi tea that is made by brewing Brahmi leaves helps to manage cold, chest congestion and bronchitis by clearing out the mucus from the air passages which helps ease breathing. It also reduces pain and inflammation in the throat and respiratory tracts due to its anti-inflammatory property,2.Ashwagandha is a popular herb used in traditional Indian medicine (Ayurveda) for stress relief and to improve general health. It can help you relax and reduce swelling.Some lab studies show that it can slow the growth of cancer cells, but this effect has not been observed in humans,3.Vacha is an ancient herb having various health benefits. The name “Vacha” in Sanskrit means speaking clearly because this herb stimulates intelligence and expression. In Ayurveda, Vacha is known as a rejuvenating herb because of its effect on the nervous system. It is bitter in taste and is used in the dried form,4.Shankhpushpi, clad by the vernacular names Shankhini, Kambumalini, Samkhapushpi, Sadaphuli, and Sankhaphuli is a potent memory booster and brain tonic that actively works to improve intelligence and functioning of the brain. The name shankhpushpi was given to the plant owing to its shankh or conch shaped flowers. It also helps in enhancing concentration, learning capabilities, mental fatigue, insomnia, stress, anxiety, depression, etc,5.Mulethi, also known as mulethi churna is one such classical ayurvedic remedy that has a centuries-long repute of being the ultimate grandma’s remedy for cough and sore throat.This traditional herb exhibits manifold benefits and is extensively used in several folk remedies and classical ayurvedic formulations to treat respiratory problems, obesity, skin infection, liver disorders, gastric problem, hormonal regulation, general debility, joint pain and many more,5.The guggul tree is a small, bushy tree and has thorny branches. It makes yellowish gum resin in small ducts found all over its bark. The guggul tree is hit by making a cut on its bark, due to which the resins flow out and are allowed to harden before they are collected.",
      use: "1.Brahmi helps to reduce the symptoms of mental illness like anxiety and depression. According to Ayurveda the nervous system is controlled by Vata and imbalance of Vata causes mental illness. Brahmi helps in balancing Vata and controlling the symptoms of mental illness,2.Ashwagandha is commonly available as a churna, a fine sieved powder that can be mixed with water, ghee (clarified butter) or honey. It enhances the function of the brain and nervous system and improves the memory. It improves the function of the reproductive system promoting a healthy sexual and reproductive balance. Being a powerful adaptogen, it enhances the body's resilience to stress. Ashwagandha improves the body's defense against disease by improving the cell-mediated immunity. It also possesses potent antioxidant properties that help protect against cellular damage caused by free radicals,3.Vacha (Acorus calamus Linn. (Acoraceae)) is a traditional Indian medicinal herb, which is practiced to treat a wide range of health ailments, including neurological, gastrointestinal, respiratory, metabolic, kidney, and liver disorders,4.According to Ayurveda, Shankhpushpi helps to calm down the brain and relieve stress as well as anxiety. It also improves memory by acting as a brain tonic due to its Medhya (improves intelligence) property. You can take Shankhpushpi powder along with warm milk or water to help boost memory and concentration,5.Mulethi is an excellent digestive herb. The anti-flatulent property of the roots reduces the formation of gas in the alimentary canal, thus reducing flatulence, bloating and abdominal distension. It also increases appetite, reduces indigestion and promotes better absorption of nutrients in the body higher concentration of fibre in the root powder, makes this a potent remedy for constipation and other digestive issues,5.Guggul has been used in the Indian traditional system for thousands of years to manage inflammation, gout, rheumatism, arthritis, obesity, and lipid metabolism disorders. It is also known as Guggula, Gugar, Guggal, and Indian bdellium.",
      imageUrl:
        "https://www.2minutemedicine.com/wp-content/uploads/2014/11/Menieres-Disease.jpg",
    },
    {
      id: "5",
      department: "Shalankya Tantra(ENT)",
      disease: "Nosebleed/Epistaxis",
      therapy: "Nasyam (Nasally administered treatments)",
      therapy_elaborate:
        "As the head of the human body is considered equal to the root of the tree in Ayurveda, it is essential that the organs in the region stay clear and balanced. A great way to clear out any blockages and diseases of the neck, head, nose, scalp and hair, Nasyam is a method by which medicated oil droplets are gently introduced in the nose, which is absorbed by the body's circulatory system, nourishing all organs above the neck. A prior preparation is necessary, where the person’s face and neck are made receptive to the medicine by steaming. The specially medicated mix irritates the mucus lining of the sinuses, leading to the secretion of the collected doshas. This is a procedure that required expert supervision, as is done by the highly experienced professionals at Rajah Ayurveda.",
      medicine: "manjistha,kama dudha,Sheesaham Juice,Bail Juice",
      description:
        "1.In ayurvedic medicine, Manjistha is a blood purifying herb. It cools and detoxifies the blood, removes stagnant blood, and dissolves obstructions in the blood flow. Manjistha also helps protect gums from receding. It is also believed to have astringent and anti-oxidant properties,2.Kamdudha Ras is an Ayurvedic medicine, with herbal and mineral ingredients, in tablet form. It is used in treating gastritis and bleeding diseases. This medicine is used more in North Indian Ayurvedic treatment method and should only be taken strictly under medical supervision,3.Usable parts – Rosewood bark, leaves, root. Quantity – Quath 5 to 10 tola. Kalk 1 to 3 grams, Swaras (leaf juice) 1 to 4 tola. White rosewood - bitter, cool and removes bile and irritation,4.Bael contains chemicals called tannins, flavonoids, and coumarins. These chemicals help to reduce swelling (inflammation). This might help treat asthma, diarrhea, and other conditions. Also, some of these chemicals help to reduce blood sugar.Bael fruits are a power punch of various nutrients like beta-carotene, protein, riboflavin and vitamin C. It is loaded with vitamin B1 and B2, thiamine, riboflavin, niacin, carotene and possesses good amounts of minerals like calcium, potassium, fiber and good fats.",
      use: "1.Manjistha or Indian Madder is considered to be one of the best blood-purifying herbs. It is mainly used to break down blockages in the blood flow and remove stagnant blood. Manjistha herb can be used both internally and externally on skin for promoting skin whitening,2.It is used in treating gastritis and bleeding diseases. It is used in Ayurvedic treatment of Gastritis, diarrhea with blood discharge and diabetes. It is used to treat female complaints such as leucorrhea, heavy menstrual bleeding. It also helps to relive symptoms associated with burning sensation in palms and soles,3.Make a decoction of 10-15 leaves of rosewood and drink it for 21 days in the morning and evening, it is beneficial,Jeevan Ras Sheesham Juice is a highy effective health and dietary supplement used for the treatment of obesity, vitiligo, fever, non-healing wounds, ulcers, intestinal parasites etc,4.The antioxidants present in this fruit cure gastric ulcer, aid in digestion, and treat diabetes. The laxative property prevents constipation and the anti-fungal components keep infections at bay.",
      imageUrl:
        "https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322333_2200-800x1200.jpg",
    },
    {
      id: "6",
      department: "Shalankya Tantra(ENT)",
      disease: "Swimmer's Ear",
      therapy: "Karna Dhoomapana",
      therapy_elaborate:
        "Karna Dhoomapana is a specialized and effective Ayurvedic procedure performed in order to cure the diseases or disorders which is related with the ear and auditory canal.It comprises of two different words “karna-(which indicates ear) and Dhoomapana”-(which means puffing of medicated fumes into the ear).Karna Dhoomapana is done by igniting a varthi (Vick) which is prepared out of combination of medicated powders and allowing the fumes to enter into the ear for a specified time as advised by the Doctor.While blowing the fumes of varthi, the medicated fumes which has volatile property enters into the external auditory canal and reaches the tympanic membrane. Owing to its medicinal property and slight warm temperature, it is absorbed by the tympanic membrane which transfers to the tympanic cavity where malleus incus and stapes is present.Due to its medicinal property it reduces the inflammation on these areas, clears infections and also it helps to stimulate the vestibular and cochlear nerves thereby helps in proper functioning of the ear.",
      medicine:
        "Jatamansi,Ashwagandha,Gangeruki,Kelamool,Jalkumbhi,Tulsi oil,Baelgiri,Sathra Oil",
      description:
        "1.Jatamansi, also known as “tapaswani” in Ayurveda, is a perennial, dwarf, hairy, herbaceous and endangered plant species. It acts as a brain tonic and helps to improve memory and brain functions by preventing cell damage due to its antioxidant property. It also calms down the brain and manages anxiety as well as insomnia.2.Ashwagandha is one of the most important herbs in Ayurveda, which is a traditional form of alternative medicine based on Indian principles of natural healing.People have usedTrusted Source ashwagandha for thousands of years to relieve stress, increase energy levels, and improve concentration.The ashwagandha plant is a small shrub with yellow flowers that’s native to India and Southeast Asia. People use extracts or powder from the plant’s root or leaves to treatTrusted Source a variety of conditions, including anxiety and fertility issues.3.Gangeruki (Grewia populifolia) oil is used as analgesic and antiseptic. It cures dumbness also.The plant is an excellent astringent, cardiac tonic, diuretic and aphrodisiac agent.4.Kelamool (Musa acuminate) oil is highly effective in speeding up the process of healing and relieves the earache.5.The leaves are approximately 13cm long and 17cm wide and of fan-shaped having parallel venation, blunt apex, and entire margin,6.Tulsi has proved to be highly effective in protecting our body from various infections and diseases of the liver, skin, kidney, etc. It contains powerful oxidants that can help in keeping your blood pressure levels and cholesterol levels under control, making it one of the best heart-healthy foods. It is also good for diabetes as it possesses hypoglycaemic properties which are known to help lower blood sugar levels,7.Bael contains chemicals called tannins, flavonoids, and coumarins. These chemicals help to reduce swelling (inflammation). This might help treat asthma, diarrhea, and other conditions. Also, some of these chemicals help to reduce blood sugar,8.Sathra oil (Origanum vulgare) is known for its strong aroma and antiseptic properties. It is a natural substance and contains two key compounds carvacrol and thymol.",
      use: "1.Jatamansi, as mentioned in Ayurveda, have been used in various herbal formulations including dietary supplements. This important traditional drug is also used to treat epilepsy, hysteria, syncope, convulsions, and mental weakness.2.In Ayurvedic medicine, ashwagandha is considered a Rasayana. This means that it helps maintain youth, both mentally and physically.There is some evidence to suggest that the herb can have neuroprotective and anti-inflammatory effects. Inflammation underpins many health conditions, and reducing inflammation can protect the body against a variety of conditions.3. It is commonly used for the treatment of ulcers. It is also used for treating stomach disorders. It has blocking action useful in bleeding disorder such as menorrhagia, ulcerative colitis etc.4.Kelamool (Musa acuminate) oil is highly effective in speeding up the process of healing and relieves the earache.5.The Plant is bitter, pungent flavored having cooling, laxative property. It is useful in “Tridosha,” fever, and diseases of blood. The root is laxative, emollient, and diuretic,6.Tulsi oil (Ocimum sanctum) is anti spasmodic, anti inflammatory, anti bacterial and skin care. It is used in ringworm and other cutaneous diseases and earache,7.Baelgiri (Aegle marmelos) when applied to the troublesome ear on a plug of cotton wool, heals infection and relieves pain,8.It is a natural substance and contains two key compounds carvacrol and thymol which are directly involved in inhibiting harmful micro-organisms that cause many illnesses and complications. It possesses anti-oxidant and anti-inflammatory properties which prevent inflammation.",
      imageUrl:
        "https://my.clevelandclinic.org/-/scassets/images/org/health/articles/8381-swimmers-ear",
    },
    {
      id: "7",
      department: "Shalankya Tantra(ENT)",
      disease: "Sleep Apnaea",
      therapy: "Karnapurana & Nasya",
      therapy_elaborate:
        "Karna Purana is an Ayurvedic therapy wherein the ears are filled with herb-o-mineral oils that lubricate the delicate filaments of the ear canal, remove impurities, and improve hearing capacity. Karna means “ear” and Purana denotes “filling” or “pouring”. The ears are an important sense organ.",
      medicine: "Ashwagandha, Jatamamsi, Shankhapushpi, Sarpagandha,Nirgundi",
      description:
        "1.Ashwagandha is an excellent adaptogen that calms the nerves, mitigates stress and guarantees smooth transmission of signals all along the body, to help breathe deeply. In addition, it is imbued with phytonutrient triethylene glycol, which induces undisturbed sleep at night, to efficiently combat sleep apnea and improve the quality of rest,2.Jatamansi holds extraordinary potential in stimulating deep sleep at night, thanks to the treasure trove of plant-based biochemicals present in the herb,3.A potent herb that boosts brain power, shankapushpi is very useful in soothing pounding headaches and agitated moods that are often experienced in instances of sleep apnea,4.Bestowed with tranquilising compounds that pacify exacerbated Vata dosha, Sarpagandha is a time-tested remedy to enhance quality and quantity of sleep, as well as treat heart-related conditions encountered in apnea,5.Famed as a panacea for all ailments, nirgundi is a versatile herb containing a powerful essential oil, that tremendously uplifts breathing functions, lung power and also pacifies aggravated Vata dosha in the system.",
      use: "1.Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system.Adaptogens are believed to help the body resist physical and mental stress. Some of the conditions it is used for include insomnia, aging, anxiety and many others, but there is no good scientific evidence to support most of these uses. There is also no good evidence to support using ashwagandha for COVID-19,2.It balances the perturbed Vata dosha, instils tridoshic harmony of Pitta, Kapha, Vata in the body, diminishes stress, tension in the nervous system and soothes a heated body due to its Sheeta or cooling nature,3.Being a Medhya or mind-stimulating plant, it heals mental fatigue, elevates nervous system activity, ensures sound sleep and vastly improves productivity, concentration, memory,4.This plant contains strong antioxidants that relax the blood vessels, facilitate optimal circulation of blood, oxygen, nutrients to tissues, organs and bring down high blood pressure,5.Pouring just 2 drops of nirgundi oil into the nostrils and inhaling the invigorating aroma before bedtime prevents frequent snoring and augments uninterrupted sleep cycles.",
      imageUrl:
        "https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2013/08/26/10/40/sl7_sleep_apnea-8col.jpg",
    },
    {
      id: "8",
      department: "Shalankya Tantra(ENT)",
      disease: "Acoustic Neuroma",
      therapy: "Karnapurana & Nasya",
      therapy_elaborate:
        "Karna Purana is an Ayurvedic therapy wherein the ears are filled with herb-o-mineral oils that lubricate the delicate filaments of the ear canal, remove impurities, and improve hearing capacity. Karna means “ear” and Purana denotes “filling” or “pouring”. The ears are an important sense organ.",
      medicine:
        "Ashwagandha Capsules,Guggul capsules,Curcumin Capsules,Tulsi Capsules,Chanderprabha Vati,Kanchnaar Guggul",
      description:
        "1.These capsules are made from the pure extract of 'Ashwagandha' herb also known as Withania Somnifera. The medicine is an excellent immune and energy booster. It enhances the physical and mental capabilities of the body. The medicine works towards balancing the doshas by eliminating excessive toxins out of the body,2.As the name suggests, these capsules are prepared using best quality guggulu herbal resin. They are useful in maintaining healthy muscles and relieving muscular pain. It is beneficial in revitalizing the cells and in rejuvenating them,3.These capsules are very effective in treating Acoustic Neuoma as they are made of curcumin which is known for its anti-microbial, anti-infective, and anti-inflammatory properties. These capsules help with healing process,4.As the name suggests, these capsules are prepared using standardized extract of herb Tulsi. Tulsi is considered to be the most sacred herb and is very effective in treating cancer or tumors and in reducing the ill effects of radio therapy,5.This medicine is a classical formulation useful in treating cancer, tumors and fibroids as it helps in balancing the kapha dosha. It acts like a catalyst for other herbal medicines to deliver faster therapeutic action. The tablets are a blend of 23 herbs like shilajit, guggul, sharkara, karpoor, dacha, mustak, haridra, amalaka, chvya, vidanga, guduchi, shunthi, maricha etc. The medicine helps with swelling, nausea and vomiting symptoms,6.This herbal product is prepared from the standardized extract of herbs like amalaka, haritaki, bibhitaki, shunthi, marich, pippali, varuna and kachnar bark. The combined formulation has anti-inflammatory and anti-cancerous properties. ",
      use: "1.It works in improving circulatory, reproductive and adrenal systems too. The medicine helps in reducing the stress and anxiety levels of the patient.Ashwagandha herb is known for its anti-stress and adaptogenic action leading to physical fitness. It stabilizes the blood sugar and also lowers the cholesterol. It has natural rejuvenating properties that helps in maintaining nourishment of the tissues,2.Guggul is praised for its anti-inflammatory properties. Preliminary research suggests it may help treat certain anti-inflammatory conditions, such as acne, eczema, psoriasis, and arthritis. It has also been used to promote weight loss, treat hypothyroidism, and manage cholesterol and blood sugar levels,3.This medicine acts as a tonic for all body systems like digestive, respiratory and circulatory. It is the best blood purifier and metabolism regulator. Curcumin is an active compound found in turmeric. The medicine protects the body from the damage caused by free radicals,4.Tulsi has proved to be highly effective in protecting our body from various infections and diseases of the liver, skin, kidney, etc. It contains powerful oxidants that can help in keeping your blood pressure levels and cholesterol levels under control, making it one of the best heart-healthy foods. It is also good for diabetes as it possesses hypoglycaemic properties which are known to help lower blood sugar levels,5.Chandraprabha Vati might be useful in managing various urinary complications. It helps to prevent the formation of toxins and removes them through urine by increasing urine flow. It also helps to remove kidney stones by increasing the production of urine due to its diuretic activity,6.This medicine helps in reducing the size of cysts or tumors, and is useful in treating all kinds of blockages.",
      imageUrl:
        "https://newsnetwork.mayoclinic.org/n7-mcnn/7bcc9724adf7b803/uploads/2016/12/a-medical-illustration-of-an-acoustic-neuroma-original.jpg",
    },
    {
      id: "9",
      department: "Shalankya Tantra(ENT)",
      disease: "Dizziness and Vertigo",
      therapy: "Karnapurana & Nasya",
      therapy_elaborate:
        "Karna Purana is an Ayurvedic therapy wherein the ears are filled with herb-o-mineral oils that lubricate the delicate filaments of the ear canal, remove impurities, and improve hearing capacity. Karna means “ear” and Purana denotes “filling” or “pouring”. The ears are an important sense organ.",
      medicine: "Kaunch Beej, Shankapushpi,Amalaki,Jatiphala,Guduchi",
      description:
        "1.Kaunch beej is a superb neuroprotective herb, with profuse amounts of levodopa amino acid that stimulates brain functions and also balances the three doshas of Vata, Pitta, Kapha,2.Laden with alkaloids that promote brain power, shankapushpi possesses the ability to decrease precarious spinning activities and preserve inner ear balance,3.The ubiquitous Indian gooseberry, also known as amla or amalaki, is abundant in vitamin C, an antioxidant that thwarts toxic free radicals from the brain and enhances nervous system operations,4.Jatiphala or jaiphal, commonly known as nutmeg, is imbued with a miraculous bioactive compound called myristicin, which bolsters brain functions,5.Guduchi is rich in antioxidants which boost cognitive functions of memory, thinking, concentration, elevate neurotransmitter functions to uplift mood and normalize an exacerbated vata and pitta dosha.",
      use: "1.Drinking a mixture of 1 tsp kaunch beej powder mixed with 1 small glass of warm milk soothes throbbing headaches and resolves vertigo,2.Taking a pacifying decoction of 2 grams of shankapushpi powder dissolved in a cup of warm water after dinner at night remarkably suppresses the shaky sensations in vertigo,3. Consuming a small portion of amla juice with 2 tsp honey twice a day alleviates uncomfortable symptoms of vertigo such as nausea, migraine and restores inner ear balance,4.Preparing a mixture of 1 tbsp nutmeg powder with 1 tsp cumin powder and honey and ingesting this along with meals twice a day provides significant relief from unstable movements in vertigo and heightens productivity as well,5. Having 2 – 3 tbsp of guduchi kashaya, made along with coriander and neem extracts, every morning half an hour before food eases unsteadiness in the body and dispels tingling feelings in the ears.",
      imageUrl: "https://www.wakeent.com/wp-content/uploads/2018/08/dizzy.jpg",
    },
    {
      id: "10",
      department: "Shalankya Tantra(ENT)",
      disease: "Hay Fever",
      therapy: "Panchakarma",
      therapy_elaborate:
        "Karna Purana is an Ayurvedic therapy wherein the ears are filled with herb-o-mineral oils that lubricate the delicate filaments of the ear canal, remove impurities, and improve hearing capacity. Karna means “ear” and Purana denotes “filling” or “pouring”. The ears are an important sense organ.",
      medicine:
        "Long pepper or pippali,Malabar nut,Liquorice,Turmeric,Tulsi(Holy basil)",
      description:
        "1.Pippali is an effective home remedy in managing cough and cold. Swallowing Pippali powder along with honey after lunch and dinner helps release mucus from the air passages due to its expectorant property, thus allowing the patient to breathe easily. It’s consumption might also help promote weight loss by improving the body’s metabolism. Consuming Pippali powder might be useful in managing constipation by promoting bowel movements due to its laxative property,2.Vasaka also known as ‘Malabar Nut’ in English, ‘Adhathodai’ in Tamil, ‘Vasa’ in Telugu and ‘Arusha’ in Hindi, is a potent ayurvedic plant that enhances the respiratory system. The plant has manifold curative properties and is an ultimate remedial measure for a lot of health anomalies like breathing trouble, cough, and cold, nasal congestion, sore throat, asthma, bronchitis, other upper respiratory tract infections, bleeding disorders, etc,3.Licorice is the extract of Glycyrrhiza glabra roots and is often used in ancient Siddha medicine and is approved by the German commission. Licorice is used for gastritis, cough, bronchitis, ulcers, inflammation, and epilepsy.62 The association between the use of licorice and hypertension is well established. It is attributed to sodium retention, edema, and hypokalemia,4.Turmeric is a common spice that comes from the root of Curcuma longa. It contains a chemical called curcumin, which might reduce swelling,5.The holy basil plant is a small annual or short-lived perennial shrub, up to 1 metre (3.3 feet) in height. The stems are hairy and bear simple toothed or entire leaves oppositely along the stem. The fragrant leaves are green or purple, depending on the variety. The small purple or white tubular flowers have green or purple sepals and are borne in terminal spikes. The fruits are nutlets and produce numerous seeds.",
      use: "1.Pippali is an effective herb in managing cough and cold. Pippali controls cough, releases mucus, clears air passages, thus allowing the patient to breathe freely. This is because Pippali has decongestant, bronchodilator and expectorant effects due to its Kapha balancing properties,2.Malabar nut is used to loosen chest congestion, open the breathing tubes (bronchi), and treat spasms. It is used for upper airway infections, common colds, cough, asthma, and tuberculosis,3.Licorice is an herb that grows in parts of Europe and Asia. Licorice root contains glycyrrhizin, which can cause side effects when eaten in large amounts. The chemicals in licorice are thought to decrease swelling, decrease cough, and increase the chemicals in our body that heal ulcers,4.Turmeric has a warm, bitter taste and is frequently used to flavor or color curry powders, mustards, butters, and cheeses. Because curcumin and other chemicals in turmeric might decrease swelling, it is often used to treat conditions that involve pain and inflammation.People commonly use turmeric for osteoarthritis. It is also used for hay fever, depression, high cholesterol, a type of liver disease, and itching, but there is no good scientific evidence to support most of these uses. There is also no good evidence to support using turmeric for COVID-19,5.Tulsi's broad-spectrum antimicrobial activity, which includes activity against a range of human and animal pathogens, suggests it can be used as a hand sanitizer, mouthwash and water purifier as well as in animal rearing, wound healing, the preservation of food stuffs and herbal raw materials and traveler's health.",
      imageUrl:
        "https://www.houstonent.com/hubfs/blog%20images/what%20is%20hay%20fever%20in%20houston.jpg",
    },
  ];
  return (
    <SafeAreaView style={{ marginHorizontal: 20, marginBottom: 50 }}>
      <View style={{ height: 50 }}>
        <Appbar
          title={item.department}
          color={COLORS.white}
          icon={"search1"}
          color1={COLORS.white}
          onPress={() => navigation.goBack()}
          onPressSearch={() => navigation.navigate("Search")}
        />
      </View>
      <FlatList
        data={Ent}
        showsVerticalScrollIndicator={false}
        keyExtractor={(item) => item.id}
        contentContainerStyle={{ columnGap: SIZES.small }}
        renderItem={({ item }) => (
          <View style={{ marginBottom: 10 }}>
            <MedicineTile
              item={item}
              onPress={() => navigation.navigate("Departmentdetails", { item })}
            />
          </View>
        )}
      />
    </SafeAreaView>
  );
};

export default Ent;

const styles = StyleSheet.create({});
