import { FlatList, StyleSheet, Text, View } from "react-native";
import React from "react";
import { useRoute } from "@react-navigation/native";
import Appbar from "../../components/Reuseable/Appbar";
import { SafeAreaView } from "react-native-safe-area-context";
import { COLORS, SIZES } from "../../constants/themes";
import MedicineTile from "../../components/Reuseable/MedicineTile";

const Sexology = ({ navigation }) => {
  const route = useRoute();
  const { item } = route.params;
  const Sexology = [
    {
      id: "1",
      department: "Vajikaran(Sexology)",
      disease: "Gonorrhea",
      therapy: "Vajikaran Therapy",
      therapy_elaborate:
        "Vajikarana therapy in Ayurveda increases your sexual life and strength now few tips for overcoming sexual problems consume herbal preparation for rejuvenating the reproductive organ daily herbal massage on your penile region sleep at least for 8 hours do yoga exercise meditation regularly avoid taking alcohol tobacco or drugs take a proper healthy diet.",
      medicine: "Haritaki,Bahera,Giloy,Manjishtha,Neem",
      description:
        "1.Technically the fruit of the deciduous myrobalan plum tree, haritaki is considered an important herb in Ayurveda and Siddha medicine, both forms of indigenous medicine in India. The fruit itself is small, oblong, and less than an inch in size.The fruits are often collected when they’re still green and raw and then dried until golden brown or black. They’re then powdered and made into Ayurvedic remedies. The fruit’s potency is based on where the fruit was collected, its color, and its shape,2.Bahera is a very useful remedy for avoiding cough and cold naturally. Bibhitaki powder mixed with honey will treat a cough and cold effectively. It also releives the symptoms of a sore throat.Belleric Myrobalan or Bahera acts as an immunity booster and is beleived to increase longevity when the powder of the dried herb is fried in ghee and consumed regularly,3.Giloy, also known as Amrita or Guduchi in Hindi, is an herb that helps improve digestion and boost immunity. It has heart-shaped leaves that resemble betel leaves. All parts of the plant are used in Ayurvedic medicine. However, the stem is thought to have the most beneficial compounds.Giloy is Titka (bitter) in taste and Ushna (hot) in potency. After metabolization, it becomes Madhura (sweet) and Guru (heavy) in nature. It has Deepan (appetizer) and Pachan (digestive) properties which help in improving digestion,4.Manjistha is an herbaceous branched climber or creeper of evergreen origin that grows up to 10 m. It has thick, long, cylindrical, bark which is red in colour and long, slender, quadrangular stems that are sometimes prickly or glabrous. The leaves are ovate or heart shaped, pointed, and arranged in a whorl on the stems. The flowers are very small, greenish white and arranged in a branched cluster. Fertile flowers are followed by small globose berries that are initially green turning in to bluish-black, or reddish-purple as they mature. The fruits usually enclose small globose seeds. Manjistha being a creeper plant chiefly uses tiny hook like structures at the leaves and stems to climb some structure,5.Neem, (Azadirachta indica), fast-growing tree of the mahogany family (Meliaceae), valued as a medicinal plant, as a source of organic pesticides, and for its timber.Neem trees can reach 15–30 metres (49–98 feet) in height and have attractive rounded crowns and thick furrowed bark. The compound leaves have toothed leaflets and are typically evergreen.",
      use: "1.Haritaki is a magical remedy that holds high significance in treating countless health problems including indigestion, gastritis, lung disease, obesity, impotence, cough, cold, asthma, vision defects, urinary tract infections and hair, and skin problems,2.Bahera, beleric myrobalan and bibhitaki are the common names of behada. What are the benefits of behada fruits? Behada fruit is used to treat asthma, bronchitis, hepatitis, diarrhoea, piles, dyspepsia, eye diseases, hoarseness of voice, scorpion-sting, hair tonic and menstrual disorders,3.Giloy juice helps to maintain overall health. According to Ayurveda, Giloy can help control high blood pressure due to digestive problems. Giloy improves metabolism and helps maintain a good digestive system. This helps reduce the risk of high blood pressure levels,4.Manjistha or Indian Madder is considered to be one of the best blood-purifying herbs. It is mainly used to break down blockages in the blood flow and remove stagnant blood. Manjistha herb can be used both internally and externally on skin for promoting skin whitening,5. Neem is commonly used in shampoos for treating dandruff and in soaps or creams for skin conditions such as acne, psoriasis, and athlete’s foot. It is also a component in some toothpastes and mouthwashes, especially in the Indian subcontinent, and young twigs are used directly as crude toothbrushes in rural areas. Neem leaves have long been used as a traditional treatment for diabetes, and there is some clinical evidence suggesting that it may help control blood sugar levels. Neem oil and neem bark and leaves are unsafe for consumption by pregnant women and can cause miscarriage.",
      imageUrl:
        "https://media-us.amboss.com/media/thumbs/big_6454d79218c9a6.49927856.jpg",
    },
    {
      id: "2",
      department: "Vajikaran(Sexology)",
      disease: "Chlamydia",
      therapy: "Nasya,Vamana & Virecha",
      therapy_elaborate:
        "Vamana helps to treat disorders related to Kapha Dosha and eliminates morbid contents through oral emesis. Virechana mainly done for diseases related to the Pitta and Kapha Dosha and this therapy eliminate morbid content through purgation (induced defecation).",
      medicine: "Ashoka,Karpura,Haridra,Neem,",
      description:
        "1.It is a friend of women,which is helpful in mennorhagia and in the female reproductive system.It contains various Carbohydrates and tennis and is helpful in balancing Kapha & Pitta doshas.Has analgesic and antidotal properties ,which regularise the hormones and provides stamina and strength in females.Is a natural detoxifier and prevents the reformation of calculi,2.It is helpful in balancing Tridoshas and secrets, gastric and pancreatic juices.Resolves the swelling of body parts and provides relief to joint pain and inflammation.Improves vision and acts as a catalyst.Controls the inflammation and thus provides a soothing effect on the body and heals the skin,3.It is helpful in balancing tridoshas of the body and useful in the scraping property.Is a natural blood purifier which removes the accumulation in the blood vessels.Reduces inflammation and stimulates the digestive fire.Heals wounds and rejuvenates the skin tone.Is useful for immune modulation by correcting metabolism.Expels the extra kapha and megha doshas from the body,4.It is a natural blood purifier and is helpful in balancing pitta and kapha doshas.Has antibacterial and antiviral properties.Reduces the swelling and treats arithriris and joint pain.Improves the digestion process and cleanse the wounds quickly.Useful in various types of skin diseases and problems related to the uniarary tract.",
      use: "1.Ashoka helps to manage various gynecological and menstrual problems in women such as heavy, irregular and painful periods. It can be taken in the form of churna/powder or capsule twice a day after meals to get relief from abdominal pain and spasms2.Karpura plays various important properties useful in cure of certain diseases. It acts as antispasmodic, anti-inflammatory, analgesic, antiseptic, anti¬infective, rubefacient, contraceptive, cough suppressant, mild expectorant and nasal decongestant. It can also be used for injection, ingestion or inhalation purpose,3. Haridra is used in the traditional system of medicine. It is used as an antioxidant and possesses various beneficial properties such as anti-inflammatory, anti-allergic, antiseptic, blood cleansing etc. It is widely prescribed Ayurvedic drug and is used in various diseases,4.All parts of the neem tree- leaves, flowers, seeds, fruits, roots and bark have been used traditionally for the treatment of inflammation, infections, fever, skin diseases and dental disorders.",
      imageUrl:
        "https://image.slidesharecdn.com/chlamydiatrachomatis-201017154540/85/chlamydia-trachomatis-medical-information-3-320.jpg?cb=1669169718",
    },
    {
      id: "3",
      department: "Vajikaran(Sexology)",
      disease: "Cancroids",
      therapy: "Vajikaran therapy",
      therapy_elaborate:
        "Vajikaran therapy is said to revitalize all the seven dhatus (body elements), therefore, restores equilibrium and health. Keeping in mind the concept of vajikaran as described in the texts of Ayurveda, it definitely offers a solution to minimize the shukra (sperm and ovum) defects and to ensure a healthy progeny. The experimental studies related to vajikaran therapy are scarce and generally lack scientific vigor.",
      medicine:
        "Kiratatika,Guggul,Manjishtha,Chandana,Yastimadhu,Daruharidra,Shireesha",
      description:
        "1.Kiratatikta, also known as Swertia chirata, is a bitter herb that holds a special place in the world of traditional medicine. In this comprehensive guide, we will explore the definition, uses, benefits, and potential side effects of Kiratatikta, revealing the therapeutic potential of this bitter boon from nature,2.Guggul is also known as “Pura” which means “wards off disease”. It is used as a source of commercial “Gum guggul”. The major bioactive component of Guggul is oleo-gum-resin (a mixture of an oil and yellowish or brownish fluid secreted from the plant stem or bark). It is this oleo-gum resin that is said to have therapeutic benefits.According to Ayurveda, Guggul is useful in weight management as it helps to improve metabolism and reduce Ama (toxic remains in the body due to improper digestion) by increasing the digestive fire,3.Manjistha which goes by the scientific name Rubia cordifolia is a type of flowering plant from the coffee family Rubiaceae. Manjistha is an herbaceous branched climber or creeper of evergreen origin that grows up to 10 m. It has thick, long, cylindrical, bark which is red in colour and long, slender, quadrangular stems that are sometimes prickly or glabrous. The leaves are ovate or heart shaped, pointed, and arranged in a whorl on the stems. The flowers are very small, greenish white and arranged in a branched cluster. Fertile flowers are followed by small globose berries that are initially green turning in to bluish-black, or reddish-purple as they mature,4.Sandalwood or Svetchandan is also known as Srigandha as per Ayurveda. It is one of the oldest and most precious sources of natural fragrance with immense medicinal and commercial significance. Sandalwood tea helps in managing the liver and gallbladder problems due to its hepatoprotective property,5.Yastimadhu is also recognized as licorice and mulethi, one of the famous ayurvedic herbs known by almost every Indian. Botanically, it is famous by the name Glycyrrhiza Glabra, a flowering plant's root which is used in various ayurvedic formulations for centuries. Most Indians chew this household item whenever their voice goes down. or they feel tired,6.Daruharidra is also called as Indian barberry or Tree Turmeric. It has been used in Ayurvedic medicine system since a long time. The fruit and stem of Daruharidra are widely used for its medicinal benefits. The fruit is edible and is a rich source of vitamin C.Daruharidra is mainly beneficial for sex.",
      use: "1.Chirata is used for fever, constipation, upset stomach, loss of appetite, intestinal worms, skin diseases, and cancer. Some people use it as “a bitter tonic.” In India, it has been used for malaria, when combined with the seeds of divi-divi (Guilandina bonducella),2.Guggul is praised for its anti-inflammatory properties. Preliminary research suggests it may help treat certain anti-inflammatory conditions, such as acne, eczema, psoriasis, and arthritis. It has also been used to promote weight loss, treat hypothyroidism, and manage cholesterol and blood sugar levels,3.Manjistha or Indian Madder is considered to be one of the best blood-purifying herbs. It is mainly used to break down blockages in the blood flow and remove stagnant blood. Manjistha herb can be used both internally and externally on skin for promoting skin whitening,4.In Ayurveda, Red Sandalwood is revered for its cooling, soothing, and astringent properties, making it particularly beneficial for balancing Pitta dosha, which is associated with heat and inflammation. It is widely used to address various skin concerns such as acne, blemishes, and infections,5.The Yashtimadhu powder can help with inflammation, stomach pain, headaches, and ulcers. Because of this, it is a traditional Ayurvedic cure for indigestion, constipation, acidity, gastritis, stomach ulcers, and sores in the mouth,6.Daruharidra is used as a stomachic, bitter tonic, laxative, diaphoretic, antiseptic, and antipyretic. It is used to treat severe eye infections, ulcers, and haemorrhoids externally. The root bark is used to treat skin diseases, boils, wounds, liver problems, ear problems, and antidiarrhoea agent.",
      imageUrl: "https://pbs.twimg.com/media/FT_vBUcXoAEdLlf.jpg",
    },
    {
      id: "4",
      department: "Vajikaran(Sexology)",
      disease: "Human papillomavirus (HPV)",
      therapy: "Yoni prakshalana",
      therapy_elaborate:
        "Yoni means female genetic part and Prakshalanam means washing. In this process, herbal oils are applied through the vaginal route. The treatment is prescribed to alleviate gynecological disorders, treat inflammation, erosions, infertility and provide strength to vaginal muscles.",
      medicine: "Neem,Karanj,Bakuchi,Amla,Giloy",
      description:
        "1.Azadirachta indica, commonly known as neem in India, is also called ‘Margosa’ or ‘Indian Lilac’. It is the most versatile, diverse (different varieties of species) tree in the tropical region (hot regions), that might have medicinal potential. Neem has a lot of beneficial non-wood products like flowers, leaves, fruits, bark, gum, oil, seeds, and neem cake (residue left over after oil is pressed from neem seeds). It is thus considered the most useful tree in comparison to all other tree species,Leaf meals from some tropical legumes have been explored due to the need to look for alternative sources of food for humans and feed for livestock. Neem leaf meal was analysed in a study that found that it has 18.10% crude protein and relatively high crude fibre of about 15-56%. Though the  gross energy content was high at 4.16 kcal/g, the metabolizable energy is low,2.Karanja is a medium sized tree and is normally planted along the highways, roads and canals to stop soil erosion. It is one of the few nitrogen fixing trees to produce seeds containing 30-32% oil. Pongamia grows into a large tree with a 10-metre taproot, creating a huge carbon sinkIt is often planted as an ornamental and shade tree. It is well-adapted to arid zones and has many traditional uses. It is often used for landscaping purposes as a windbreak or for shade due to the large canopy and showy fragrant flowers,3.Bakuchi is an important herb that is used for its medicinal properties. The seeds of Bakuchi are kidney shaped, having a bitter taste and a very unpleasant odor.It’s application also helps reduce boil and skin eruptions due to its strong healing property. According to Ayurveda, Bakuchi powder help improves hair growth and controls dandruff when applied externally due to its Keshya property,5.Cultivated throughout India and nearby countries, amla has gained a following throughout the world as a 'superfruit' It's no surprise — a 100-gram serving of fresh amla berries contains as much vitamin C as 20 oranges.Amla, also known as Indian gooseberries, grows on a flowering tree of the same name. The small berries are round and bright or yellow-green. Though they are quite sour on their own, their flavor can enhance recipes they’re added to,6.Giloy, also known as Amrita or Guduchi in Hindi, is an herb that helps improve digestion and boost immunity. It has heart-shaped leaves that resemble betel leaves. All parts of the plant are used in Ayurvedic medicine.",
      use: "1.Leaf meals from some tropical legumes have been explored due to the need to look for alternative sources of food for humans and feed for livestock. Neem leaf meal was analysed in a study that found that it has 18.10% crude protein and relatively high crude fibre of about 15-56%. Though the  gross energy content was high at 4.16 kcal/g, the metabolizable energy is low,pure neem oil is incredibly potent. To treat acne, fungal infections, warts, or moles, use undiluted neem oil to spot treat affected areas. Lightly dab the neem oil onto the area using a cotton swab or cotton ball, and allow it to soak in for up to 20 minutes. Wash off the oil with warm water,2.Karanja is a medicinal herb mainly used for skin disorders. All parts of Karanja tree (roots, flowers, leaves, bark) are used for medicinal purposes. Karanja is widely used in managing constipation as it helps to improve gut motility and has a laxative property,3.The fruit of the Bakuchi plant is used to prepare tonic to use as an aphrodisiac. It is also used to treat incontinence in men, frequent urination, premature ejaculation and impotence. The seed extract helps to soothe the symptoms of abnormal uterine bleeding and menstrual disorders in women,4.Amal acts as a natural aphrodisiac that improves your sex life. It contains Vitamin C that boosts sperm production in males suffering from low sperm count (clinically known as Oligospermia) and is known to help a man last longer in bed by boosting his libido. Apart from that, this fruit is also known to improve sexual vigor and virility. This is mainly due to the presence of iron and zinc in amla that enhance your sperm quality,6.It has an aphrodisiac quality, which helps boost the libido in men and increases sexual hormone production. Studies have disclosed that this wonder herb has the power to increase sperm count, the volume of ejaculation, sperm motility, and overall male health.If you are looking to enhance your willingness for sex, consuming Giloy juice twice a day can naturally boost testosterone levels that help you perform better in bed.",
      imageUrl:
        "https://i0.wp.com/post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/02/hpv-symptoms-1296x1000-body-1024x793.png?w=1155&h=2137",
    },
    {
      id: "5",
      department: "Vajikaran(Sexology)",
      disease: "Syphillis",
      therapy: "Panchakarma & Rasayana therapy",
      therapy_elaborate:
        "This detoxification therapy aims to eliminate toxins from the body. It may involve procedures like Virechana (therapeutic purgation) and Rakta Mokshana (bloodletting) to remove accumulated toxins and impurities.Rasayanas are rejuvenating therapies that aim to restore vitality and enhance immunity. Specific rasayana formulations may be prescribed by Ayurvedic practitioners to support the body’s healing process. ",
      medicine:
        "Cucurmin,Haritaki,Bibhataki,Amlaki,Shudh Shilajit,Shudh guggulu",
      description:
        "1.Curcumin is a compound in turmeric. It's the active ingredient in this popular spice. It also gives it the yellow color.Curcumin belongs to a class of more than 8,000 compounds called polyphenols. You'll find polyphenols in plant-based foods. They come in different types. They also work as antioxidants, which mean they can help with damage from the sun or chemicals you're in contact with,2.Prized as the “King Of Medicines”, Haritaki is a miraculous ayurvedic fruit that is extensively used for a wide range of traditional remedies. Cultivated from the seeds of Terminalia chebula tree, it is popularly known as Indian walnut for its innumerable benefits or Indian hog plum in English.This dried fruit often termed as Chebulic myrobalan is one of the three musketeers that constitute the potent rejuvenative Triphala formulation,3.Bibhitaki (Terminalia berecilla), is a large deciduous medicinal tree and holds a great value in traditional medicines like Ayurveda and Unani.The fruit of bibhitaki contains a host of plant compounds like beta sitosterol, tannins, gaelic, ethyl and elegiac acid. The yellow colour oil extracted from the seed kernel is highly valued for its astringent and laxative properties. Even the leaves and roots of bibhitaki have potent medicinal values,4. Amlaki Tablets offers certain other health benefits that include its ability to manage high cholesterol levels, helps to normalize blood pressure, effective for diabetics, helps to control glucose levels, helps prevent aging, greying of hair, purify the blood, brighten the skin, improve eyesight, digestion and relieve acidity.It functions as an antioxidant, and it supports the liver in maintaining healthy cholesterol levels,5.Shilajit is a mineral based extract which is pale-brown to blackish-brown in color. It is found in the Himalayan rocks and is composed of a gummy substance. Shilajit contains humus, organic plant materials and fulvic acid. It consists of more than 84 minerals including copper, silver, zinc, iron, and lead.Shilajit is a health rejuvenator that improves sexual stamina and also improves energy levels. This helps manage chronic fatigue, tiredness, lethargy and fatigue due to diabetes. Shilajit is known to improve the testosterone level and enhance male fertility,6.Guggul contains plant steroids that might affect cholesterol levels in the body. One of these substances might also reduce redness and swelling from acne.People use guggul for acne, obesity.",
      use: "1.Based on existing studies, curcumin has been used as a potential therapeutic agent for various neurological disorders, such as dementia, AD, PD, multiple sclerosis, and Huntington’s disease (HD), due its antioxidant, anti-inflammatory, and anti-protein aggregating abilities,Moreover, it modulates an array of cellular progressions, i.e., nitric oxide synthetase activity, protein kinase C activity, epidermal growth factor (EGF) receptor intrinsic kinase activity, nuclear factor kappa (NF-kB) activity, inhibiting lipid peroxidation and production of reactive oxygen species,2.Haritaki is identified as a natural aphrodisiac. Owing to its Rasayana properties, it promotes sexual and reproductive health in both males and females. It relieves stress and stimulates the release of hormones which increases libido. It helps in keeping the uterus and ovaries healthy and improves fertility,3.Maintaining hormonal balance is of utmost importance for a woman’s overall well-being, encompassing various aspects of her health, including sexual well-being. Hormones play a vital role in regulating reproductive functions, mood, energy levels, and libido. When hormones are in equilibrium, women experience improved sexual vitality, enhanced mood, and optimal energy levels. Hormonal imbalance, on the other hand, can lead to irregular menstrual cycles, mood swings, low libido, and other concerns,4.It helps increase stamina, improve mood, enhance immunity, and boost sexual desire. It further helps maintain an optimum temperature in the scrotum. This fruit contains Vitamin C, which helps boost sperm production, while iron and zinc help enhance sperm quality,5.Shilajit may support reproductive health by promoting healthy sperm production and testosterone levels. Furthermore, it can boost energy, potentially improving stamina and athletic performance. Some men use Shilajit as a natural supplement to manage conditions like erectile dysfunction and premature ejaculation,6.Guggul extract is used to increase the sexual problem, impotence as well as to treat infertility related issues. The individuals suffering from facial paralysis and gout problems are recommended to take Guggul formulations. Since ancient times Guggul has been used in the treatment of obesity and diabetic patients.",
      imageUrl:
        "https://irvineskin.com/wp-content/uploads/2021/08/image10-1.png",
    },
    {
      id: "6",
      department: "Vajikaran(Sexology)",
      disease: "Pubic lice",
      therapy: "Vamana & Virechana",
      therapy_elaborate:
        "Vamana helps to treat disorders related to Kapha Dosha and eliminates morbid contents through oral emesis. Virechana mainly done for diseases related to the Pitta and Kapha Dosha and this therapy eliminate morbid content through purgation (induced defecation).",
      medicine: "1.Garlic and Limejuice",
      description:
        "1.Lime is rich in vitamin C, which has been shown to reduce the risk of heart disease. Garlic, on the other hand, can help lower blood pressure and cholesterol levels, reducing the risk of heart attacks and strokes. Incorporating lime and garlic into your diet can help support a healthy heart.",
      use: "1.The use of garlic and lime juice is extremely important in treating the problem of lice. People can take a few pods of garlic and crush. Then they should add lemon juice to turn it into a paste.",
      imageUrl:
        "https://www.pcds.org.uk/imager/gallery/clinical/pubic-lice/11957/Pubic_lice_2_fee391183f15cb4d62773032fe0be92d.jpg",
    },
    {
      id: "7",
      department: "Vajikaran(Sexology)",
      disease: "Hepatitis",
      therapy: "Panchakarma & Rasayana therapy",
      therapy_elaborate:
        "This detoxification therapy aims to eliminate toxins from the body. It may involve procedures like Virechana (therapeutic purgation) and Rakta Mokshana (bloodletting) to remove accumulated toxins and impurities.Rasayanas are rejuvenating therapies that aim to restore vitality and enhance immunity. Specific rasayana formulations may be prescribed by Ayurvedic practitioners to support the body’s healing process.",
      medicine: "Katuki,Kalamegha,Kumari,Punarnava,Kakamachi,Guduchi",
      description:
        "1.Katuki, a traditional herb, originally found in the mountains is rather rare and not as popularly known as other traditional herbs and spices but can offer respite from so many problems that may be weighing down your body.Touted for its intense bitter taste, this eastern root is said to be cooling, cleansing, and anti-bacterial by nature. These properties make Kutki a great option as a powerful herbal antibiotic, Pitta pacifier component, anti-inflammatory agent, detoxifier, and an antimicrobial powerhouse,2.Kalamegha or Bhunimba botanically known as Andrographis paniculata is a small annual herbaceous plant. Kalamegha means dark cloud or Bhunimb means Neem of the ground, as the bitter taste of the small annual herb Kalamegha, is similar to the bitter taste of a large Neem tree,3.Aloe vera is kumari, which means ‘a beautiful young girl.’ Aloe vera is known in Ayurveda as that which keeps a woman always youthful. It is a rejuvenating herb, part of a special class of Ayurvedic herbs known as rasayana. Rasayana herbs are anti-aging, immune system-building, healing agents that help protect your body from the natural wear and tear of everyday life and stress,4.Punarnava is a well known medicinal plant packed with essential nutrients, vitamins such as vitamin C and other constituents.Taking Punarnava juice before meals might help manage stomach disorders such as constipation by promoting bowel movements due to its laxative property. It also provides relief from gas and abdominal pain. Punarnava is effective in improving digestion and managing weight by suppressing appetite,5.Kakamachi is a small, short-lived perennial herb, which mostly grows as a weed in India, typically in dry regions. This herb is native to Eurasia but can be found growing plentifully in different parts of the world.The Kakamachi herb has egg-shaped leaves, with its flowers and fruits (berries) growing in clusters. The flowers of the herb are of white, cream or violet colours, while the ripe berries are black or dark purple in colour,6.Guduchi, scientifically known as Tinospora cordifolia, is a vital remedy in the Indian system of medicine. It belongs to the Menispermaceae family and has been used as a medicament since ancient times. It is also known as Giloy, Amrita or Indian bitter. It is found in dense and dry forests all over India, growing over small trees and bushes at high altitudes. The stem, roots and leaves of Guduchi all have medicinal properties.",
      use: "1.It can be used as an appetizer. Decoction of kutki with honey or kutki powder with sugar is used to treat jaundice in ayurveda. Kutki is also used to make an ayurvedic formulation named 'arogyavardinivati' to treat liver diseases. In ayurveda, kutki is used with various herbs to manage viral hepatitis and fatty liver,2.Kalamegha Strong liquid is a ayurvedic medicine by Swadeshi which is used in indigestion, flatulence, constipation and covers a wide range of hepatic and gastric complaints.Indigestion, flatulence, hepatitis, jaundice, constipation.Kalmegh helps improve digestion due to its laxative properties; it aids in the elimination of faeces. It is also choleretic (helps in improving the properties of bile and causes a substantial increase in the flow of bile) and thus aids in digestion,3.Perfect health through Ayurveda Kumari Kalpam is very effective for certain disease that women normally hesitate to disclose. Some women start deteriorating in health, lose weight, suffer abdominal cramps, stomach burning, body irritation and general weakness that eventually drain their vigor and vitality,4.The herb can be used as a diuretic in kidney disorders and helps to manage symptoms of spleen enlargement. The extract of Punarnava also helps soothe cough as it can act as an expectorant. The root of Punarnava consists of anti-helminthic properties to remove intestinal worms and asthma,5.Kakamachi Solanum nigrum is an Ayurvedic plant used for treating fever, opium poisoning, splenomegaly, diseases of the liver, rodent bites, vitiligo, nausea, diseases of the oral cavity and headache,6.Guduchi is also a powerful herb to enhance your sex drive. It is beneficial in clearing excess heat or Pitta from the reproductive system that can cause pain, disease, and discomfort. In addition, it tones and rejuvenates the reproductive tissues, improves sperm motility, and increases sperm count for men.",
      imageUrl:
        "https://smb.ibsrv.net/imageresizer/image/blog_images/1200x1200/15634/229488/0058066001600712291.jpg",
    },
    {
      id: "8",
      department: "Vajikaran(Sexology)",
      disease: "AIDS/HIV",
      therapy: "Rakta mokshana(blood letting) & Rasayana",
      therapy_elaborate:
        "Rakta moshana is a procedure where toxic blood is drawn out of different body sites based on the location of the vitiated doshas.It is usually done when immediate result are desired such as in case of some pitta related disorders like headaches,conditions affecting the spllen, skin and liver,gout and high blood pressure.Performing the blood letting procedure using leeches has shown prominent effects in improving the health condition of people with HIV infection and AIDS.Leeches not only helped eliminate toxins from the body,but also improved the CD4 cell count,thereby improving the immunity levels,whereas is a treatment procedure that uses rejuvinating herbs and tonics to improve a person's health.Achara rasayana,ahara rasayana and dravya rasayana are all used for treatment in people with HIV/AIDS.It helps people achieve good spiritual and mental health.It also gives relief from anxiety and stress,thereby, preventing diseases that are caused due to increased stress levels.",
      medicine:
        "Amalaki,Ashwagandha,Yashtimadhu,Tulsi,Punarnava,Haritiki,Guduchi,Shatavari",
      description:
        "1.The fruits of amalaki plants are used as rasayana in the treatment of many diseases including HIV infections/AIDS.It pacifies all three doshas.Amalaki fruits are a rich source of Vitamin C and also have antibacterial,antioxidising and anti-inflammatry properties.Amla consumption reduces the risk of bacterial infections and inflammatory conditions,which, in turn prevent prevent diseases in people with HIV/AIDS,2.Ashwagandha has immunomodulatory,anti-oxidising,adaptogenic and anti-inflammatory properties.These properties help inhibit the inflammatory processes in the body.It is also known to relieve depression and anxiety along with improving mental functions due to its anti-stress properties.This herb is also known to protect against infections,especially in those with lowered immunity levels.Therefore helping AIDS/HIV patients to live healthy and stress free life,3.Yastimadhu is helpful in managing HIV infection and AIDS due to its immunostimulant and immunomodulatory effects.It specifically stimulates the immune system's resistance to HIV.It also helps treat other conditions including a sore throat,muscle spasm,inflammation,general debility and ulcers.In addition to its immonomodulatory properties,it also has expectorant(expels phlegm),demucent(sooths mucus membranes),sedative(induces sleep),rejuvenate and laxative(regulates bowel movements) propeties.This plant is native to India.It is commonly used in the traditional Indian medicine system,Ayurveda,5.Punarnava has immunomodulatory properties that make it useful in enhancing the immunity levels in body.It also has antiviral properties that help fight against HIV and prevent bacterial infections such as tuberculosis in people with HIV/AIDS,6.Haritaki is known to have antibacterial,immunomodulatory,anti-inflammatory and anti-oxidising properties that are useful in improving immunity,fighting bacterial infections and preventing inflammatory diseases in people with HIV infection.It also has rejuvenative,astringent(constricts tissues) and laxative(regulates bowel movements) properties.It is used as a tonic for the body,7.Guduchi improves body's defence system and is useful for improving supressed immunity.This is because the active constituents of the plant show immunomodulatory effects,8.Shatavri has antioxidant properties.It is known to be the primary herb that is used for enhancing the immune system and is considered beneficial in people with AIDS.It also improves overall strength.",
      use: "1.Amalaki also helps improve longetivity and quality of life.It increases body's resistance to infection due to its immunomodulatory effects and provides relief from inflammation in the lungs.Amalaki is helpful in proving relief to people who have T.B along with AIDS.You can take amalaki in many forms,e.g, powder,decoction or as directed by your physicians,2.Ashwagandha is also used to treat other health problems such as fatigue,swollen glands and paralysis.You can take ashwagandha in the form of powder,decoction,infused with oil or ghee or as per your physicians directions,3.You can take yastimadhu in the form of a decoction prepared with water or milk,infused with ghee,powder or as per physians direction.The Yashtimadhu powder can help with inflammation, stomach pain, headaches, and ulcers. Because of this, it is a traditional Ayurvedic cure for indigestion, constipation, acidity, gastritis, stomach ulcers, and sores in the mouth.Mulethi herb can treat asthma, cough, cold, sore throat and other respiratory ailments. Mulethi has antioxidant properties help to reduce inflammation specifically in the bronchial tubes. Mulethi thins and loosens the mucus inside the airways, this eases coughing and congestion,4.Tulsi is an immunomodulatory and anti-stress effect,which makes it useful in the treatment of AIDS.It also has antiviral properties,due to which it is useful against HIV as well,4.Tulsi has anti oxidant,anti-bacterial,analgesic(pain-relieving) properties and is vermifuge(expels worm from the system),Holy basil is an adaptogen and contains several nutrients, including vitamins A and C, calcium, iron, and zinc.When using herbal medicine, it is important to make informed decisions. A healthcare professional, such as a registered dietitian, pharmacist, or healthcare provider can help review and individualize your supplement use to be sure it is safe and supports your health needs,5.Punarnava posesses anti-arithritic and anti-stress properties.It is recommended as a chief herb for the treatment of kidney stones.,6.Along with AIDS,it provides relief from many other health conditions such as piles,diarrhoea,mouth ulcers and liver disorders,take as per physician's directions,7.Guduchi enhances the phagocytic activity and stimulates the function of macrophages in the body.It is also used in treating anaemia,jaundice,tb,persistent malarial fever & diabetes,8.It also helps treat herpes,hyperacidity,dysentry,fever,impotence and other health conditions.",
      imageUrl: "https://cdn1.byjus.com/wp-content/uploads/2016/07/128.png",
    },
    {
      id: "9",
      department: "Vajikaran(Sexology)",
      disease: "Genital herpes",
      therapy: "Raktamokshan(leech therapy)",
      therapy_elaborate:
        "It involves the removal of toxic blood from the body,which makes it an effective therapy when the predominant cause of visarpa is the vitation of rakta.Skin diseases such as herpes are mainly caused due to vitiation of pitta dosha.Raktamokshana helps in removal of the aggrevated pitta and balances the imbalanced doshas in the body,thereby,helping in the treatment of visarpa and other skin diseases.",
      medicine: "Neem,Yastimadhu,Haritaki,Giloy,Bosewellia,Manjishtha",
      description:
        "1.Azadirachta indica, commonly known as neem in India, is also called ‘Margosa’ or ‘Indian Lilac’. It is the most versatile, diverse (different varieties of species) tree in the tropical region (hot regions), that might have medicinal potential. Neem has a lot of beneficial non-wood products like flowers, leaves, fruits, bark, gum, oil, seeds, and neem cake (residue left over after oil is pressed from neem seeds). It is thus considered the most useful tree in comparison to all other tree species,2.Yashtimadhu is a tall perennial plant commonly known as Liquorice or Sweetwood. The whole herb is said to have high medicinal value. The name Yashtimadhu indicates that its stem is sweet in taste. Glycyrrhiza glabra is named so because “Glykas” means sweet, “rhiza” means root and “glabra” means smooth and hairless,3.Prized as the “King Of Medicines”, Haritaki is a miraculous ayurvedic fruit that is extensively used for a wide range of traditional remedies. Cultivated from the seeds of Terminalia chebula tree, it is popularly known as Indian walnut for its innumerable benefits or Indian hog plum in English,4.Giloy, also known as Amrita or Guduchi in Hindi, is an herb that helps improve digestion and boost immunity. It has heart-shaped leaves that resemble betel leaves. All parts of the plant are used in Ayurvedic medicine. However, the stem is thought to have the most beneficial compounds.Giloy is Titka (bitter) in taste and Ushna (hot) in potency. After metabolization, it becomes Madhura (sweet) and Guru (heavy) in nature. It has Deepan (appetizer) and Pachan (digestive) properties which help in improving digestion,5.Due to its potential anti-inflammatory properties, boswellia may help with inflammatory conditions, such as rheumatoid arthritis, inflammatory bowel disease, and asthma. The treatments for these conditions tend to revolve around reducing inflammation. By helping control inflammation, boswellia may minimize the symptoms of these conditions.Boswellia serrata is a tree prevalent in India, the Middle East and North Africa. The gummy exudate or resin obtained by peeling away the bark is commonly known as frankincense or olibanum,6.In ayurvedic medicine, Manjistha is a blood purifying herb. It cools and detoxifies the blood, removes stagnant blood, and dissolves obstructions in the blood flow. Manjistha also helps protect gums from receding. It is also believed to have astringent and anti-oxidant properties.",
      use: "1.Neem is very effective in training in treating Herpes infection by acting as an effective antiviral and antibacterial agent.Helps to avoid complications.Neem acts as a antioxidant as well.Helps to stop nerve damage caused by virus and superadded bacterial infection,2.It is very effective in relieving itching,burning,rashes and blisters.It acts as an antioxidant as well as immounobooster.Glycyrrhizin is a chemical constituent present in this herb,which is scientifically proven to act against DNA and RNA viruses including HZV,HSV,3.This dried fruit often termed as Chebulic myrobalan is one of the three musketeers that constitute the potent rejuvenative Triphala formulation. The holistic science of Ayurveda strongly advocates the uses of haritaki due to its potent laxative, astringent, purgative, anti-bilious and anti-oxidant properties for treating numerous health anomalies.It is a very good antioxididing agent,antiinflammatory,antiallergic,digestive herb,very effective in viral and bacterial infections.Thus it helps in reducing rashes ,nervine pain,blisters and burning sensation,4.Giloy juice helps to maintain overall health. According to Ayurveda, Giloy can help control high blood pressure due to digestive problems. Giloy improves metabolism and helps maintain a good digestive system. This helps reduce the risk of high blood pressure levels.It is a proven best antiviral herbs as well as it helps to raise immunity.Very effective to decrease pitta to help in burning sensation and all flu like symptoms,especially,in first few days of infection,5.Boswellia is used widely in Ayurveda for treating arthritis, ulcerative colitis, coughs, sores, wound healing, and asthma.Helps in reducing inflammation and pain.Do not take boswellia if you are pregnant or breastfeeding. Boswellia may inhibit the liver enzymes that break down drugs, which can increase the drug effects. Avoid taking boswellia concurrently with other medications unless specifically prescribed by your physician,6.Manjistha or Indian Madder is considered to be one of the best blood-purifying herbs. It is mainly used to break down blockages in the blood flow and remove stagnant blood. Manjistha herb can be used both internally and externally on skin for promoting skin whitening.Acts as an antiviral agent,helps in reducing nerve pain and detoxication of body.",
      imageUrl:
        "https://www.chemistclick.co.uk/uploads/news/image/1653471860_picture%20of%20genital%20herpes.jpg",
    },
    {
      id: "10",
      department: "Vajikaran(Sexology)",
      disease: "Trichomoniasis",
      therapy: "Sthanik Chikitsa",
      therapy_elaborate:
        "This is one of the simplest Sthanik chikitsa that gives the continuous drug delivery to the target organ and there is that there is no need of sophisticated instruments and trained expert rather than patient can do itself after little instruction.Pichu is made up of cotton swab wrapped with gauze piece and tied with long thread it should be immersed in medicated oil or liquid oil are mostly prepared due to its retention ability circular and elongated Pichu is used for shallow and deep insertion inside vagina respectively. Mode of action depending upon the medicine used as different medicines have different mode of action",
      medicine: "Haridra,Aragwadha,Guduchi,Nimba,Karanja,Amalaki",
      description:
        "1.Turmeric or Curcuma longa, is a flowering plant in the ginger family Zingiberaceae. It is a perennial, rhizomatous, herbaceous plant native to the Indian subcontinent and Southeast Asia that requires temperatures between 20 and 30 °C and high annual rainfall to thrive,2.Aragwadha is commonly known as ‘Purging casia’ owing to it’s purgative action. Aragwadha is one of the most widely used herb in Ayurveda. The name Aragwadha itself means that the plant can completely cure many ailments. The species name of the plant, “fistula” indicates the cylindrical pod fruits. Aragwadha is one of the most commonly used herb for the treatment of skin allergic conditions,3.Guduchi, scientifically known as Tinospora cordifolia, is a vital remedy in the Indian system of medicine. It belongs to the Menispermaceae family and has been used as a medicament since ancient times. It is also known as Giloy, Amrita or Indian bitter. It is found in dense and dry forests all over India, growing over small trees and bushes at high altitudes. The stem, roots and leaves of Guduchi all have medicinal properties,5.Azadirachta indica, commonly known as neem in India, is also called ‘Margosa’ or ‘Indian Lilac’. It is the most versatile, diverse (different varieties of species) tree in the tropical region (hot regions), that might have medicinal potential. Neem has a lot of beneficial non-wood products like flowers, leaves, fruits, bark, gum, oil, seeds, and neem cake (residue left over after oil is pressed from neem seeds). It is thus considered the most useful tree in comparison to all other tree species,6.Karanja is a medicinal herb mainly used for skin disorders. All parts of Karanja tree (roots, flowers, leaves, bark) are used for medicinal purposes.Karanja is widely used in managing constipation as it helps to improve gut motility and has a laxative property. It might also be used for piles due to its astringent and anti-inflammatory properties,7.Ayurvedic practitioners also believe amalaki improves functioning of the liver, heart, brain, and lungs. Although the efficacy of amalaki for treating these conditions in particular has not been proven, the fruit has been studied as a treatment for heartburn, high cholesterol, and diabetes.",
      use: "1.Trichomoniasis is usually treated quickly and easily with antibiotics. Most people are prescribed an antibiotic called haridra(turmeric), which is very effective if taken correctly. You'll usually have to take haridra twice a day with lukewarm water, for 5 to 7 days. Sometimes this antibiotic can be prescribed in a single, larger dose,2.The leaves of Aragvadhadi are fried in mustard oil and taken in the evening followed by a meal. It alleviates Trichomaniasis or Aragvadha in the dose of 40 gm should be taken with the juice of sugarcane it is helpful in alleviating trichomaniasis,3.Clinical studies have shown that Guduchi is useful in relieving symptoms of post-menopausal issues without any side effects. It is suggested that it may be an alternative to hormone replacement therapy.The starch obtained from the stem known as 'Guduchi-satva' is highly nutritive and digestive and used in many diseases.,5.All parts of the neem tree- leaves, flowers, seeds, fruits, roots and bark have been used traditionally for the treatment of inflammation, infections, fever, skin diseases and dental disorders,6.According to Ayurveda, Karanja oil is mainly applied on the skin to manage boils and eczema as well as heal wounds due to its Ropan (healing) and antimicrobial property. The paste of its leaves can also be applied on cuts and wounds to help promote healing.The Ayurvedic doctor may also suggest a number of immunity-boosting medicines, such as Neem capsules or Ashwashila capsules in sexually transmitted diseases(trichomoniasis) treatment . Other herbal medicines that are created for deeper rooted issues may also be able to help in the problem,7.Amla is rich in vitamin C and has antioxidant, anti-inflammatory and antibiotic properties. Consuming amla or its juice enhances immunity. For the treatment of vaginal discharge, take one teaspoonful of amla powder with a glass of water once daily.",
      imageUrl:
        "https://images.medindia.net/amp-images/patientinfo/trichomoniasis.jpg",
    },
  ];
  return (
    <SafeAreaView style={{ marginHorizontal: 20, marginBottom: 50 }}>
      <View style={{ height: 50 }}>
        <Appbar
          title={item.department}
          color={COLORS.white}
          icon={"search1"}
          color1={COLORS.white}
          onPress={() => navigation.goBack()}
          onPressSearch={() => navigation.navigate("Search")}
        />
      </View>
      <FlatList
        data={Sexology}
        showsVerticalScrollIndicator={false}
        keyExtractor={(item) => item.id}
        contentContainerStyle={{ columnGap: SIZES.small }}
        renderItem={({ item }) => (
          <View style={{ marginBottom: 10 }}>
            <MedicineTile
              item={item}
              onPress={() => navigation.navigate("Departmentdetails", { item })}
            />
          </View>
        )}
      />
    </SafeAreaView>
  );
};

export default Sexology;

const styles = StyleSheet.create({});
