import { FlatList, StyleSheet, Text, View } from "react-native";
import React from "react";
import { useRoute } from "@react-navigation/native";
import { COLORS, SIZES } from "../../constants/themes";
import Appbar from "../../components/Reuseable/Appbar";
import { SafeAreaView } from "react-native-safe-area-context";
import MedicineTile from "../../components/Reuseable/MedicineTile";

const Surgery = ({ navigation }) => {
  const route = useRoute();
  const { item } = route.params;
  const Surgery = [
    {
      id: "1",
      department: "Shalakya Tantra(Surgery)",
      disease: "Anal Fissures",
      therapy: "Khara Sutra Therapy",
      therapy_elaborate:
        "Patients recuperate within only 3 to 5 days and in that respect is no demand facing pharmaceutic drugs that can power strict side effects. The therapy is regarded as a workable choice to ancient counsel, with studies screening a return pace as gross as 3.33% compared to the 26% return rate associated with ancient surgical procedures. yet, it is desirable to survey such manipulation alone in a reputed hospital with a marvelous operating surgeon who is of regular proficiency. The Kshara Sutra Technique is not costly and doesn’t have side effects. It provides a long-term healing process concerning other surgical procedures.For the preparation of thread, surgical linen thread gauge number 20 is manually coated eleven times with the latex of Euphorbia neriifolia, followed by seven coatings of the latex and the alkaline powder of Achyranthus aspera alternatively, and dried. In the final phase, three coatings of latex and powder of Curcuma longa is to be given alternatively.The thread thus prepared is sterilized by ultra violet radiation and placed in a polythene bag or glass tube.",
      medicine: "guggulu,isabgol,sonamukhi,haritiki",
      description:
        "1.Guggul is also known as “Pura” which means “wards off disease”. It is used as a source of commercial “Gum guggul”. The major bioactive component of Guggul is oleo-gum-resin (a mixture of an oil and yellowish or brownish fluid secreted from the plant stem or bark). It is this oleo-gum resin that is said to have therapeutic benefits.Guggul is useful in weight management as it helps to improve metabolism and reduce Ama (toxic remains in the body due to improper digestion) by increasing the digestive fire. It also helps to reduce swelling, pain and stiffness in joints in case of osteoarthritis as well as rheumatoid arthritis due to its anti-inflammatory and anti-arthritic properties. Guggul might also be helpful in managing blood cholesterol levels by lowering total cholesterol, low-density lipoprotein (LDL or bad cholesterol) and triglyceride levels,2.Isabgol also known as psyllium husk is a dietary fiber that helps to increase stool and promote laxation. It is one of the most commonly used home remedies for constipation.Isabgol is good for weight loss as it gives a feeling of fullness and helps prevent overeating. It is also good for diabetic patients as it helps to manage blood glucose levels.Isabgol consumption is good for piles as it makes the stool bulky and prevents constipation. It also reduces the inflammation in piles due to its anti-inflammatory property,3.Senna, or Swarnapatri in Sanskrit, is also known as Indian senna. It is used for various medicinal purposes, including constipation.According to Ayurveda, Senna helps in managing constipation due to its Rechana (laxative) property. Taking a Senna leaf powder along with lukewarm water also helps in managing weight by improving the Agni (digestive fire) and thus digestion due to its Deepan (appetizer) and Usna (hot) property,4.Haritaki is a drupe-like fruit, oval in shape with size varying between 2 – 4.5 cm in length and 1.2 – 2.5 cm in breadth having 5 longitudinal ridges. Depending upon its variety, it turns green – blackish in color when ripens. Haritaki fruit tastes sweet, sour, bitter depending upon its types. There are 7 types of Haritaki: Vijaya, Rohini, Putane, Amruta, Abhaya, Jivanti, Chetak.Haritaki is very nutritious containing essential vitamins, minerals, and proteins. It is a source of vitamin C, manganese, selenian, potassium, iron and copper. It also contains plant chemicals like – tannic acid, gallic acid, palmitic acid, stearic acid and behenic acid.",
      use: "1.By bulking up and increasing moisture content in stools, this type of fiber reduces anal fissure symptoms by decreasing the pressure on the sphincter muscle and improving blood circulation to the region, further giving the fissures a chance to heal. Guggulu is regarded as effective at relieving fissures because of its analgesic, anti-inflammatory, and wound healing properties and is often used in combination with other herbs.Guggul can be taken in the form of powder, tablet or capsule to help reduce the production of sebum which inhibits the growth of acne-causing bacteria due to its antibacterial property.It should be kept in mind that Guggul should always be chewed well before swallowing in order to get the maximum benefits,2.Psyllium husk is a type of soluble fiber that helps generate mucilage, retaining water and helping bulk up stools, allowing for easier bowel movements. This can help relieve both symptoms of diarrhoea and constipation. This type of fiber can also be obtained from lembodi, a herb that is often used as an ingredient in Ayurvedic medicines for fissures, piles, and chronic constipation.sabgol husk can be taken either with warm milk or water preferably before going to bed. It is advisable to avoid excessive consumption of Isabgol as it may lead to complications like abdominal pain, loose stools, diarrhoea etc,3.Anal fissure treatment also includes ayurvedic herbs like Sonamukhi that is regarded as highly effective, especially in cases where constipation is the underlying cause. This herb supports the peristaltic movement of the intestines, easing and improving bowel movements.Applying Senna leaf paste on the skin helps in managing various skin problems like inflammation, blisters, redness etc. due to its Ropan (healing) property.It must be kept in mind that excessive consumption of Senna might cause severe diarrhea and loss of fluid from the body. So, it is advisable to take Senna as recommended by a physician,4.Harda or haritaki is also useful not just for its digestive benefits, but because of its anti-inflammatory effects, which can provide relief from fissures and haemorrhoids. Similarly, nagkesar has a protective effect on the gastrointestinal tract and reduces the risk of infection thanks to its antiseptic properties.During constipation, one should take haritaki in the form of powder with water. To prepare a Haritaki powder, take haritaki fruit, remove the seed and sundry the pill, then take the peel and grind it.",
      imageUrl:
        "https://my.clevelandclinic.org/-/scassets/images/org/health/articles/13177-anal-fissures",
    },
    {
      id: "2",
      department: "Shalakya Tantra(Surgery)",
      disease: "Appendicitis",
      therapy: "Anuvasana & Kashya Vasti(Panchakarma)",
      therapy_elaborate:
        "Anuvasana vasti helps in the overall detoxification of the body. Anuvasana vasti is used for the purification and rejuvenation of the colon. In Appendicitis anuvasna basti with Triphala tailam is recommended to the patients, whereas Kashya vasti means medicated herbal enema. Kashya vasti contains medicated herbs and oils. In Kashya vasti medicine reach your bowels directly without enzymatic actions and its effectiveness is very high.",
      medicine: "Garlic,Lemon,Fenugreek,Mint,ginger",
      description:
        "1.Garlic (Allium sativum) is an herb related to onion, leeks, and chives. It is commonly used for conditions related to the heart and blood system.Garlic produces a chemical called allicin. This is what seems to make garlic work for certain conditions. Allicin also makes garlic smell. Some products are made 'odorless' by aging the garlic, but this process can also change the effects of garlic.People commonly use garlic for high blood pressure, high levels of cholesterol or other fats in the blood, and hardening of the arteries. It is also used for the common cold, osteoarthritis, and many other conditions, but there is no good scientific evidence to support these uses. There is also no good evidence to support using garlic for COVID-19,2.Lemons are a popular fruit that people use in small quantities to add flavor to baked goods, sauces, salad dressings, marinades, drinks, and desserts. However, they rarely consume them alone due to their intense, sour taste.Lemons are a good source of vitamin C. One 58 gram (g) lemon can provide over 30 milligrams(mg) of vitamin C.Vitamin C is essential for health, and a deficiency can lead to health problems,3.Fenugreek (Trigonella foenum-graecum) is an herb similar to clover. The seeds taste similar to maple syrup and are used in foods and medicine.Fenugreek seems to slow sugar absorption in the stomach and stimulate insulin. Both of these effects lower blood sugar in people with diabetes. Fenugreek might also improve levels of testosterone and estrogen, helping to improve interest in sex,4.Mint leaves create a cool sensation in the mouth. Toothpaste, mouthwash, breath mints, and chewing gum are all commonly flavored with mint. There are many varieties of the mint plant, and most fall under the genus mentha. Because mint plants spread quickly, gardeners tend to grow them in containers. When planted directly into the ground, they can become invasive and take over a garden.Mint is perhaps most popularly known as a remedy for digestive problems. Some limited research suggests that peppermint oil in capsules may ease belly pain from irritable bowel syndrome,5.Ginger (Zingiber officinale) is a plant native to Asia. The ginger spice comes from the roots of the plant. It's used as a food flavoring and medicine.Ginger contains chemicals that might reduce nausea and swelling. These chemicals seem to work in the stomach and intestines, but they might also help the brain and nervous system to control nausea. ",
      use: "1.garlic have anti-inflammatory properties can reduced inflammation and pain caused due to appendicitis. Eating 2-3 cloves of garlic on an empty stomach may help to get rid of this problem,2.Drinking water mixed with freshly squeezed lemon and honey may help in indigestion and constipation. It will also provide pain relief affect and boost immunity,3.People commonly use fenugreek for diabetes, menstrual cramps, sexual problems, enlarged prostate, high cholesterol, obesity, and many other conditions, but there is no good scientific evidence to support most of these uses.Fenugreek seeds contain antioxidants and antimicrobial compounds that prevent intestinal waste and excess mucus from storing which boost digestion and reduce the risk of severe pain,4.Mint is perhaps most popularly known as a remedy for digestive problems. Some limited research suggests that peppermint oil in capsules may ease belly pain from irritable bowel syndrome.  Mint leaves is beneficial remedy for appendicitis. It calm the appendicitis symptoms like nausea and vomiting,5.People commonly use ginger for many types of nausea and vomiting. It's also used for menstrual cramps, osteoarthritis, diabetes, migraine headaches, and other conditions, but there is no good scientific evidence to support many of these uses. There is also no good evidence to support using ginger for COVID-19.Drinking ginger tea twice or thrice a day may help to reduce inflammation and pain, and curing symptoms such as nausea and vomiting.",
      imageUrl:
        "https://my.clevelandclinic.org/-/scassets/images/org/health/articles/8095-appendicitis",
    },
    {
      id: "3",
      department: "Shalakya Tantra(Surgery)",
      disease: "Bile Duct Stones",
      therapy: "Apatarpana,langhana & Virechana",
      therapy_elaborate:
        "Meticulously crafted by our Ayurveda experts, this signature treatment comprises various authentic therapies aimed at reducing weight and fostering confidence. Experience the transformation of Apatarpana for a healthier and confident you.A healthy weight is essential for both excellent health and the prevention of some diseases, such as heart disease, joint disease, and hypertension. A healthy weight makes you comfortable and boosts your confidence,Langhana is a body cleansing therapeutic measure that eliminates vitiated Dosha.It may be Dravyabhuta (with medicines) or Adravyabhuta (without medicines) . Autophagy is a recently recognized body cleansing mechanism found to have therapeutic value in certain diseases like cancer.Improves the metabolism and digestive power, removes the blockage from Strotas and tissues, remove Ama (toxin) from the body, brings lightness and feel healthy,whereas Virechana is one of the Panchakarma therapies wherein purgation is induced by drugs and it specifically aims at the elimination of excessive Pitta Dosha from the body. Normally, after Virechanakarma, patient does not complain of having any untoward like those present after diarrhea due to dehydration.Thererfore, Apatarpana (fasting), langhana (light diet), and virechana (mild purgation) are some of the ayurvedic therapeutic procedures that are usually advised as a part of the gallbladder stone removal treatment.",
      medicine: "Ginger,Garlic,Bhumi amla,manjishtha,bhringraj",
      description:
        "1.Ginger (Zingiber officinale) is a plant native to Asia. The ginger spice comes from the roots of the plant. It's used as a food flavoring and medicine.Ginger contains chemicals that might reduce nausea and swelling. These chemicals seem to work in the stomach and intestines, but they might also help the brain and nervous system to control nausea,2.Garlic (Allium sativum) is an herb related to onion, leeks, and chives. It is commonly used for conditions related to the heart and blood system.Garlic produces a chemical called allicin. This is what seems to make garlic work for certain conditions. Allicin also makes garlic smell. Some products are made 'odorless' by aging the garlic, but this process can also change the effects of garlic.People commonly use garlic for high blood pressure, high levels of cholesterol or other fats in the blood, and hardening of the arteries,3.Commonly called “Gale Of The Wind” and scientifically termed Phyllanthus niruri, bhumi amla is a key ingredient in the ayurvedic formulation Chyawanprash where it works to boost immunity and also provides valuable therapeutic properties in its leaves, roots, and other plant parts. These include hepatoprotective, antioxidant, antiviral, to not only enhance liver wellness but also promote digestion, remedy kidney illnesses, enrich skin texture and uplift all-round health,4.In ayurvedic medicine, Manjistha is a blood purifying herb. It cools and detoxifies the blood, removes stagnant blood, and dissolves obstructions in the blood flow. Manjistha also helps protect gums from receding. It is also believed to have astringent and anti-oxidant properties.The fruit is round and fleshy. It grows up to 1.5m in height and has perennial leaves. The Manjistha roots have brownish red bark and are used to produce a red dye. The parts of the herb that are beneficial to us are stems and roots,5.Bhringraj is also known as Kesharaj which means “Ruler of the hair”. It is rich in proteins, vitamins and antioxidants which help protect the body against certain infections.According to Ayurveda, Bhringraj juice rejuvenates the skin and thereby helps reduce the signs of aging such as fine lines, wrinkles and patchy skin due to its anti-aging property. Bhringraj powder along with a carrier oil (like coconut oil) can also be used to manage skin infections and allergies due to its antimicrobial property.",
      use: "1.People commonly use ginger for many types of nausea and vomiting. It's also used for menstrual cramps, osteoarthritis, diabetes, migraine headaches, and other conditions, but there is no good scientific evidence to support many of these uses. There is also no good evidence to support using ginger for COVID-19. Another choleretic herb that stimulates the gallbladder and liver functions, improves digestion, and reduces nausea and vomiting,2.Garlic is also used for the common cold, osteoarthritis, and many other conditions, but there is no good scientific evidence to support these uses. There is also no good evidence to support using garlic for COVID-19.A cholagogue herb that contracts the gallbladder to expel excess bile and stones into the intestines, while also possessing antibacterial and antiviral properties,3.The leaves of bhumi amla are used to prepare medicinal tonics, pastes and powders, aside from the whole plant that is used for remedial purposes.Imbued with these bioactive components exhibiting anti-inflammatory, hepatoprotective, antibacterial, analgesic, antioxidant, astringent, anti-ulcer, respiratory issues like cough, cold and fever, gastrointestinal problems, skin infections, wounds and burns.Dissolves gallstones, reduces inflammation, and heals the liver and gallbladder tissues, with added antiviral and antibacterial properties,4.This is the primary function of manjistha herb is the purification of blood. Purified blood is necessary to have good skin and hair. Manjistha is a great blood purifier. It cleanses the blood and removes all toxins from it. Helps your body to purify the blood, removes toxins, and reduces inflammation, thereby regulating the Pitta dosha and balancing the digestive fire,5.Taking Bhringraj leaves in the powdered form increases the production of urine due to its diuretic property and therefore helps to manage urinary complications. Bhringraj is also beneficial in managing the symptoms of gastrointestinal disorders (such as diarrhea and dysentery) like contractions or spasms in the stomach, intestine or urinary bladder due to its antispasmodic property.Improves bilious flow in the liver and acts as an excellent appetizer, digestive agent, and liver stimulant, while alleviating Vata.",
      imageUrl:
        "https://assets.mayoclinic.org/content/dam/media/en/images/2023/02/08/gallstones.jpg",
    },
    {
      id: "4",
      department: "Shalakya Tantra(Surgery)",
      disease: "Constipation",
      therapy: "Virechana & Basti",
      therapy_elaborate:
        "This therapy involves administering herbal laxatives to evacuate the bowel, eliminate toxins from the GI tract and treat the ailments caused by elevated Pitta dosha, whereas This therapy involves administering a herbal enema into the rectum to clear the colon. Although this technique is ‌used to treat vitiated vata dosha, it's an essential step in panchakarma treatment for gut cleansing and detox. The therapy is minimally invasive and mostly painless.",
      medicine: "Swarnapatri,Fenugreek(Methi),Isabgol,Amla,Aragwadha",
      description:
        "1.Senna, or Swarnapatri in Sanskrit, is also known as Indian senna. It is used for various medicinal purposes, including constipation.According to Ayurveda, Senna helps in managing constipation due to its Rechana (laxative) property. Taking a Senna leaf powder along with lukewarm water also helps in managing weight by improving the Agni (digestive fire) and thus digestion due to its Deepan (appetizer) and Usna (hot) property.Senna helps in managing blood sugar levels by increasing the insulin production due to its antioxidant property. It also helps to remove worms from the intestine due to its anthelmintic property,2.Fenugreek (Trigonella foenum-graecum) is an herb similar to clover. The seeds taste similar to maple syrup and are used in foods and medicine. Fenugreek seems to slow sugar absorption in the stomach and stimulate insulin. Both of these effects lower blood sugar in people with diabetes. Fenugreek might also improve levels of testosterone and estrogen, helping to improve interest in sex,3.Isabgol also known as psyllium husk is a dietary fiber that helps to increase stool and promote laxation. It is one of the most commonly used home remedies for constipation.Isabgol is good for weight loss as it gives a feeling of fullness and helps prevent overeating. It is also good for diabetic patients as it helps to manage blood glucose levels.Isabgol consumption is good for piles as it makes the stool bulky and prevents constipation. It also reduces the inflammation in piles due to its anti-inflammatory property,4.Amla, also known as Indian gooseberries, grows on a flowering tree of the same name. The small berries are round and bright or yellow-green. Though they are quite sour on their own, their flavor can enhance recipes they’re added to.The antioxidants and vitamins found in amla berries offer several health benefits. High concentrations of vitamin C in amla helps the body recover from illness. Amla berries also include several flavonols, chemicals that have been linked to benefits like improved memory,5.A medium sized tree with brilliant yellow flowers growing at roadside and gardens. Long cylindrical pods of the tree are used in Ayurveda.Pods contain glucoside rhein and an anthraquinone, fistulic acid. Leaves contain glucosides which have been identified as senoside A & B. The stem bark contained tannins, lupeol, b-sitosterol and hexacosanol.",
      use: "1.Applying Senna leaf paste on the skin helps in managing various skin problems like inflammation, blisters, redness etc. due to its Ropan (healing) property.It must be kept in mind that excessive consumption of Senna might cause severe diarrhea and loss of fluid from the body. So, it is advisable to take Senna as recommended by a physician.Swarnapatri or Senna is used in many Ayurveda formulations because of its rechana or laxative property. It balances Vata and promotes Pitta. It is a strong laxative and hence should be used with caution,2.People commonly use fenugreek for diabetes, menstrual cramps, sexual problems, enlarged prostate, high cholesterol, obesity, and many other conditions, but there is no good scientific evidence to support most of these uses.Fenugreek or methi seeds are good for preventing constipation because of the high amount of soluble fibers. It is best for Kapha type of constipation. People with high Pitta should avoid it,3.Isabgol, when applied to the skin along with aloe vera gel, helps in managing acne and pimples due to its anti-inflammatory property.Isabgol husk can be taken either with warm milk or water preferably before going to bed. It is advisable to avoid excessive consumption of Isabgol as it may lead to complications like abdominal pain, loose stools, diarrhoea etc.Psyllium husk is guru or heavy and adds bulk to the stools. It also has a mild laxative property that relieves constipation,4.The soluble fiber in amla berries dissolves quickly in the body, which helps to slow the rate your body absorbs sugar. This can help reduce blood sugar spikes. Amla berries also have a positive effect on blood glucose and lipid counts in people with type 2 diabetes.The fiber in amla berries helps the body regulate bowel movements and may help to relieve symptoms from conditions like irritable bowel syndrome.Because of the high amount of fiber, Amla can help ease constipation. However, consuming it in large quantities can worsen constipation, so you should consume it in limited quantities,5.Bark of the Aragvadha is extensively used by Ayurveda in India in the treatment of inflammatory swellings and as a cleaning agent for ulcers and wounds. It is believed to decrease purulent discharge and act as a local antiseptic. The fruits are also used as a laxative. Aragvadha is considered to maintain the balance of water content in the bowel mass to ensure smooth defecation.",
      imageUrl:
        "https://cdn.sanity.io/images/0b678gck/buoy-public-site/57de3eecc4b23b74aa7e4bf913ca4b2f60c3983e-4168x4168.jpg?w=768&q=70&auto=format&dpr=1",
    },
    {
      id: "5",
      department: "Shalakya Tantra(Surgery)",
      disease: "Gastroesophageal Reflux",
      therapy: "Supta Baddha Konasana (Reclining Bound Angle)",
      therapy_elaborate:
        "Sit on your mat with your knees bent and feet together, allowing your knees to fall open to the sides.Lie back and support your knees with blocks or folded blankets to find a comfortable hip opening.Rest your arms alongside your body with your palms facing up.Close your eyes and take slow, deep breaths, surrendering to the gentle opening of the hips and inner thighs.Stay in this pose for 5-10 minutes.For support, you can place additional props under your knees, hips, or head.",
      medicine: "Tulsi,Elaichi,Ash Gourd,Ghrit Kumari",
      description:
        "1.Also known as Holy Basil, Tulsi is an excellent natural remedy for a host of stomach-related woes, including GERD. The leaves of this sacred plant are imbued with volatile oils that portray strong carminative traits, to relieve flatulence, gas and hyperacidity,2.Cardamom or elaichi is rich in B vitamins, antioxidants, which boost metabolism in the system and facilitate smooth digestion processes. The aromatic pods also help reduce nausea, bloating and bitter taste in the mouth which often occur during instances of GERD.3.Ash gourd is a wholesome green vegetable that not only has a high water content but is also laden with valuable phytonutrients – terpenes, flavonoids, which considerably decrease acid levels in the gut and help avert nausea, vomiting, constipation,4.Known as Ghrit Kumari as per the Ayurvedic terminology in Sanskrit, aloe vera is a marvellous panacea for umpteen health conditions, including GERD. The leaves of the aloe plant secrete a liquid gel which contains vast reserves of antioxidant and anti-inflammatory compounds, that neutralize stomach acids, heal peptic ulcers and ease heartburn.",
      use: "1.After a full meal at breakfast, lunch or dinner, sip on a cup of hot tulsi tea to enhance digestion and pacify burning sensations in the gut,2.Chew on some elaichi/cardamom pods after ingesting food, to activate the digestive juices and assist in proper assimilation of nutrients within the system,3.Drink a glass of ash gourd juice in the morning to augment digestive functions, ease acid reflux and heartburn, to effectively manage GERD,4.Having a glass of aloe vera juice along with meals uplifts digestion and treats acid reflux and GERD, for better gut health.",
      imageUrl: "https://ghshospital.org/wp-content/uploads/2021/09/Gerd.jpg",
    },
    {
      id: "6",
      department: "Shalakya Tantra(Surgery)",
      disease: "Hemorrhoids",
      therapy: "Panchakarma Therapy",
      therapy_elaborate:
        "It is a purification process that removes skin toxins from the body and restores the balance of the body energies, involves five procedures, namely vamana, Virechana, Nasya, Basti and Taktamokshana.This therapy can help improve circulation reduce inflammation and promote the regeneration of damaged tissues.Ayurvedic therapies like Sits baths and Panchakarma can be highly beneficial in the treatment of Piles. These therapies are non-invasive and offer lasting relief.",
      medicine: "Touch-me-not plant,Triphala,Guggul,Turmeric",
      description:
        "1.Touch-me-not herb has long been known for its healing properties to help manage bleeding piles. In addition, the plant contains a chemical known as alkaloid mimosine, which can help ease pain and manage inflammation.Since ancient times, Ayurvedic practitioners and Vaidyas have suggested using touch-me-not plants for piles,2.Triphala churna has analgesic, antibacterial, anti-arthritic, hypoglycemic, antiaging, antiviral and anti-inflammatory properties. It helps with headaches, dyspepsia, fatigue, oxidative stress reduction, and infectious disorders like tuberculosis, and periodontal disease.It is a rich source of antioxidants such as vitamin C which helps in building immunity. Taking Triphala supplements on an empty stomach before bed can be beneficial for internal cleansing due to its detoxifying property. Triphala churna also helps in weight loss as it shows significant reduction in energy intake and body fat,3.Guggul is also known as “Pura” which means “wards off disease”. It is used as a source of commercial “Gum guggul”. The major bioactive component of Guggul is oleo-gum-resin (a mixture of an oil and yellowish or brownish fluid secreted from the plant stem or bark). It is this oleo-gum resin that is said to have therapeutic benefits.According to Ayurveda, Guggul is useful in weight management as it helps to improve metabolism and reduce Ama (toxic remains in the body due to improper digestion) by increasing the digestive fire. It also helps to reduce swelling, pain and stiffness in joints in case of osteoarthritis as well as rheumatoid arthritis due to its anti-inflammatory and anti-arthritic properties.Guggul might also be helpful in managing blood cholesterol levels by lowering total cholesterol, low-density lipoprotein (LDL or bad cholesterol) and triglyceride levels,4.Turmeric (also known as Haldi) is a common ingredient in most Indian households. With its significant health benefits, it finds a range of cosmetic, religious, and healthcare uses, and managing piles is one of them.Turmeric is an antimicrobial and anti-inflammatory herb that can prevent the attack of secondary microbial infection and manage bleeding because of haemorrhoids.",
      use: "1.For best results, a paste of touch-me-not leaves can be applied externally to the affected area. Kerala Ayurveda Pilogest capsules have the goodness of touch-me-not and other herbs that provide relief, and even prevent such concerns from cropping up,2.A paste of Triphala and coconut oil can be applied on the face to improve the skin texture and enhance skin elasticity due to its anti-aging property. Triphala is also considered good for the eyes due to its antioxidant activity which helps improve eye health. Triphala helps to control hair fall and promotes hair growth when applied on the scalp due to the presence of vitamin C.Triphala is safe for all skin types but if you have dry skin, it is advisable to use Triphala with coconut oil. Excessive intake of Triphala might cause diarrhea.By using Triphala for piles, one can find lasting relief. Triphala is a healthy mix of three potent herbs: Amalaki, Bhibhitaki and Haritaki. The composition of Triphala is such that it acts as an excellent ingredient for constipation relief. When you have a smooth evacuation, the chances of straining and piles reduce significantly,3.Guggul can be taken in the form of powder, tablet or capsule to help reduce the production of sebum which inhibits the growth of acne-causing bacteria due to its antibacterial property.Applying a paste of Guggul mixed in warm water on the joints helps to reduce joint pain.It should be kept in mind that Guggul should always be chewed well before swallowing in order to get the maximum benefits,Guggul is one of Ayurveda's most potent anti-inflammatory herbs. Also known as Balsamodendron Mukul, Guggul helps reduce inflammation, manages hemorrhoidal concerns, and can provide quick and lasting relief from piles.Being a laxative and an astringent agent, Guggul can help metabolise the bioactive etiologic components of haemorrhoids. This helps eliminate toxins (Ama) and improve digestive health,4.Apart from that, it can also help reduce anal itching urges. Ayurveda suggests that turmeric has an alkaline nature and can have an astringent effect that can help shrink haemorrhoids. In addition, by improving the digestive fire (Agni), Turmeric helps improve digestion and prevent haemorrhoids.",
      imageUrl:
        "https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2013/08/26/10/25/ds00096_im01772_r7_hemorrhoidsthu_jpg.jpg",
    },
    {
      id: "7",
      department: "Shalakya Tantra(Surgery)",
      disease: "Peptic Ulcer",
      therapy: "Basti Therapy",
      therapy_elaborate:
        "This therapy involves administering a herbal enema into the rectum to clear the colon. Although this technique is ‌used to treat vitiated vata dosha, it's an essential step in panchakarma treatment for gut cleansing and detox. The therapy is minimally invasive and mostly painless.Basti is a procedure wherein the medicated oil/kashayam/fluid which is given through the anal route gets absorbed in the intestine with simultaneous action of the medicines which are there in the oil or decoction given.It nourishes the body, pacifies the vata and allied dosha in the body.It is a varied type according to pathology of the disease in an individual. The doshas from all over body are initially bought into abdomen by Therapeutic ayurvedic abhyangam and swedan i.e. massage and steam, after that they are expelled through the basti treatment.Basti treatments balance and nurture Vata dosha. When Vata usually functions, it helps bring toxins and waste matter out of the dhatus( body cells) and eliminates them. Basti has two actions, expelling the vitiated doshas ( morbid substances/toxins) and nourishing the body.Typically, Basti treatments are not considered painful. However, if the practitioner feels that based on the condition of the patient some pain might be possible, then he can administer a sedative to ease the pain.",
      medicine: "Mulethi,Amla,Rose,Giloy,Coconut",
      description:
        "1.Typically, Basti treatments are not considered painful. However, if the practitioner feels that based on the condition of the patient some pain might be possible, then he can administer a sedative to ease the pain.Mulethi has been found to have antiviral and antibacterial properties. These properties may contribute to its ability to combat infections in the throat, helping to alleviate symptoms of a sore throat caused by viral or bacterial infections,2.Amla, also known as Indian gooseberries, grows on a flowering tree of the same name. The small berries are round and bright or yellow-green. Though they are quite sour on their own, their flavor can enhance recipes they’re added to.While we can't be entirely sure when Ayurvedic healers started using amla berry, historical records tell us they’ve been used in remedies for at least 1,000 years.The antioxidants and vitamins found in amla berries offer several health benefits. High concentrations of vitamin C in amla helps the body recover from illness. Amla berries also include several flavonols, chemicals that have been linked to benefits like improved memory,3.Roses are more than just a sweet-smelling flower in Ayurveda. Celebrated for their balancing influence on the heart, mind, and emotions, roses are used in everything from herbal supplements and teas to aroma blends, massage oils, and delicious recipes.Rose petals are considered cooling in Ayurveda, and are therefore excellent for balancing PITTA DOSHA, the mind-body energy associated with fire and water. Pitta governs all heat in the environment (the hot sun, warm weather) and the body (your digestive fire and metabolism). When Pitta predominates outside or within, roses can help you restore balance,4.Giloy, also known as Amrita or Guduchi in Hindi, is an herb that helps improve digestion and boost immunity. It has heart-shaped leaves that resemble betel leaves. All parts of the plant are used in Ayurvedic medicine. However, the stem is thought to have the most beneficial compounds,5.Coconut is primarily grown in the coastal subtropical zones of Asia and Oceania, its region of origin, on small family farms. The nuts, which are available all year round, are consumed in the region in the form of coconut milk. They are also used to produce copra and its by-product, copra oil.",
      use: "1.Licorice is very affected in sore throat and due to its expectorant properties, it is also used in bronchitis, throat irritations. It can loosen the mucus present in the chest for easing to coughing it out.Due to the Sita potency, licorice is effective in stomach ulcers. In the mechanism of ulcer prevention, when the licorice is taken, it provides a thick coating mucus lining which further helps in reliving from ulcer irritation. Licorice root extract is rich in Glycyrrhetinic acid which is a potent anti-inflammatory agent, and this helps reduce pain and stomach inflammation,2.The fiber in amla berries helps the body regulate bowel movements and may help to relieve symptoms from conditions like irritable bowel syndrome. High levels of vitamin C in Amla berries helps your body absorb other nutrients, so they may be helpful if you take iron and other mineral supplements.Amla can be used for the management of dementia, Alzheimer's disease and Parkinson's disease due to its anti-cholinesterase activity. Amla also has antioxidant and anti-inflammatory property. It fights against free radicals and inhibits the inflammatory mediators to reduce brain damage and improve cognitive function,3.Both cooling and calming, rose is regarded in Ayurvedic medicine as the most essential flower for reducing excess heat associated with fiery pitta dosha. It also soothes the nervous energy that oftentimes accompanies vata dosha and even purifies oily kapha type skin.Rose flowers have been increasingly used for treatments for peptic ulcers because of its healing impact on the stomach ulcers and the irritations caused by stomach ulcers,4.The bitter taste of Giloy may help manage blood glucose levels in diabetic patients. Giloy also helps in weight management by improving overall metabolism.Drinking fresh Giloy juice helps to improve immunity and can be used to manage fevers due to its antipyretic activity. It also increases platelet count and might help in dengue fever.Giloy powder, Kadha (tea), or tablets can also be used for various skin problems as it helps to remove toxins from the body,5.Coconut has the ability to kill the bacteria that are responsible for the cause of stomach ulcers due to its anti-bacterial properties.It is used as an essential ingredient to treat the ulcer related symptoms.",
      imageUrl:
        "https://www.mayoclinic.org/-/media/kcms/gbs/patient-consumer/images/2013/11/15/17/42/ds00242_-ds00958_im02752_r7_ulcersthu_jpg.jpg",
    },
    {
      id: "8",
      department: "Shalakya Tantra(Surgery)",
      disease: "Small Intestine Tumors",
      therapy: "Kalpa Chikitsa",
      therapy_elaborate:
        "Ayurveda kalpa chikitsa is a distinctive approach of therapy, where a specific drug is administered in a gradually increasing dose and decrease inverse order to the level of the initial dose.The Kalpa chikitsa is a unique approach of therapy, where a specific drug is administered in a gradually increasing dose is tapered in the invorse order of the increased dose to the level of initial dose. During this period the patient is kept on suitable specific cereal or non-cereal diet.Kalpa is a unique and patented line of treatment developed by Muniyal Ayurveda for treating chronic disorders. It is a combination of several ayurvedic procedures, proprietary and classical ayurvedic medicines manufactured by the company which is patient specific.",
      medicine: "Ghrit Kumari,Turmeric,Ashwagandha,Garlic",
      description:
        "1.It is because Aloe is believed to bring back youthful energy and femininity. Aloe is used as a tonic for the female reproductive system, skin and hair. According to Ayurveda, Aloe is said to have clarifying, tonic, rejuvenating, purgative, and anti-inflammatory actions.Aloe vera gel has healing and moisturizing properties and is best to provide the dry skin with the much needed hydration. Exfoliating the skin is important to get rid of dead cells and clear pores of grime. It's an all-natural and gentle way to exfoliate your skin,2.Turmeric is a common spice that comes from the root of Curcuma longa. It contains a chemical called curcumin, which might reduce swelling.Turmeric has a warm, bitter taste and is frequently used to flavor or color curry powders, mustards, butters, and cheeses. Because curcumin and other chemicals in turmeric might decrease swelling, it is often used to treat conditions that involve pain and inflammation,3.Ashwagandha is an evergreen shrub that grows in Asia and Africa. It is commonly used for stress. There is little evidence for its use as an 'adaptogen',Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system.Since ashwagandha is traditionally used as an adaptogen, it is used for many conditions related to stress. Adaptogens are believed to help the body resist physical and mental stress. Some of the conditions it is used for include insomnia, aging, anxiety and many others, but there is no good scientific evidence to support most of these uses,4.Garlic (Allium sativum) is an herb related to onion, leeks, and chives. It is commonly used for conditions related to the heart and blood system.Garlic produces a chemical called allicin. This is what seems to make garlic work for certain conditions. Allicin also makes garlic smell. Some products are made 'odorless' by aging the garlic, but this process can also change the effects of garlic.People commonly use garlic for high blood pressure, high levels of cholesterol or other fats in the blood, and hardening of the arteries. It is also used for the common cold, osteoarthritis, and many other conditions, but there is no good scientific evidence to support these uses. There is also no good evidence to support using garlic for COVID-19.",
      use: "1.One of the most effective uses of Aloe vera gel is to manage various skin problems like acne and blemishes. Aloe vera is also good for controlling dandruff and hair loss. Aloe vera juice when taken orally helps reduce constipation due to its laxative property. Aloe vera juice is also used to lose weight and manage diabetes.It is advisable to avoid Aloe vera during pregnancy as it may increase uterine contractions which may lead to a miscarriage. In some cases, Aloe vera might cause stomach pain, diarrhea, and skin irritations.Consuming Aloe Vera is another useful technique. It cleans the digestive tract and colon region by removing harmful toxins and can thus help to cure cancer faster,2.People commonly use turmeric for osteoarthritis. It is also used for hay fever, depression, high cholesterol, a type of liver disease, and itching, but there is no good scientific evidence to support most of these uses. There is also no good evidence to support using turmeric for COVID-19.Researchers are looking into its potential role in the prevention of cancer and other diseases as well. Turmeric is also rich in vitamin C, vitamin B6, and other antioxidants that reduce the risk of serious health conditions like heart disease and diabetes.Turmeric is also very potent in fighting cancer. It contains curcumins which can destroy the cancer cells formed in the colon region,4.Ashwagandha contains chemicals that might help calm the brain, reduce swelling, lower blood pressure, and alter the immune system. Since ashwagandha is traditionally used as an adaptogen, it is used for many conditions related to stress. Adaptogens are believed to help the body resist physical and mental stress.Results from several clinical trials suggest that ashwagandha extracts may help reduce stress and anxiety. A 2021 systematic review identified seven studies investigating ashwagandha to treat stress and anxiety,Ashwagandha is known to have certain properties that can control the growth of cancer cells and is thus instrumental in treating colon cancer,4.The juice of garlic has certain medicinal properties that can combat the growth of cancer cells in your colon region. Intake of garlic juice can thus be very helpful.",
      imageUrl:
        "https://img.freepik.com/free-vector/colorectal-cancer-crc-infographic-education_1308-47971.jpg?size=626&ext=jpg&ga=GA1.1.1412446893.1705017600&semt=ais",
    },
    {
      id: "9",
      department: "Shalakya Tantra(Surgery)",
      disease: "Broken bone repair",
      therapy: "Purva Karma & Snehana Karma",
      therapy_elaborate:
        "To achieve the process of Purva Karma, Snehana Karma (oleation therapy) and fomentation were applied over the fractured area. Seethodaka oil and paste of Katakaladi were applied for the Virechana Karma of Shodhana Chikitsa and it probably regularized the blood circulation around the fractured bone.It initiates the formation of hematoma subsequently resolving into granulation tissue with the typical inflammatory cascade. In this case, it is in a nonunion state thus Virechana Karma of Shodhana treatment would trigger the granulation tissue formation which subsequently leading to soft callus and finally trigger the hard callus formation. Initial 6-month period topical (Seethodaka oil and Katakaladi paste) and oral medicines (Triphala decoction, Vasa-Guduchiyadi decoction and Gandharva-Hastadi decoction) were selected which has properties of Virechana while next 6 months medicines were administered having properties of Shamana. Last 1-year period, oral and topical Tarpana medicines were administered to enhance the strength of the bones, nerves and muscles.",
      medicine:
        "Hadjod(Haritiki),Haridra(Turmeric),Shallaki or Boswellia serrata,Punarnava",
      description:
        "1.Hadjod, also known as Cissus quadrangularis, is a herb used in Ayurveda for centuries to treat bone fractures. It is rich in calcium, phosphorus, and vitamin C, essential nutrients for bone health. Hadjod increases bone mineral density, reduces inflammation, and promotes bone healing.Hadjod or Bonesetter is an ancient plant commonly used in India. It is famous for its fracture healing properties due to various antioxidants such as phenols, tannins, carotenoids, and Vitamin C present in it. As per Ayurveda, consuming Hadjod juice along with cow’s ghee or a cup of milk helps in healing bone fractures due to its Sandhaniya (promoting the union of fractured parts) property,2.Turmeric is a deep, golden-orange spice known for adding color, flavor and nutrition to foods. A relative of ginger, turmeric comes from the rhizome (root) of a native Asian plant and has been used in cooking for hundreds of years.Turmeric's active ingredient curcumin is an anti-inflammatory. Researchers are looking into its potential role in the prevention of cancer and other diseases as well. Turmeric is also rich in vitamin C, vitamin B6, and other antioxidants that reduce the risk of serious health conditions like heart disease and diabetes,3.Shallaki is a holy plant which is widely used in traditional medicine and is considered to be an important part of Ayurvedic medicine. The oleo gum resin extracted from this plant has various medicinal properties.Arthritic patients can take 1-2 Shallaki tablets along with water to get relief from swelling in the joint. It reduces swelling as well as stiffness in the inflamed joints due to its anti-inflammatory property. Consuming Shallaki juice (before taking food) on a regular basis also helps improves brain function as it prevents cell damage caused by free radicals due to its antioxidant activity,4.Punarnava is a well known medicinal plant packed with essential nutrients, vitamins such as vitamin C and other constituents.Taking Punarnava juice before meals might help manage stomach disorders such as constipation by promoting bowel movements due to its laxative property. It also provides relief from gas and abdominal pain. Punarnava is effective in improving digestion and managing weight by suppressing appetite. Punarnava also helps increase urine production due to its diuretic activity and reduces the risk of urinary complications. It might also be useful for managing liver problems due to its antioxidant activity.",
      use: "1.Hadjod helps in wound healing due to its astringent and wound healing properties. Applying Hadjod paste on the wound helps in reducing pain and inflammation due to its analgesic and anti-inflammatory properties.Excessive consumption of Hadjod might lead to certain side effects like Dry mouth, Headache, Dry mouth, Diarrhea etc. So, it is advisable to consult a physician before using Hadjod,2.Turmeric, also known as Haridra in Ayurveda, is a potent anti-inflammatory herb commonly used to treat bone fractures. It contains a compound called curcumin, which has been shown to reduce inflammation and pain associated with bone fractures. Both as a spice and a supplement, turmeric can be taken. Because chronic inflammation contributes to many chronic diseases, curcumin may help treat conditions like inflammatory bowel disease, pancreatitis, and arthritis.We’ll get into some of those specific benefits later.And a study in mice found that 50 mg oral curcumin per kg of body weight significantly slowed the progression of OA, whereas a topical curcumin treatment provided pain relief.That said, whether these specific benefits apply to humans has yet to be seen,3.As per Ayurveda, massaging Shallaki oil along with coconut oil gently on the affected areas also provides relief from joint pains due to its analgesic property. It’s topical application helps to heal wounds due to its faster healing activity. Applying Shallaki powder (along with water in the form of a paste) on the skin helps manage the symptoms of ageing.Avoid the excessive intake of Shallaki as it might cause nausea and stomach pain,4.Applying Punarnava paste helps to heal skin due to its quick wound healing activity. Moreover, according to Ayurveda, massaging with Punarnava oil helps reduce joint pain due to its Vata balancing property.It is advisable to use Punarnava powder with water or coconut oil if you have hypersensitive skin.",
      imageUrl:
        "https://ars.els-cdn.com/content/image/3-s2.0-B9780128132593000129-f12-03-9780128132593.jpg",
    },
    {
      id: "10",
      department: "Shalakya Tantra(Surgery)",
      disease: "Angioplasty",
      therapy: "Panchakarma Therapy",
      therapy_elaborate:
        "Ayurvedic therapies like Panchakarma, Yoga, Pranayama and meditation can help improve Agni (digestive fire), clear channels, influence the nervous system, reduce stress, clear the energy pathways in the body, promote the healthy flow of Prana and improve wellness in the body. Here are the benefits of some of the common heart-support therapies.Ayurvedic practitioners believe that diminished digestive fire (Agnimandya) is the root cause of all diseases. Panchakarma procedures, which help clear the body channels, improve Agni (digestive fire) and remove toxins in the body can help improve cardiac health and overall well-being,Pranayama restores vitality to the energy channels of the body and calms and purifies the mind. What’s more, regular practice of pranayama can lower your heart rate and blood pressure.Routine prayer and meditation can help you cultivate mindfulness, stabilise your thought patterns, and improve your state of mind. When it comes to heart disease in Ayurveda, practitioners believe that praying and meditating consistently can reduce stress, improve your heart rate, and lower blood pressure. Meditation can also reduce your risk of stroke and diabetes.",
      medicine: "Guggulu,Arjuna,Pushkarmoola,Amalaki,Jatamansi",
      description:
        "1.Guggul is also known as “Pura” which means “wards off disease”. It is used as a source of commercial “Gum guggul”. The major bioactive component of Guggul is oleo-gum-resin (a mixture of an oil and yellowish or brownish fluid secreted from the plant stem or bark). It is this oleo-gum resin that is said to have therapeutic benefits.According to Ayurveda, Guggul is useful in weight management as it helps to improve metabolism and reduce Ama (toxic remains in the body due to improper digestion) by increasing the digestive fire,2.Arjuna also known as the “Arjun tree” is a widely grown tree in India. It has various medicinal properties like antioxidant, anti-inflammatory and antimicrobial.Arjuna helps reduce the risk of heart diseases. It strengthens and tones the heart muscles and helps in proper functioning of the heart. Arjuna tree also has strong anti-hypertensive property and helps reduce high blood pressure,3.Pushkarmool is also known as Inula racemosa. Pushkarmula has found its references in many ayurvedic works of literature. The plant blooms beautiful yellow flowers. It belongs to the Asteraceae family. Pushkarmool often grows in the Western Himalayas at elevations ranging from 1300 to 4500 metres.Pushkarmool has many medicinal properties and health benefits that are derived from its seeds, roots, leaves and stems. Let us learn more about this beautiful plant,4.Amalaki powder, or amla, is a supplement derived from the Indian gooseberry. It is a rich source of vitamins and bioactive compounds, and research suggests it may help support the immune system, improve digestion, and even protect against cancer.Amalaki powder is perhaps most widely promoted for its anti-aging properties,5.Jatamansi, also known as “tapaswani” in Ayurveda, is a perennial, dwarf, hairy, herbaceous and endangered plant species. It acts as a brain tonic and helps to improve memory and brain functions by preventing cell damage due to its antioxidant property. It also calms down the brain and manages anxiety as well as insomnia.According to Ayurveda, Jatamansi helps in preventing wrinkles due to its Snigdha (oily) nature. It also promotes wound healing due to its Ropan (healing) property. Taking Jatamansi powder along with honey once or twice a day helps to improve memory functions. ",
      use: "1.Guggul can be taken in the form of powder, tablet or capsule to help reduce the production of sebum which inhibits the growth of acne-causing bacteria due to its antibacterial property.Applying a paste of Guggul mixed in warm water on the joints helps to reduce joint pain.It should be kept in mind that Guggul should always be chewed well before swallowing in order to get the maximum benefits,2.For maximum benefits in case of heart problems, Arjuna chaal boiled in milk should be taken 1-2 times a day.Arjuna also helps control diarrhea, asthma and cough.External application of Arjuna bark (Arjuna chaal) helps manage various skin disorders like eczema, psoriasis, itching and rashes.One note of caution is to avoid Arjuna with anticoagulant drugs as it has blood thinning property,3.Puskarmool is an aromatic tonic, febrifuge, and expectorant with anti-inflammatory, carminative, diuretic, and antiseptic properties. The plant is used in chronic bronchitis and rheumatism. Dried rhizomes and roots are used to cure loss of appetite and stomach troubles.It does not possess any side effects, but Overconsumption may cause side effects like diarrhea, Stomach pain, bloating. However you should always consult Ayurvedic Physician before using Pushkaramoolasava,4.One group was given two 500-milligram (mg) amalaki tablets twice a day after meals, while the other group was given a placebo, or sham treatment. After four weeks, the patients who took the amalaki tablets had a significant reduction in heartburn and regurgitation symptoms,5.You can also take Jatamansi tablets or capsules which are also readily available in the market.Applying Jatamansi oil on the skin helps manage skin infections and prevents aging due to its antifungal and antioxidant activities. Jatamansi is also good for hair growth as it helps to increase the follicular size and elongate the growth phase of hair. Applying Jatamansi oil helps to promote hair growth. Jatamansi root paste can also be applied on hair to improve hair strength and growth.",
      imageUrl:
        "https://www.hopkinsmedicine.org/-/media/images/health/2_-treatment/cardiovascular/coronary-artery-disease-treatment/pcardio20140402v0001.jpg?h=360&iar=0&mh=360&mw=520&w=488&hash=7B64F38B2875E2A0714381933943DC8B",
    },
  ];
  return (
    <SafeAreaView style={{ marginHorizontal: 20, marginBottom: 50 }}>
      <View style={{ height: 50 }}>
        <Appbar
          title={item.department}
          color={COLORS.white}
          icon={"search1"}
          color1={COLORS.white}
          onPress={() => navigation.goBack()}
          onPressSearch={() => navigation.navigate("Search")}
        />
      </View>
      <FlatList
        data={Surgery}
        showsVerticalScrollIndicator={false}
        keyExtractor={(item) => item.id}
        contentContainerStyle={{ columnGap: SIZES.small }}
        renderItem={({ item }) => (
          <View style={{ marginBottom: 10 }}>
            <MedicineTile
              item={item}
              onPress={() => navigation.navigate("Departmentdetails", { item })}
            />
          </View>
        )}
      />
    </SafeAreaView>
  );
};

export default Surgery;

const styles = StyleSheet.create({});
